### ISSUE TITLE
REQUEST: Update block list without resetting the Next Update time

### ISSUE THREAD

**Issue by chmichael** [TechnitiumSoftware/DnsServer#1001]
Hello,
  Currently "update now" resets the "Next Update" time.
  
  Could you add a "checkbox" or a 2nd button not to reset the "Next Update" interval when updating the block list ?
  Or a time field which manually we set up the update time of the block list ? (this is better eg set the interval at midnight at specific time)

  So in case of emergency add/remove of a block list it would still update at the time we specified.
    
Thank you

**Comment by ShreyasZare** [comment]
Thanks for the request. The block lists are updated immediately when you change the Block List URLs option in the Settings which is why the update time is reset by adding the Block List Update Interval. Block lists are not frequently updated so it really does not matter if you do not reset the next update time. It also does not matter at what time the lists are updated since it does not affect the DNS server operations in any specific manner. Another aspect of the update is that the DNS server will check for the block list file's Last Modified data and only download and reload it if new block list file is available on the given URL. So, I am not really sure how such an option would help. Let me know if there is something that I am missing.

**Comment by chmichael** [comment]
Hello,
  Understood but in order to avoid major cpu usage and network delays i have set them up to check at midnight.
  Some big lists are updating daily. So imagine downloading and processing big lists at work time it might cause delays to dns requests especially if you have the server on VPS which they usually use 1 core or Rasberry.

Anyhow i am leaving it up to you to decide.

Thank you

**Comment by ShreyasZare** [comment]
You really do not have to worry about that. The block lists are downloaded and updated in background and does not affect the DNS server's performance. It also takes less than a couple of seconds to load block list file with 1mn records on my Raspberry Pi and it would be even faster on a VPS. So, even if you have large block lists configured, it would get updated in just few seconds.

**Comment by chmichael** [comment]
Ok then i am closing the request

Thank you
