### ISSUE TITLE
[Feature Request]  Allow http blocklists

### ISSUE THREAD

**Issue by dl12345** [TechnitiumSoftware/DnsServer#1015]
In an attempt to get around the issue I raised [here](https://github.com/TechnitiumSoftware/DnsServer/issues/1014), I setup my nginx to host a whitelist.

This nginx is running in a docker container on the same machine as my Technitium server. This means that the external IP address of the VM is not visible to the Technitium container and I thus need to configure the nginx to listen for connections on the docker bridge so that Technitium can access the nginx service.

The Technitium blocklist will always ignore a http URL and attempt to connect with https (any :80 is removed from the URL). This in turn means that the SSL certificate validation will produce an error, since the x590 certificate contains the correct canonical name of the server, meaning that the blocklist load will fail.

**Comment by ShreyasZare** [comment]
Thanks for the post. This restriction is there by design for security reasons. If you have the file on the same server, you can use the `file://` URI format instead of trying to get the file over HTTP. 

Check for the help info that is available in the GUI where you configure the block list URL to see how to use local file URI. Let me know if you have any issues with the config.

**Comment by ShreyasZare** [comment]
Apologies for the previous response which was made due to some confusion. I checked it again and there is no such restriction and you will be able to use a http URL. The port 80 in URL gets removed since 80 is the default port and will not affect anything.

You need to check the nginx config once again and test the URL on your web browser before you use it as the block list URL.

Try it again and let me know if it worked.

**Comment by dl12345** [comment]
> You need to check the nginx config once again and test the URL on your web browser before you use it as the block list URL.

You're absolutely correct. There was an error in the nginx.conf that was redirecting the URL to https. When I correct it, then the http blocklist is correctly loaded. Apologies. Closing this issue.
