### ISSUE TITLE
clients rate limited

### ISSUE THREAD

**Issue by REZAFatf** [TechnitiumSoftware/DnsServer#1042]
Hi

today, I see this screenshot and some of our users are rate limited? what is that?

![Screenshot 2024-09-23 112330](https://github.com/user-attachments/assets/7399f38b-9c06-47f6-8f45-adfdad1d49a3)

**Comment by ShreyasZare** [comment]
Thanks for asking. The DNS server has default rate limiting option configured to prevent abuse which is causing this. You just need to change the QPM Limit values in Settings > General section. You can set it to `0` to disable rate limiting if this DNS server is only accessible on your local network.

**Comment by REZAFatf** [comment]
I have update technitium to V13 and I noticed the Concurrent Forwarding. Does it make the webpage opening more slow?

**Comment by ShreyasZare** [comment]
> I have update technitium to V13 and I noticed the Concurrent Forwarding. Does it make the webpage opening more slow?

Concurrent Forwarding feature already existed and was used by default. This new option now allows you to disable it if you need the DNS server to query the forwarder in sequential order as they are listed.

Concurrent Forwarding will make DNS resolutions faster, not slower since they will be querying multiple forwarders simultaneously and use the fastest response.
