### ISSUE TITLE
Stub zones can be added to catalog but doesn't work

### ISSUE THREAD

**Issue by ruifung** [TechnitiumSoftware/DnsServer#1045]
If you look under zone options for Stub zones, they can be added to a catalog. However, it gets synced to secondaries as a stub zone missing the NS record, which sort-of defeats the point of adding it to the catalog.

Suggest adding some validation to prevent stub zones from being added to a catalog zone I suppose? Or if possible, make it be able to be replicated to secondaries too.

**Comment by ShreyasZare** [comment]
Thanks for the post. Stub zone will get replicated to all secondaries as a Stub zone itself. Since a stub zone is not authoritative for any of its contents, the Stub zone that gets automatically created on secondary server will fetch its records just like how the Stub zone on the primary server does. If a Primary Name Server Address was specified in the Stub zone on primary server then the same will be used by Stub zone of the secondary server to fetch NS records.

**Comment by ruifung** [comment]
Huh, just tested again, and it does indeed work that way. No idea why it failed the first time around.
