### ISSUE TITLE
How can i use these dns server with my client on mikrotik

### ISSUE THREAD

**Issue by muhanadali100** [TechnitiumSoftware/DnsServer#106]
I have an clients how can i use the dns server for all with mikrotik from my PC

**Comment by ShreyasZare** [comment]
You cannot install the DNS server on your router. You will need to install the DNS server on a computer that will run 24hrs everyday. Preferred option is to get a small device like Raspberry Pi and install the DNS server on it as the device will consume less power and can be kept running continuously.

Once you have this device/computer with DNS Server running, make sure that the computer has fix IP address i.e. manually configure the IP address on it so that it does not change. Now, use this IP address as DNS server in your mikrotik router's DHCP settings. Once you have it configured, the router will automatically give the IP address of your DNS server to all clients in the network and all DNS queries will go to the DNS server.

If you have any more queries, do send an email to support@technitium.com.

**Comment by muhanadali100** [comment]
can you make a video for that please ?

**Comment by muhanadali100** [comment]
![77](https://user-images.githubusercontent.com/31727156/71547340-f682bc00-29af-11ea-8dbb-914b5874f2b4.png)
![64](https://user-images.githubusercontent.com/31727156/71547341-fa164300-29af-11ea-8dcc-d1612dc44ba6.png)

The DHCP-SERVER Not working !

**Comment by Globulopolis** [comment]
@muhanadali100 enable DHCP in you network settings. See https://www.dummies.com/wp-content/uploads/Configuring-TCP-IP2.jpg

**Comment by muhanadali100** [comment]
> 
> 
> @muhanadali100 enable DHCP in you network settings. See https://www.dummies.com/wp-content/uploads/Configuring-TCP-IP2.jpg

i make this but doesn't work

**Comment by muhanadali100** [comment]
![81022289_1231634120374273_3330209751739924480_n](https://user-images.githubusercontent.com/31727156/71547917-6d6f8300-29b7-11ea-86bd-afc542b0f56f.png)

in the second PC not working !! 
I make every thing but not working 

Can you make a slide picture for that or a video for help me please

**Comment by Globulopolis** [comment]
@muhanadali100 PC with DNS server must have a static IP-address.
As I see on you last screenshot, this PC and DNS server gets an IP from DHCP pool.

**Comment by muhanadali100** [comment]
My friend this from my mikrotik router and it's static ip but private ip , so i want to use the dns server for my clients but i can't , Each client have ip different from each other

**Comment by Globulopolis** [comment]
@muhanadali100 cannot understand that you're trying to do.
If all you clients connected to mikrotik, try to set up DNS under the `Bridge`. Something like this:

![image](https://user-images.githubusercontent.com/740757/71549885-39578a80-29d6-11ea-9345-ed007fb513ba.png)

**Comment by muhanadali100** [comment]
My friend , I fix it and the dhcp-server is working but the client don't have internet ??

i installed the dns-server in windows 10 
i have network from my router 

if i connect the client by the bridge the client get the ip from my pc so he haven't internet

f you allow me, I want your connection between the DNS Server device, the mikrotik, and the client
and how the client have internet please

**Comment by muhanadali100** [comment]
My server ![76](https://user-images.githubusercontent.com/31727156/71549936-3315de00-29d7-11ea-8907-6207f13052ba.png)
My PC ![78](https://user-images.githubusercontent.com/31727156/71549943-47f27180-29d7-11ea-9526-549c1b69d3a4.png)

![79](https://user-images.githubusercontent.com/31727156/71549952-67899a00-29d7-11ea-9b87-1241bc100868.png)

![80](https://user-images.githubusercontent.com/31727156/71549953-6b1d2100-29d7-11ea-997c-8d25edd1b706.png)
![81](https://user-images.githubusercontent.com/31727156/71549960-a0c20a00-29d7-11ea-9e50-f274207a2301.png)

**Comment by muhanadali100** [comment]
i fix it ... that's proplem



![899](https://user-images.githubusercontent.com/31727156/71550830-3ebed000-29ea-11ea-8733-04ff6c36a518.png)

**Comment by ShreyasZare** [comment]
> can you make a video for that please ?

Making video tutorials is not feasible due to lack of resources. I would suggest that you read on some basic home networking concepts that will help you in understanding and configuring things in long run. 

This gives me idea about writing a new blog post to help people with no background knowledge to help them understand some basic concepts about configuring home routers. I will try to write this once I get some time in coming days.

**Comment by ShreyasZare** [comment]
@muhanadali100 from seeing the about posts there are few things that you need to follow for your home network to work correctly:
- there should be only one DHCP server running in a single network. If you have your router which by default has DHCP configured and running then you should not enable the DHCP server provided by Technitium DNS Server. If you wish to use DHCP server provided by Technitium DNS Server then you need to disable the DHCP server in your router.

- The IP address range that you are using for your home network i.e. 11.11.11.0/24 is invalid for private network usage. This will cause issue as you wont be able to access any website hosted on the public IP address in that range since your router thinks you own this public IP address range. You must use a suitable network range only from the valid private network address ranges of 10.0.0.0/8, 192.168.0.0/16 or 172.16.0.0/12. Most routers use 192.168.0.1/24 for simplicity so you can use a network range in similar fashion. With the correct IP address range being used, you wont need to uncheck the "Allow Recursion Only For Private Networks" option in settings.

- If you configure DHCP on the Technitium DNS Server and disable it from your router then, you need to make sure that your router's IP address is in the same DHCP network range and your router's IP address is set in the DHCP Router Address option.

- The computer you want to run DNS server must have manually configured IP address so that it does not change in future as you have configured that IP address in your DHCP settings.
