### ISSUE TITLE
Frequent DNS Zone Updates Causing File Size Growth with external-dns

### ISSUE THREAD

**Issue by DRON4eg** [TechnitiumSoftware/DnsServer#1092]
Version v13.1 ARM in Docker.
DNS zone files grow significantly in size with frequent updates (DNSServer is used together with external-dns + RFC 2136). Each time a zone update occurs, the size of the zone increases, although the actual number of records in the zone remains the same – external-dns just updates the existing records.
Recently, it was noticed that one of the zones has exceeded 60 MB, whereas converting it to any other type of zone reduces its size to just a few kilobytes.

If any other information is needed, I'm willing to provide it.

**Comment by ShreyasZare** [comment]
Thanks for asking. This is expected since the DNS server maintains zone history for the incremental zone transfer (IXFR) to work. The old records are kept up to the SOA Expiry, i.e. if zone's SOA expiry is 7 days then the history is maintained for all changes for past 7 days. Since you have frequent changes, the zone size has increased considerably. If you want to keep the zone size low then just reduce the SOA Expiry to a suitable value.

**Comment by DRON4eg** [comment]
> Thanks for asking. This is expected since the DNS server maintains zone history for the incremental zone transfer (IXFR) to work. The old records are kept up to the SOA Expiry, i.e. if zone's SOA expiry is 7 days then the history is maintained for all changes for past 7 days. Since you have frequent changes, the zone size has increased considerably. If you want to keep the zone size low then just reduce the SOA Expiry to a suitable value.

I hadn't thought of that, thanks for such a quick reply.
