### ISSUE TITLE
DHCP Server should be able to dynamically register multiple A records in a DNS zone for the same hostname

### ISSUE THREAD

**Issue by cowegner** [TechnitiumSoftware/DnsServer#1093]
Actual behavior:
It is possible to manually register the same hostname in a DNS zone with different IP addresses, leading to multiple A Records with the same name in a DNS zone. This is intentional.

Dynamic registration through DHCP server logs the following message: DHCP Server cannot update DNS: an A record already exists for '<hostname>' with a different IP address [<IP address>]
There will be no second A record for the hostname.

Expected behavior:
The hostname will also be registered with the second IP address in DNS, leading to two (or even more) A records.

Further information:
Think of a host with multiple subnets attached.
This might also somehow relate to #394, for it will lead to multiple A records with the same name.

**Comment by ShreyasZare** [comment]
Thanks for the post. This is by design to avoid a DNS entry to get changed accidentally or maliciously by an actor in network. So, dynamic leases will be able to add DNS entry only when there is no existing entry in the zone.

Since the DHCP server cannot know if the lease belongs to the same server, it cannot coordinate the DNS entries accordingly.

In your scenario, since you need to have two IP addresses for the same host, you will have to manually configure the DNS entries for it.
