### ISSUE TITLE
Ipv6 issue. 

### ISSUE THREAD

**Issue by t-e-s-tweb** [TechnitiumSoftware/DnsServer#1098]
Hello I am on an ipv6 only network and while recursion works fine for all other domains but for this I get this error. 

I have ipv6 preferred. Also if I use the DNS client to only do a ipv6 query then I do get ipv6 addresses for the domains shown in the screenshot. However if I access it normally then it tries connecting to these ipv4 addresses. 
![Screenshot_20241103_193030_Chrome](https://github.com/user-attachments/assets/96885ca4-576f-485f-b7ef-91501510c956)

**Comment by ShreyasZare** [comment]
Thanks for the feedback. For this specific domain name, the glue records returned are for only ipv4 which is why the resolver is trying to use them. I will test the resolver and see how it can be updated to try to find the ipv6 addresses in such scenarios when preferIPv6 is enabled. Till then you can create a Conditional Forwarder zone for this domain name and forward it to any other DNS server that is able to resolve it.

Note that with ipv6 only Internet connectivity, there may be domain names that would fail to resolve since they do not have any name servers running on ipv6. For this specific case, the name servers have ipv6 addresses but they are not being included as glue addresses causing this issue.

**Comment by ShreyasZare** [comment]
> The clients can access both 4 and 6 so that isn't an issue. The server doesn't provide any adress that causes issues.

Its not about client connectivity. The DNS server needs to have ipv4 too for it to be able to resolve domain names that do not have any name servers on ipv6.

> Any ways it happens on some other domains too after looking at the logs. Namely api-45-0-0.twitter.com

That domain does not have any ipv6 name servers which is why it wont resolve. You can check it [here](https://dnsviz.net/d/api-45-0-0.twitter.com/servers/).

**Comment by ShreyasZare** [comment]
Technitium DNS Server v13.1.1 is now available which fixes this issue. Do update and let me know your feedback.

**Comment by ShreyasZare** [comment]
Thanks for the feedback!
