### ISSUE TITLE
Round Robin or Shuffle Disable Option

### ISSUE THREAD

**Issue by salmanshafi404** [TechnitiumSoftware/DnsServer#1109]
Hey please add shuffle dissble option, i Don't like shuffle in Nameserver!

**Comment by ShreyasZare** [comment]
Thanks for the post. Please let me know in detail what issue are you having due to the NS record shuffling.

**Comment by salmanshafi404** [comment]
If I set up Technitium as ns1, ns2, and ns3, Technitium answers with ns2, ns1, and ns3, or ns3, ns2, ns1 in reverse order. This looks strange to me when I see it. I am not facing this issue with knot dns but knot don’t provider gui like technitium! I wanna disable shuffle in techtenium with any records

**Comment by ShreyasZare** [comment]
The DNS server shuffles NS records for all local zones so that the load is evenly distributed for all name servers as some resolvers may not shuffle the list before using it. I understand that it may look annoying when you query to check the records but its a useful to have feature. Many name servers do that for example you can [check here](https://dnsclient.net/#Recursive%20Query%20%7Brecursive-resolver%7D/google.com/NS/UDP/false/) that Google's name servers do the same. You already have those NS records in your zone to view in a fixed order as you entered it if you need to check them.

**Comment by salmanshafi404** [comment]
But knot dns not shuffling & maximum resolver 1.1.1.1,9.9.9.9,etc also same

**Comment by ShreyasZare** [comment]
> But knot dns not shuffling & maximum resolver 1.1.1.1,9.9.9.9,etc also same

That's true but its not useful for a public DNS resolvers or recursive resolvers to shuffle NS records since this feature is only useful for authoritative name servers. Technitium DNS server shuffles NS records only for authoritative zones it hosts and does not do for NS queries that are resolved recursively or forwarder.

The shuffle feature does not cause any issues and it does help in evenly distributing load across the name servers which is an issue some people do have which they are not aware of. 

Now, adding a configurable option for this would need time and effort which does not really justify it since its not really causing something to break or having a non-standard response. The list of records in DNS response is always an unordered list by standard.

**Comment by salmanshafi404** [comment]
Sorry for my bad english confusion i opened a issue for authorarativ zone shuffle disable not enable in recursive

**Comment by ShreyasZare** [comment]
> Sorry for my bad english confusion i opened a issue for authorarativ zone shuffle disable not enable in recursive

I know, but you compared with public DNS resolvers like 1.1.1.1, 9.9.9.9 in previous comment.

**Comment by salmanshafi404** [comment]
But my request is to add round robin disable option in technitium dns

**Comment by ShreyasZare** [comment]
> But my request is to add round robin disable option in technitium dns

I would have added the option but I do not see a technical need to have one since the issue here is just that you don't like the order in which NS records are listed and its not really affecting anything.
