### ISSUE TITLE
Random Authoratative NSEC3 Resolution Failure

### ISSUE THREAD

**Issue by AceBlade258** [TechnitiumSoftware/DnsServer#1121]
> > > Do you have any of the zones signed with DNSSEC? If yes, are you using NSEC3?
> > 
> > Yes, to both questions - all of them.
>
> There have been similar feedback from a few people but the issue is such that I am unable to reproduce it at all. Its also rare so only a handful installations are reporting it. Will see if I can find more clues on it.
> 
> _Originally posted by @ShreyasZare in https://github.com/TechnitiumSoftware/DnsServer/issues/1114#issuecomment-2495379600_

Opening this issue based on the above comment. I have a pair of servers (primary/secondary) hosting a single domain reliably reproducing this issue. How can I help to resolve (pun intended) this issue?

**Comment by ShreyasZare** [comment]
Thanks for the post. It would be nice if you can share the full backup zip (including logs) of the primary DNS server so that this can be tested independently on my local test setup. You can send the zip to support@technitium.com. The file will be used only for testing and all data will be deleted once the tests are done.

I understand that this may not be possible for you to share it. But the issue is otherwise proving to be difficult to reproduce. I have had only like 4 people reporting it so there is almost no info available on how to reproduce it. One guy had shared only the zone file which he believed caused the issue but on my test setup with a load testing tool used to bombard the zone with multiple queries did not trigger the issue at all.

**Comment by AceBlade258** [comment]
Backups sent; please let me know if I can help further.

**Comment by ShreyasZare** [comment]
> Backups sent; please let me know if I can help further.

Thanks for that. Will test with it soon and let you know how it goes.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v13.3 is now available that fixes this issue. Do update and let me know your feedback.
