### ISSUE TITLE
Unable to update dns name 

### ISSUE THREAD

**Issue by Amateur-God** [TechnitiumSoftware/DnsServer#1128]
im trying to update my dns name so that i can enable doh however whenever i click save, even if I've made no edits i get 

```
Error! Invalid domain name [dns 2]: invalid character [32] was found.
```

i believe it thinks there is a space somewhere as im sure ASCII 32 is space, however ive doublechecked and there is no space anywhere, ive even restart the server, gone to settings and clicked save without making any edits and i get the same error

**Comment by ShreyasZare** [comment]
Thanks for the post. It seems that the domain name `dns 2` is being set somewhere causing this issue. Please check the DNS logs from admin panel and share the complete error message so that I can know exactly where its coming from.

Secondly, for DoH, you can use any domain name that the SSL/TLS cert contains and there is no need for the domain name to be configured as DNS Server Domain name in settings.

**Comment by Amateur-God** [comment]
From what I can tell this is the part relating to the error 

```
[2024-11-28 08:19:14 UTC] [192.168.5.246:64541] TechnitiumLibrary.Net.Dns.DnsClientException: Invalid domain name [dns 2]: invalid character [32] was found.
   at TechnitiumLibrary.Net.Dns.DnsClient.IsDomainNameValid(String domain, Boolean throwException) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 2532
   at DnsServerCore.WebServiceSettingsApi.SetDnsSettings(HttpContext context) in Z:\Technitium\Projects\DnsServer\DnsServerCore\WebServiceSettingsApi.cs:line 1071
   at lambda_method53(Closure, Object, HttpContext)
   at DnsServerCore.DnsWebService.WebServiceApiMiddleware(HttpContext context, RequestDelegate next) in Z:\Technitium\Projects\DnsServer\DnsServerCore\DnsWebService.cs:line 682
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

RE DoH doesn't the domain have to resolve to the ip of the DNS server? 

I just setup a local only subdomain on an existing FQDN i had and used DNS-01 validation with certbot and cloudflare to set up an auorenewing certificate for a domain that doesn't actually resolve anywhere on the Internet only resolves on my lan and setup a renewal hook to make it a pkcs#12

But I can't even enable DoH in the settings atm as I can't save any settings changes

**Comment by ShreyasZare** [comment]
Thanks for the error details. It seems that the invalid domain name is set in the TSIG section in one of the Key Names.

> RE DoH doesn't the domain have to resolve to the ip of the DNS server?

Since your earlier comment did not mention where you are entering the domain name, I assumed that you were configuring it for the DNS Server Domain Name in Settings section.

> I just setup a local only subdomain on an existing FQDN i had and used DNS-01 validation with certbot and cloudflare to set up an auorenewing certificate for a domain that doesn't actually resolve anywhere on the Internet only resolves on my lan and setup a renewal hook to make it a pkcs#12

I am not sure how its possible to renew cert for an private domain name with DNS challenge. I would suggest that you review the setup once since its not possible and if you really did succeed then will be a huge deal.

**Comment by Amateur-God** [comment]
Perfect, I found it, thank you. I'm not sure how that managed to get saved before.

Re DNS for a private subdomain, it's possible using a DNS-01 with certbot which uses a txt acme challenge in the domains public dns to verify ownership of the domain, there doesn't actually need to be a A record for the domain in the public dns for it to work. 

That's how I did it, I have the A record for the DoH subdomain in technitium but not in cloudflare then certbot with my cloudlfare api credentials just puts a txt entry for the subdomain in the DNS verifying ownership and letting the verification for LE pass

I can write up some detailed instructions, including a script to automate the creation of a pcks#12 making the entire renewal process fully automated if you would like

**Comment by ShreyasZare** [comment]
> Perfect, I found it, thank you. I'm not sure how that managed to get saved before.

You may have had set it earlier since the current major update had added the additional validation check since many people had issue with invalid domain name set as Key Name and it caused TSIG auth to fail with errors.

> That's how I did it, I have the A record for the DoH subdomain in technitium but not in cloudflare then certbot with my cloudlfare api credentials just puts a txt entry for the subdomain in the DNS verifying ownership and letting the verification for LE pass

That means you have the actual domain hosted on cloudflare where the DNS challenge TXT is added and have a subdomain zone that works internally on LAN, which is fine.
