### ISSUE TITLE
Errors in log

### ISSUE THREAD

**Issue by Globulopolis** [TechnitiumSoftware/DnsServer#113]
After flush dns cache I see these errors in log. Not only for imx.to host.

> [2020-01-13 10:07:18 UTC] DNS Server recursive resolution failed for QNAME: imx.to; QTYPE: A; QCLASS: IN;
> 
> System.Security.Authentication.AuthenticationException: Ошибка вызова SSPI, см. внутреннее исключение. ---> System.ComponentModel.Win32Exception: Получено непредвиденное сообщение или оно имеет неправильный формат
> 
>    --- Конец трассировки внутреннего стека исключений ---
> 
>    в System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
> 
>    в System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
> 
>    в System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
> 
>    в System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
> 
>    в System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
> 
>    в System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
> 
>    в System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
> 
>    в System.Net.Security.SslStream.AuthenticateAsClient(String targetHost)
> 
>    в TechnitiumLibrary.Net.Dns.ClientConnection.TlsClientConnection.GetNetworkStream(Socket socket)
> 
>    в TechnitiumLibrary.Net.Dns.ClientConnection.TcpClientConnection.GetConnection()
> 
>    в TechnitiumLibrary.Net.Dns.ClientConnection.TcpClientConnection.Query(DnsDatagram request)
> 
>    в TechnitiumLibrary.Net.Dns.DnsClient.Resolve(DnsDatagram request)
> 
>    в DnsServerCore.Dns.DnsServer.<>c__DisplayClass71_0.<RecursiveResolve>b__0(Object state)
> 
> [2020-01-13 10:07:18 UTC] [10.10.10.10:63842] [UDP] QNAME: imx.to; QTYPE: A; QCLASS: IN; RCODE: ServerFailure; ANSWER: []

**Comment by ShreyasZare** [comment]
Thanks for the feedback. The exception is about SSL connection to the forwarder server failing either due to some network issue or could even be deliberate attempt to reset the SSL connection.

Once you clear cache, the DNS server has no option but to find the answers again. If you dont flush cache then the server will still respond with old IP address from cache for up to 7 days because of the serve stale feature.

I would suggest that you try changing your forwarder to another provider and see if it works. Do try DoH instead of DoT and see if it makes any difference as DoH is a bit tricky to block.

**Comment by Globulopolis** [comment]
Ok. I need some time to test for DoH.
