### ISSUE TITLE
Unable to add CNAME at apex on a subdomain zone

### ISSUE THREAD

**Issue by wdhdev** [TechnitiumSoftware/DnsServer#1134]
I have a zone created called `william.is-a.dev`, which is a subdomain of `is-a.dev`.

However I cannot add a CNAME record at the apex (`william.is-a.dev`), even though it is a subdomain. Is it possible to adjust the logic so a CNAME record can be added at the apex when the zone name is actually a subdomain?

I'm aware of ANAME records, however I am using Cloudflare's Secondary DNS service, which does not support them, so it would cause some issues.

**Comment by ShreyasZare** [comment]
Thanks for the post. The issue with CNAME is that you cannot have CNAME and any other record type (except RRSIG) co-exist for the same domain name. Which is why you cannot add CNAME to a zone's apex since a zone must have a SOA and NS records.

If possible use the parent zone `is-a.dev` itself instead of creating a zone for the subdomain name. That's the only way you could add a CNAME record for it.

**Comment by wdhdev** [comment]
Ah okay, I forgot about that. My bad, thank you.
