### ISSUE TITLE
TLS Certificate not being generated with SAN fields (IP Address)

### ISSUE THREAD

**Issue by cob-web-corner** [TechnitiumSoftware/DnsServer#1138]
Version 13.2.2

Update: 

Automatically generated self-signed certificate is missing SAN field with IP Address. In environments where users are likely to use the self-signed certificates its a good idea to include the IP Address.

https://www.rfc-editor.org/rfc/rfc6125
https://www.rfc-editor.org/rfc/rfc9525

example
```
X509v3 Subject Alternative Name: 
                DNS:dns.example.com, IP Address:192.168.1.100
```

_________
Original Issue filed (no longer relevant):

> When enabling the https option under settings > web service you can optionally enable another setting `Use A Self Signed TLS Certificate When TLS Certificate File Path Is Unspecified`. I have enabled both (see image below), however a self-signed certificate is not being generated.
> 
> ![image](https://github.com/user-attachments/assets/ac0d4282-e548-402a-9483-b362ba673240)
>  
> When navigating to the server's webpage using the default https port I get the following error:
> 
> ![image](https://github.com/user-attachments/assets/51c544cb-ba24-4f29-93ce-96202ac5e69b)

**Comment by Hemsby** [comment]
From memory, I think Firefox also blocks Self Signed unless you explicitly allow them.  Does the same happen with other browsers like Edge for example?

**Comment by ShreyasZare** [comment]
Thanks for the feedback. The IP is not included in the cert since its not really required for self signed certs. 

This is what Firefox shows when you have self signed cert configured:

![image](https://github.com/user-attachments/assets/ff7b801b-f339-489b-8381-0b0e93904680)

This is with Chrome:

![image](https://github.com/user-attachments/assets/d70fa43c-faa8-4417-947c-e9906a29d28c)

Just proceeding to view the page works and it does not matter if you used domain name or the IP address.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v13.3 is now available that adds SAN entries for local unicast addresses for self signed certs. Do update and let me know your feedback.

**Comment by ShreyasZare** [comment]
Thanks for confirming!
