### ISSUE TITLE
Automated Installer does not properly configure systemd file

### ISSUE THREAD

**Issue by jftuga** [TechnitiumSoftware/DnsServer#1150]
On `Ubuntu 24.04.1 LTS`, I used `snap` to install `dotnet` because it installed a newer version vs using `apt`:

    snap install dotnet-sdk --classic

This then installs the binary to: `/snap/bin/dotnet`

Therefore, I needed to modify my `/etc/systemd/system/dns.service` file:

* from: `ExecStart=/usr/sbin/dotnet /opt/technitium/dns/DnsServerApp.dll /etc/dns`
* to: `ExecStart=/snap/bin/dotnet /opt/technitium/dns/DnsServerApp.dll /opt/technitium/dns`

There are two changes I made:

* `/usr/sbin/dotnet ` -> `/snap/bin/dotnet`
* `/etc/dns` -> `/opt/technitium/dns`

Would it be possible for you to update the [install.sh](https://download.technitium.com/dns/install.sh) to properly handle the scenario?

Thank you.

**Comment by ShreyasZare** [comment]
Thanks for the post. Microsoft does [not recommend](https://learn.microsoft.com/en-us/dotnet/core/install/linux-snap-runtime) using snap to install dotnet. Also note that you need to install dotnet runtime only and SDK is not needed to be installed.

![image](https://github.com/user-attachments/assets/ffd0f646-cb40-478b-b389-501866447837)

If you are manually installing dotnet then make sure that you create a link (using ln -s) so that dotnet works with `/usr/bin/dotnet` path. This will make the installer detect dotnet and work as expected and there wont be any need to change how the installer works.

I would recommend to allow the script to install dotnet instead of manually installing it. The reason for this is that you will have to update dotnet to the latest release manually each time you update the DNS server. If the installer has installed dotnet, it will automatically update dotnet every time you upgrade the DNS server.

**Comment by jftuga** [comment]
Thanks for the follow up and detailed explanation. I really appreciate it. 😃
