### ISSUE TITLE
Feature Request: Offer to manage and maintain reverse zone....

### ISSUE THREAD

**Issue by natiki** [TechnitiumSoftware/DnsServer#12]
A handy feature would be that as you create the forward zone the server offers to manage the reverse zone for you.

**Comment by ShreyasZare** [comment]
This feature request is really tricky to implement since the admin may want to manage the reverse zone in a particular way and the feature may add the entries in other way. There is also issue when you add same IP address for two different records since creating multiple PTR records for reverse lookup is not recommended and will have undesirable outcome due to various DNS client implementations.

This feature would work best with a coupled DHCP server which will add the reverse lookup entry after assigning IP address. Closing this issue here and will track it on the DHCP issue.

**Comment by natiki** [comment]
Can u add the issue reference for the DHCP issue so that it is linked here?

**Comment by ShreyasZare** [comment]
DHCP feature request #32

**Comment by ShreyasZare** [comment]
This feature is now available with release of v4.0 that includes DHCP server.
