### ISSUE TITLE
Remember selected filter on Dashboard

### ISSUE THREAD

**Issue by Globulopolis** [TechnitiumSoftware/DnsServer#121]
It is a feature request.
Store in cookie or localStorage currently selected filters and apply on dashboard load. Because untick every time on unnecessary filters is boring.

**Comment by ShreyasZare** [comment]
Thanks for the feedback, It will indeed be useful to have it.

**Comment by Cossey** [comment]
@Globulopolis this is indeed useful. Also, it seems that the legend filter is lost when the data automatically refreshes every 60 seconds when the *Last Hour* filter is selected as well as when you change the filters.

I have some working modifications that will save this filter when changed, then on page reload or filter change it will load. This is stored in localStorage as suggested since it involved minimal modifications.

As a by-product it will also update the charts "the suggested way" so that their data transition animations work fine.. I will submit a PR after additional testing.

**Comment by ShreyasZare** [comment]
@Cossey Thanks for the PR. How about having these changes only for the current session and not use local storage? I am more inclined to not store any data/cookie on client browser.

@Globulopolis what do you say? should the web console remember the view or should it refresh if page reloads?

**Comment by Globulopolis** [comment]
> How about having these changes only for the current session and not use local storage? I am more inclined to not store any data/cookie on client browser.

Then how about to store this option in global config?

> should the web console remember the view or should it refresh if page reloads?

Should remember.

**Comment by ShreyasZare** [comment]
> 
> > How about having these changes only for the current session and not use local storage? I am more inclined to not store any data/cookie on client browser.
> 
> Then how about to store this option in global config?
> 
> > should the web console remember the view or should it refresh if page reloads?
> 
> Should remember.

The web app is independent of the DNS Server and uses the API for interaction. So making UI specific backend API options would not be ideal. Local storage looks good in that case then

@Cossey lets keep it that way. I will test it locally as soon as I can get some time.

**Comment by ShreyasZare** [comment]
New update v6.0 is now available for download that adds this feature thanks to @Cossey .
