### ISSUE TITLE
Provide an official docker image

### ISSUE THREAD

**Issue by davidecavestro** [TechnitiumSoftware/DnsServer#123]
Please provide an official image for docker.

Some examples
- [ts-dnsserver](https://hub.docker.com/r/roxedus/ts-dnsserver) hosted at https://github.com/Roxedus/docker-TS-DnsServer
- [technitium-dns-docker](https://hub.docker.com/r/sjkp/technitium-dns-docker) hosted at https://github.com/sjkp/technitium-dns-docker

Please note the former seems to support both amd64 and arm64.

**Comment by ShreyasZare** [comment]
Thanks for the request.

**Comment by chrismeller** [comment]
Just a heads up for anyone else who is looking for something similar, I use [m400's image](https://hub.docker.com/r/m400/technitium) because 1) it is updated regularly, 2) actually gets tagged with the release number, 3) supports arm7, arm64, and amd64, and 4) has the Dockerfile in a Github repo so you can tell what's going on.

**Comment by ShreyasZare** [comment]
Official Docker image is now available: [technitium/dns-server:latest](https://hub.docker.com/r/technitium/dns-server)
