### ISSUE TITLE
[Not Issue] - custom block page 

### ISSUE THREAD

**Issue by vvcares** [TechnitiumSoftware/DnsServer#126]
Hi, this is a simple yet powerful DNSapp. can do redirect the blocked page to custom html ?

**Comment by ShreyasZare** [comment]
Thanks for the feature request. Custom page when domain name is blocked is not technically feasible due to HTTPS. Most websites now deploy HTTPS and thus trying to hijack the blocked website to display custom page will create SSL/TLS errors with web browser. Most ads are within an iframe and with such setup you will see these errors in each iframe.
