### ISSUE TITLE
Bug: truncated TXT records for relayed domains

### ISSUE THREAD

**Issue by shawnkhall** [TechnitiumSoftware/DnsServer#143]
Using Technitium DNS Server 4.1

The following DNS request truncates the multi-line SPF/TXT record:

`nslookup -type=txt spf.messagingengine.com 127.0.0.1`

    spf.messagingengine.com text =
        "v=spf1 ip4:66.111.4.25 ip4:66.111.4.26 ip4:66.111.4.27 ip4:66.111.4.28 ip4:66.111.4.29 ip4:66.111.4.221 ip4:66.111.4.222 ip4:66"`

This is what should be returned:

`nslookup -type=txt spf.messagingengine.com 8.8.8.8`

    spf.messagingengine.com text =
        "v=spf1 ip4:66.111.4.25 ip4:66.111.4.26 ip4:66.111.4.27 ip4:66.111.4.28 ip4:66.111.4.29 ip4:66.111.4.221 ip4:66.111.4.222 ip4:66"
        ".111.4.224 ip4:66.111.4.225 ip4:66.111.4.229 ip4:66.111.4.230 ip4:64.147.123.17 ip4:64.147.123.18 ip4:64.147.123.19 ip4:64.147."
        "123.20 ip4:64.147.123.21 ip4:64.147.123.24 ip4:64.147.123.25 ip4:64.147.123.26 ip4:64.147.123.27 ip4:64.147.123.28 ip4:64.147.1"
        "23.29 -all"`

That's a huge difference and will result in errors if I use Technitium DNS for my email servers.

Don't get me wrong - their SPF record is ugly - but it's well-formed and should be respected as-is even though it's ugly.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. This bug was already spotted and fixed [here](https://github.com/TechnitiumSoftware/TechnitiumLibrary/commit/f45672594e2b5e07b604e89bf5018a65143a693f).

This change is deployed to [dnsclient.net](https://dnsclient.net) web app for testing and you can [click here](https://dnsclient.net/#Recursive%20Query%20(recursive-resolver)/spf.messagingengine.com/TXT/UDP) to see if the record is read correctly.

Next release coming in a couple of weeks will have the code changes for correctly reading the TXT records.

**Comment by ShreyasZare** [comment]
The issue has been fixed in the new release.
