### ISSUE TITLE
Does the new version support GeoIP2 national database？

### ISSUE THREAD

**Issue by thb007** [TechnitiumSoftware/DnsServer#146]
If the support GeoIP2 national database, we can on this ip / domain of the database, specify a DNS resolution.

**Comment by ShreyasZare** [comment]
The new version that is under testing does not have support for this. This feature will be added in a later release.

**Comment by Globulopolis** [comment]
Maxmind required registration to use GeoIP DB(lite and commercial). It's better to use https://db-ip.com/db/lite.php instead.

**Comment by thb007** [comment]
> Maxmind required registration to use GeoIP DB(lite and commercial). It's better to use https://db-ip.com/db/lite.php instead.

ok

**Comment by thb007** [comment]
> The new version that is under testing does not have support for this. This feature will be added in a later release.

ok thanks

**Comment by thb007** [comment]
> Maxmind required registration to use GeoIP DB(lite and commercial). It's better to use https://db-ip.com/db/lite.php instead.
I haven't found a dns that supports geoio database at the moment, do you know?

**Comment by Globulopolis** [comment]
> I haven't found a dns that supports geoio database at the moment, do you know?

BIND DNS?

**Comment by thb007** [comment]
> > I haven't found a dns that supports geoio database at the moment, do you know?
> 
> BIND DNS?
not support

**Comment by Globulopolis** [comment]
> not support

https://geoip.site ? We talk about GeoDNS?

**Comment by thb007** [comment]
> > not support
> 
> https://geoip.site ? We talk about GeoDNS?

Almost, geoip integrates a lot of domain names. We can specify DNS for resolution by domain name

**Comment by ShreyasZare** [comment]
New update v6.0 is now available for download that supports DNS Apps. A Default DNS App is now available to [download](https://download.technitium.com/dns/DefaultDnsApp.zip) which supports Split Horizon, Geo-location based responses, etc. using MaxMind GeoIP2 database.

The DNS Apps are custom apps that anyone can create so, if you want to use another database instead of MaxMind then its possible to fork the default app on GitHub and make those changes and use them on your DNS server installations.
