### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by garsia0** [TechnitiumSoftware/DnsServer#15]
have moth no problem today service fail StartUp
No se puede iniciar el servicio. System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en DnsServerCore.StatsManager.LoadLastHourStats()
   en DnsServerCore.StatsManager..ctor(String statsFolder, LogManager log)
   en DnsServerCore.DnsWebService..ctor(String configFolder, Uri updateCheckUri)
   en DnsService.DnsService.OnStart(String[] args)
   en System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Will fix this issue soon.

**Comment by zenabius** [comment]
Thr same problem!

**Comment by krismach** [comment]
It started to happen to me today, not sure what changed

**Comment by ShreyasZare** [comment]
Fix for this issue is coming in few days in the next release. This exception occurs while loading the last hour stats at 00 hrs UTC when starting the DNS Server and goes away later.

**Comment by Matthew-Bonner** [comment]
![image](https://user-images.githubusercontent.com/7858744/49692340-26b2af00-fb50-11e8-8641-41f533bc6d28.png)

**Comment by Matthew-Bonner** [comment]
Obviously, lastHourlyStats will be null if there are no stats for that time, changing the highlighted line to the following fixes the issue and makes logical sense:

`if (lastHourlyStats != null)
                    _lastHourStatCounters[lastDateTime.Minute] = lastHourlyStats.MinuteStats[lastDateTime.Minute];`

**Comment by Matthew-Bonner** [comment]
@ShreyasZare why are you over complicating the code by creating your own custom file formats, using `Encoding.ASCII.GetString(bR.ReadBytes(2)) != "HS"` makes it difficult to work with your code, are you attempting to make the software more performant by using your own custom file format?

**Comment by ShreyasZare** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/7858744/49692340-26b2af00-fb50-11e8-8641-41f533bc6d28.png)

Thanks for the feedback. You have correctly pointed the bug in there which gets fixed with a null check:
`if ((lastHourlyStats == null) || (lastDateTime.Hour != lastHourlyStatsDateTime.Hour))`

This will get released soon once the testing gets complete.

The file formats you mentioned are binary serialization for the objects. Its designed to serialize/de-serialize the objects easily with format detection to prevent loading invalid data and versioning option to allow extending them later. Specifically for objects holding stats which are required to be loaded quickly, these binary formats work fast. The binary format is similar to Type Length Value (TLV) formats used by many standards like ANS.1 encoding.

**Comment by Matthew-Bonner** [comment]
The null check was just a workaround, and a poor one at that, the reason I deleted the comment was that I feel refactoring this code will provide a better outcome.

**Comment by ShreyasZare** [comment]
Current implementation is always a working model for the feature and when newer ideas are thought of then there is refactoring effort. So refactoring entire design for null check is not feasible. It would only make sense when more functionality needs to be added.

**Comment by ShreyasZare** [comment]
Bug fixed in v2.1 release. Please update the software.
