### ISSUE TITLE
Bug: flush cache isn't purging the cache

### ISSUE THREAD

**Issue by shawnkhall** [TechnitiumSoftware/DnsServer#150]
With 5.0 and 5.0.1 the `flush cache` feature no longer appears to actually purge the blocklist cache. The logs indicate that the `flush cache` button does cause it to download the blocklists again, but queries for values that no longer appear in the blocklists are still returning the blocklist as the reason for being blocked.

**Comment by shawnkhall** [comment]
Workaround: I was able to get this to work by modifying the list of blocklists then saving the settings again. Simply saving the settings did *not* work.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. With the v5.0 release, the options to flush Allowed zone and Blocked zone has been removed since it was added for testing purposes and could cause issues for some users since there was no way to reload Allowed zone and the Blocked zone could be renewed only if the url in settings were modified.

The flush cache option is still available and will flush only the DNS cache while the Allowed and Blocked zones wont be affected. This option is useful in certain scenarios and since the cache gets populated automatically, it wont cause any issues.

The flush cache option wont trigger the block list download. It could be just that the download was triggered by the timers independently.

Another major change is that the Blocked zone which was previously used to store the domain names from the block list is no longer being used in that manner. Block lists now have its own internal zone which is not a tree data structure and thus not browse able like the Blocked zones. This was done to optimize memory usage since the tree data structure would take a lot of memory and thus a simple hash map based internal block list zone was implemented. So, apart from the block list zone not being browse able or viewable, the functionality remains same.

**Comment by ShreyasZare** [comment]
> Workaround: I was able to get this to work by modifying the list of blocklists then saving the settings again. Simply saving the settings did _not_ work.

Yes, its actually a feature to prevent downloading block lists frequently if no change was made to them.
