### ISSUE TITLE
DNS resolution failed

### ISSUE THREAD

**Issue by rikyotei** [TechnitiumSoftware/DnsServer#163]
Hi,

Can you please take look why the DNS server works slowly or passing failure errors?

![图片](https://user-images.githubusercontent.com/16711623/89979846-3da19100-dca3-11ea-86a3-020fd0b293c8.png)

logs attached
[2020-08-12.log](https://github.com/TechnitiumSoftware/DnsServer/files/5060838/2020-08-12.log)
[2020-08-11.log](https://github.com/TechnitiumSoftware/DnsServer/files/5060839/2020-08-11.log)

**Comment by ShreyasZare** [comment]
Thanks for the post. I saw the log files and its mostly request time out errors which means that the forwarders are not responding or not responding quick enough. It could be due to intermittent network issues.

The Name Errors are just some applications querying for non existent domain names. Its nothing to worry about.

**Comment by rikyotei** [comment]
How I can fix the issures? My another DNS server(Microsoft) is works fine under same network, do I have to change any settings?

**Comment by ShreyasZare** [comment]
Once the DNS server has resolved the domain name then it will stop responding as ServerFail and serve-stale cache feature will prevent that from occurring for the same domain name. You can test this using DNS Client tool by querying for any domain name in the logs that had errors.

Thus this issue usually gets fixed on it own due to multiple queries triggers retries on the DNS server and once the data is in cache, the issue wont occur.

**Comment by rikyotei** [comment]
Thank you for your reply, I'm going to test and continue to observe.
