### ISSUE TITLE
Improve installation process on Windows

### ISSUE THREAD

**Issue by Globulopolis** [TechnitiumSoftware/DnsServer#167]
Hi!
If we use windows installer we need some improvements in installation process.
- [ ] Change path in "Where to install" dialog from default, to path where server installed. Only if we do upgrade.
- [ ] Shutdown service while install, instead doing it by hands. See screenshot below.
![Clipboard01](https://user-images.githubusercontent.com/740757/91745788-35fb4b00-ebc4-11ea-8a77-dae0b2efcd1b.jpg)

**Comment by ShreyasZare** [comment]
Thanks for the post. The installer that is being used lacks a lot of things which includes the couple of things that you have mentioned. This issue can be thus only resolved by finding out another installer that supports installing .NET services and is also free.

**Comment by Cossey** [comment]
InnoSetup can do all of that plus the download and install of .NET on the fly.

Its scripting (pascal) offers a lot of power too!

**Comment by ShreyasZare** [comment]
> 
> 
> InnoSetup can do all of that plus the download and install of .NET on the fly.
> 
> Its scripting (pascal) offers a lot of power too!

Thanks for the suggestion. I am looking for something that would support installing .NET 5 as all code will eventually move to run on .NET 5.

**Comment by Cossey** [comment]
Okay, can you assign this issue to me? 

Ill go ahead and do up a proof of concept installer ￼that does every thing you need it to.

**Comment by Matthew-Bonner** [comment]
The trend these days is to move towards writing your own installer in C#, because it does everything an installer can do, but when the installer grows in complication, it is easier to manage.

**Comment by ShreyasZare** [comment]
> 
> 
> The trend these days is to move towards writing your own installer in C#, because it does everything an installer can do, but when the installer grows in complication, it is easier to manage.

With installer the maintenance and testing required takes too much time especially since things keep changing every couple of years.

**Comment by ShreyasZare** [comment]
> Okay, can you assign this issue to me?
> 
> Ill go ahead and do up a proof of concept installer ￼that does every thing you need it to.

There are 2 aspects for this. 
- To update the DnsService project to run on .NET 5. This should run as a proper Windows Service. Creating service with .NET 5 is easy but you need to installer to install the windows service. Previously with .NET Framework, the app itself had code for the service installer.
- To create installer to install the DnsService project. This includes to install the .NET 5 dependency is missing and install the windows service. It should also update any previously installed windows service.

If you can get this working then it will be great! I would suggest that you wait for a day while the next update is released. Also, use the develop branch for PR so that I can do some more testing before the next release.

**Comment by Cossey** [comment]
@ShreyasZare okay, I have spent some time today working on this.

You have mentioned .NET 5 above. The Windows version of the DNS Server is supplied with the *System Tray App* still runs on .NET Framework 4.8. I am assuming that the Tray app will still be available when you move these to .NET 5 and it will still be using WinForms? If you can keep the Mutex you've created there in the tray app when you shift it over, that would be helpful for the installer.

When uninstalling, should the uninstaller remove the config files under `DNS Server\config`, prompt to remove or leave them? If prompting to remove, what should the uninstaller do by default in silent mode?

I have tested the .NET 4.8/5 dependency install on the fly from the installer, looks to be working well. Just need to give it some additional testing in some other environments, but it is progressing well.

Looking at this conversation here: https://github.com/dotnet/runtime/issues/29643 it seems like people are using sc create now to install windows services, so I am currently working on this and testing how it performs with the develop branch.

**Comment by ShreyasZare** [comment]
@Cossey thanks for the details. 

The system tray app will need to be ported to .NET 5 too. I think it should work without any change if you just put the code in a new .NET 5 Win Forms app. May be some additional nuget package will be required if any thing is missing.

For uninstalling, I think keeping the config folder as-is by default should be better just in case someone tries to reinstall the DNS server. Removing the config files should be explicitly asked.

I too have seen people using sc to create service. I feel a bit issue with this since handling case when sc fails could be difficult. May be a check in the registry to see if the relevant key exists can be done to make confirm that sc installed the service should be good.

**Comment by Cossey** [comment]
I’ve just finished some additional improvements. 

Firstly I sucessfully ported the tray app and the service over to .NET 5. Quite straightforward. I removed the service installer code in the service since that wasn’t supported. It builds and runs but probably needs some more intensive testing. 

Installing .NET 5 on the fly seems to work very reliably. Its written to detect dotnet 5.0.1 desktop and install it if its not present. Would you like it to install 5.0.1 only if it detects no version 5.0.0 or would you like it to install 5.0.1 even if 5.0.0 is installed?

I found and modified a code module for Inno Setup that will actually install the service using WinAPI and we actually get Error Codes back using the `GetLastError()` WinAPI. It seems to work quite well. 

On another note: I’ve also built a powershell script to create a chocolately package for this software (I personally use chocolately to install all my software on my PC and i maintain 7 packages on the community repo). I did this in the hope you would consider submitting this to the chocolately community repository in addition to downloads from your site.

Would you like me to PR just the installer code or should I PR the .NET 5 ports as well?

**Comment by ShreyasZare** [comment]
Awesome! Do check for the .NET 5 version. If lower version is installed then the bundled version can be installed. If there is v5.0.2 released later then no need to install v5.0.1. But, if v6.0.0 is released then we need to have v5.0.x since with .NET core the major versions were not compatible.

Another question is where will the setup download the .NET 5 installer? It has to be official MS link since hosting the file will be costly.

Installing via win32api is really good one to have so that we can ensure that the service is installed correctly.

I have not explored chocolately. Will check it out once.

PR the installer as well as the ports for system tray app and the windows service.

**Comment by Cossey** [comment]
PR #217 contains these changes. It'll be in draft for a day or two whilst I go over installer code and add some additional comments and make a few small tweaks for the chocolatey package.

**Comment by Cossey** [comment]
Okay, the PR is out of draft and is ready please let me know if you have further questions not covered in the PR.

**Comment by ShreyasZare** [comment]
Awesome! Will check and let you know.

**Comment by ShreyasZare** [comment]
New update v6.0 is now available for download with new windows setup made using Inno Setup thanks to @Cossey.
