### ISSUE TITLE
[REQUEST] Version Information | Install Documentation

### ISSUE THREAD

**Issue by kopacko** [TechnitiumSoftware/DnsServer#184]
Two requests:
1] Can you add version information to the zip files?
2] Can you add a simple install text file to specify which files to run in which order?
    - DnsServiceSetup.msi (first?)
    - setup.exe (second?)

Thanks

**Comment by ShreyasZare** [comment]
Thanks for the feedback. 

There is no version info in the name of the downloaded files to make the install paths to always point to the latest version.

In the windows setup, you just need to run the "setup.exe" file since it will install missing .NET framework. Running the msi file will also work if you already have the required .NET framework installed. The setup installer is planned to be replaced with something better so this issue should get fixed with it.

**Comment by ShreyasZare** [comment]
New update v6.0 is now available for download with a new windows setup installer that has a single exe file.
