### ISSUE TITLE
Lot of unwanted connections

### ISSUE THREAD

**Issue by PEPERSO** [TechnitiumSoftware/DnsServer#186]
I've found, using technitium logs, that everytime I go to http://localhost:5380, there are connections to these domains (in the following order):

- go.technitium.com
- twitter.com
- technitium.com
- dnsclient.net (I guess this one is necessary for the DNS Client tool page ?)
- blog.technitium.com
- tools.ietf.org
- github.com

And then, once logged in:

- go.technitium.com
- download.technitium.com (I guess those two are auto check for update, would it be possible to choose if I want an auto check or check by myself ?

I'm quite sure these connections are due to technitium, because I followed the following steps: 

1. Deleted the log file from the http API
2. Started a browser
3. Download the log again with the api (almost no change)
4. Then going to http://localhost:5380 from the browser
5. Download the log with API
6. Log in from browser
7. Download again

All my block lists are on my computer, no need to go through the internet to update them. As a DNS server and logger, Technitium is critical to my privacy, and I would like to know what are all these connections for, especially the twitter one, which I don't really understand...

Anyway thanks for Technitium, I hope it will keep growing !

**Comment by ShreyasZare** [comment]
Thanks for the query.

The DNS server makes a https connection once each time you login via the
web console to check for update. There is no automatic update, instead this
is just a notification that is shown in the UI when there is an update
available. The update notification uses go.technitium.com and
download.technitium.com domain names.

The rest of the domain name that you see in the DNS logs are due to the web
browser doing dns prefetch. This is a web browser feature which resolves
all domain name for all the URLs it finds on the web page to be ready for
the user to click. This is done for performance reasons. There are URLs in
the footer and in the About tab which the browser sees and does dns
prefetch. There is no actual connection being made by the web browser.

Shreyas Zare
Technitium

**Comment by PEPERSO** [comment]
As always, thanks for the quick and clear answer !

For the update check, I know it's not an automatic update and just a check to eventually display a notification, but I would like to be able to choose if this check is done automatically or not. 
Alright for the other connections, I'll see how to disable dns prefetching on my browser !

**Comment by ShreyasZare** [comment]
The automatic update check is done on the client side javascript. Since, the settings are not directly accessible to it, I need to think about such option.
