### ISSUE TITLE
Stop using the deprecated BincodingDecoder and use json instead for config files

### ISSUE THREAD

**Issue by Matthew-Bonner** [TechnitiumSoftware/DnsServer#19]
I see code like this in quite a few places:

`BincodingDecoder decoder = new BincodingDecoder(s, "DS");`

And I don't understand why you've done this, even the updater uses a strange encoding method, so firstly, what is the point of this?

Secondly, it would make it much easier for developers if you just stuck with json configuration files.

I'm half tempted to fork what you've done and fix all these niggly issues under a separate project but I don't want to as I think we could produce something better together as you clearly know a lot about DNS.

**Comment by ShreyasZare** [comment]
The `BincodingDecoder` class is already marked deprecated and exists only for compatibility for users who will upgrade from earlier version of DNS Server to latest.

BincodingDecoder binary serialization was intended to be TLV formatted data similar to ASN.1 with support for advance data types. But, eventually it got too complex and cumbersome to use and lost its purpose of making it easier to use thus, got deprecated in favor of using simple BinaryReader and BinaryWriter object data serialization. 

I strongly prefer using binary formats for data serialization and do not prefer json formats since:
- Binary formats are incredibly easy to serialize and de-serialize.
- They perform faster compared to text based human readable formats. These data sets are not supposed to be read by humans and the software using them must specify options to edit them.
- Text formats makes it difficult to control data types and require multiple sanitation checks for each fields.
- Json format is not natively supported and thus require separate library to be included. This DNS server project does include Newtonsoft.Json library which is necessary to support Google's DNS-over-HTTPS protocol version which mandates Json format instead of DNS wire format.

**Comment by Matthew-Bonner** [comment]
I think you make a good case for using the binary format, but there is no definition for the data structure and no information published on what is contained within each file, nor are we able to simply view the file to try and understand it, so if people want to contribute they have to look at the code, and that can take some time. Given this, I'll spend some time looking at the code to understand it better. Thanks for your clarification.
