### ISSUE TITLE
Can't delete TXT with quotation marks

### ISSUE THREAD

**Issue by Marook332** [TechnitiumSoftware/DnsServer#196]
Hello,

just updated to v5.4 and realised, i had a bad SPF record on one of my hosted zones.

![image](https://user-images.githubusercontent.com/13482386/100025088-6419b100-2de8-11eb-81ed-e380b5ad6305.png)

If i try to delete this entry, i just get an error message
![image](https://user-images.githubusercontent.com/13482386/100025154-801d5280-2de8-11eb-871e-0dfb1025d9ad.png)

Then i tried to delete this record using an API request like:
`curl 'http://my.host.name:5380/api/deleteRecord?token=tokenxxx&domain=domain.tld&type=TXT&value=""v=spf1 mx -all""'`

No way to delete this record. I figured out, when i am creating a TXT record with no spaces between the quotation marks, i am able to delete the record. If the record contains a space, i'll get this while im using the API:
`<h1>Bad Request (Invalid request line (version).)</h1>`

**Comment by ShreyasZare** [comment]
Thanks for the feedback. I am able to reproduce this issue. Its caused due to the double quotes not getting encoded in the html correctly. Will fix this issue in next update.

As you have tried with the API, you are on the right path to manually delete the record. The only thing you need to do is url encode the value part `"v=spf1 mx -all"`. The url encoding will give you `%22v%3Dspf1%20mx%20-all%22` which you can then use in the API call to get the record deleted.

Another thing is that you don't need to add double quoted for TXT record since quotes syntax is only required if you are editing bind zone files in text editor.

**Comment by Marook332** [comment]
You're welcome. I tried the deletion with encoded spaces (`%20`) and it worked. 👍 

> Another thing is that you don't need to add double quoted for TXT record since quotes syntax is only required if you are editing bind zone files in text editor.

I know it was a copy&paste fail :) Thanks and keep up the good work!

**Comment by ShreyasZare** [comment]
Good to know it worked.

**Comment by ShreyasZare** [comment]
DNS server version 5.6 fixes this issue.

**Comment by hellmind** [comment]
Isn't a way to delete that record without specifying  target, value, a, or whatever it needs ?

**Comment by ShreyasZare** [comment]
> Isn't a way to delete that record without specifying target, value, a, or whatever it needs ?

Thanks for asking. The records in the zone do not have a unique identifier so the entire record details are required to delete it.

**Comment by hellmind** [comment]
But you can 'getrecords' using only the domain.
How is that different?

**Comment by ShreyasZare** [comment]
> But you can 'getrecords' using only the domain. How is that different?

GetRecords will give you a list of all records for that name. This includes all type of records. When you want to delete, you need to delete a specific record so you need to provide all the details of the record to match it for deletion.
