### ISSUE TITLE
Need a web page for DNS-over-HTTPS service

### ISSUE THREAD

**Issue by gexqin** [TechnitiumSoftware/DnsServer#198]
Dear Developer
This is a feature request.  (2  features )
When I use Enable DNS-over-HTTPS (TCP Port 80 & 443) function , It works good but when I use web browser access it. It will show 404 Not Found.  I know I should use dns-query but I still think it should have a page tell the user it is a DNS server when user access it.  The second also about DNS-over-HTTPS. Since DNS-over-HTTPS open TCP Port 80 & 443 I don`t know why need 80 for https? could you make the web access from http jump to https  automatically?

**Comment by ShreyasZare** [comment]
Thanks for the request.

Its a good idea to add a simple page with some info regarding how to configure DoH service. This should help especially when Windows 10 update in 2021 will include support to configure DoH and a page that includes some directions would be useful.

The DoH service runs HTTP on port 80 and HTTPS on port 443. Port 80 is required for automatically renewing Let's Encrypt TLS certificate that is being used and thus the plain HTTP access exists. This plain HTTP over port 80 cannot be used to configure DoH since its not secure and the server wont respond to queries without HTTPS. 

Redirecting HTTP to HTTPS is totally not desirable in this case since it would look ok at first but then if someone configures HTTP URL then for each DoH request there will be an additional 302 HTTP redirect which will severely hit performance and most importantly it will make the DoH service severely insecure. Its best that things break when HTTP is used so that the user corrects the URL to use HTTPS.

**Comment by Globulopolis** [comment]
> but I still think it should have a page tell the user it is a DNS server when user access it.

How about if DOH server installed on the same server with Apache/nginx/etc web server?

**Comment by ShreyasZare** [comment]
> 
> 
> > but I still think it should have a page tell the user it is a DNS server when user access it.
> 
> How about if DOH server installed on the same server with Apache/nginx/etc web server?

The request is to help someone who probably is trying to learn while trying out DoH config. So it can be quite useful for newbies.

**Comment by ShreyasZare** [comment]
New version 6.3 is now available that now shows a page for the DoH url with basic instructions.

**Comment by gexqin** [comment]
Thanks it really good.
