### ISSUE TITLE
Cannot compile master : missing TechnitiumLibrary

### ISSUE THREAD

**Issue by tbremard** [TechnitiumSoftware/DnsServer#210]
I downloaded master branch and cannot compile locally due to missing dependency:

TechnitiumLibrary

![image](https://user-images.githubusercontent.com/36224228/102787858-03a77080-43a2-11eb-9874-053ac208c259.png)

**Comment by ShreyasZare** [comment]
Thanks for the post. You need to clone the TechnitiumLibrary repo in the same directory where you have cloned the DnsServer repo. Compile the library repo once in release mode and then compile the DNS server.

**Comment by tbremard** [comment]
Ok I get it : you must download a seperate repository available on your account/ build / then update the references.

what about publishing a nuget package ?

**Comment by tbremard** [comment]
I solved the TechnitiumLibrare, manage to execute the netcore, but I let you know there is a problem to build systray (not blocking to use the website)

![image](https://user-images.githubusercontent.com/36224228/102790478-c7760f00-43a5-11eb-86e5-441c60f55bc4.png)

**Comment by ShreyasZare** [comment]
The library is for internal use and the API keeps on changing as per new requirements so, it would be a bit difficult to maintain nuget package.

For the other error, it seems that you downloaded the source as a zip file instead of cloning. Do, web browsers do this thing and mark all files that you download and extract from zip to indicate it was downloaded from internet and when you try to execute them you get a warning. This can be cleared by just going to the file's properties and check the Unblock checkbox as shown below:

![image](https://user-images.githubusercontent.com/10008172/102857827-23e13900-444f-11eb-80aa-57f4443fc11a.png)

**Comment by tbremard** [comment]
thanks a lot !

Le mar. 22 déc. 2020 à 07:44, Shreyas Zare <notifications@github.com> a
écrit :
