### ISSUE TITLE
dns server does not work in freebsd 12 mono 5.20 environment

### ISSUE THREAD

**Issue by rlagmlah** [TechnitiumSoftware/DnsServer#213]
I upgraded to freebsd 12 and mono also upgraded to 5.20. Then, when I run technitium dns, it immediately stops and restarts, and no messages appear.

I know that freebsd is an os that is not well used compared to linux.
Also I know that Technitium dns does not officially support freebsd.
I also know that mono 5.20 is old version of mono.
So I also know that this problem may not be solved.

Are there any possible causes or solutions to the problem you are guessing?

**Comment by ShreyasZare** [comment]
Thanks for the query. The DNS server is moving towards running on .NET 5 in coming updates since .NET Framework is obsolete. So, it should be best if you can install .NET 5 on FreeBSD (the next release of the DNS server v5.6, releasing in a day's time, requires .NET 5 while the current version runs on .NET Core 3.1).

While there is no official support from Microsoft for FreeBSD, but you can find instructions and try to get it installed. I just found some instructions [here](https://github.com/jasonpugsley/installer/wiki/.NET-5.0-Preview-3-for-FreeBSD) but have not tried them.

**Comment by rlagmlah** [comment]
Previously, the .net installation had failed once. I will try again this time and close the issue if it succeeds. thanks.
