### ISSUE TITLE
Feature Request: Don't leave the admin site if you press the back button on the browser.

### ISSUE THREAD

**Issue by JDA88** [TechnitiumSoftware/DnsServer#218]
Hi,

Currently if you press the back-button om the browser you leave the sit and have to re-authenticate. No matter how many pages you saw on the site.
Can you implement a feature so that the back / next button allows to navigate on the admin site?

**Comment by ShreyasZare** [comment]
Thanks for the feedback. This is since when you navigate in the web console, the page never refreshes. All content is dynamically loaded since this is a single page app. There are some techniques to use bookmarks that can be used to navigate though. I will take a look with this technique and see how to get it implemented. I cant commit timeline for this though since this will be taken up when I am working exclusively on UI changes.

**Comment by JDA88** [comment]
Sure, that's not a deal breaker, just a QoL improvement for peoples (like me) used to navigate forward / backward with mouses button 👍
