### ISSUE TITLE
Feature Request: Give a way to know from which block list come the last x blocked domain.

### ISSUE THREAD

**Issue by JDA88** [TechnitiumSoftware/DnsServer#219]
Hi, 

Currently if you can’t browse to a website it’s a real pain to find from which block list comes the problem, most of the times it comes from a redirection on a CDN URL. Even allowing the website domain usually doesn’t fix the issue.

It would be super useful to have a place in the admin interface to:
- See the last x blocked domains in the last y minutes (could be a toggle if that impact performance)
- Know from what list(s) come the blocked zone (would be click to action)

**Comment by ShreyasZare** [comment]
Thanks for the post. Fixing a broken website due to DNS blocking is quite difficult for most people. This involves using developer tools to see console errors and trial and error to see which domain when allowed fixes the website. I dont know how to make it easier for most people since a lot of stuff on web pages is dynamic.

The dashboard already shows the top 10 blocked domain and top 1000 blocked domains for last hour, last day, etc. 

Right now you can find out which block list has the domain blocked by querying the domain in the DNS Client with type TXT. Adding this details by default on dashboard will not look clean though.

**Comment by JDA88** [comment]
I did not know about the TXT query trick! It will help for sure, thanks.

I have no idea how you store your stats in memory (to compute last hour, last day, etc.) but is it unrealistic to have a page to query the "last hour" data subset?
If we had a way to list the domain blocked for a host in the last 5-10 min, and not limited to the top 10 that would already be a huge improvement.

The last hours stats are good to spot massive problems, but not enough for a single user that have problem on a particular exotic site. Especially considering that the top 10 il mostly populated by the classic Microsoft / Google / FB endpoints.

**Comment by ShreyasZare** [comment]
The stats data is stored in data structures as crunched data and is not relational i.e. no relation between various stats. Its not a database so cannot query it with different conditions except for data/time. The stats are available for each minute.

I think there can be a custom option added to select the date/time slice that you want to display apart from the last hour, last day etc options. This will fit in with your requirements and also allow loading data for custom data/time duration for all available stats data.

**Comment by JDA88** [comment]
Anything that can help with debuging would be great!

**Comment by ShreyasZare** [comment]
New update v6.0 is now available for download that adds option to select custom range on dashboard.
