### ISSUE TITLE
Log to file using NLog

### ISSUE THREAD

**Issue by Matthew-Bonner** [TechnitiumSoftware/DnsServer#22]
At the moment, logging takes place on the same thread as the server itself, which means that the DNS server is constantly being blocked by logs that are being written to file. I think using NLog rather than your own logging solution will serve to provide better performance.

**Comment by ShreyasZare** [comment]
Currently the DNS Server uses ThreadPool thread per request and writes logs on the same request thread after the response is sent. Thus there is no delay in sending response since response is already written to wire. There are separate multiple threads that read the response or accept TCP connections and the request is processed by separate threads that come from ThreadPool.
