### ISSUE TITLE
Feature Req: Custom Hostname for DHCP Server

### ISSUE THREAD

**Issue by Hemsby** [TechnitiumSoftware/DnsServer#223]
Im using the DHCP Part of this software.
I have a number of Amazon devices that I want to change the hostname for rather than using alias in the DNS as they are all amazon-xxxxx for example.  Also my TV does not use hostname so would like to set one without reserving an IP and again having to manually create an A Record in the DNS server part.

**Comment by ShreyasZare** [comment]
Thanks for the request. I can implement something that will allow you to override the hostname of a device. So devices that don't provide any hostname will get the one you set using that feature. You can use that to set a name of your choice for your amazon devices so that you wont need to add a CNAME record for it in the DNS zone separately. 

But, that will require you to add the device's MAC address to the reserved lease. The DHCP server relies on the reserved lease option to identify the device in question using its MAC address so without setting a reserved lease the server cannot identify your device.

**Comment by Hemsby** [comment]
Thanks!

**Comment by ShreyasZare** [comment]
New update v6.0 is now available for download that allows overriding client's host name.
