### ISSUE TITLE
Revoke DHCP Lease

### ISSUE THREAD

**Issue by debasish-mohanty** [TechnitiumSoftware/DnsServer#225]
Would like to have the option to revoke DHCP lease from the Server side.

**Comment by ShreyasZare** [comment]
Thanks for the request. The option to delete lease is deliberately not available. The reason is that if you delete a lease, the device with the lease does not know it and will keep using that same IP address till the lease expires or the device reboots. In that span, the DHCP server may lease that same IP address to another device and then you will have two devices on the network that do not work and you don't know why.

The best way to manage DHCP server is to use an appropriate lease time that is not to long. Like if you have a lease of 1 day then its guaranteed that any device that leaves the network will have its lease deleted automatically within a day.

If you wish to change the assigned IP address for a device, you can do that using the reserved lease option where you specify a new IP address that the device must use. Once the device reboots or tries to renew the lease, it will get the new IP address and the old lease wont be renewed.
