### ISSUE TITLE
How to Integrate with Microsoft AD Integrated Zones ?

### ISSUE THREAD

**Issue by debasish-mohanty** [TechnitiumSoftware/DnsServer#226]
Any recommendation on how to integrate with active directory integrated Domain Controller rather than using Windows Domain control integrated DNS service. Do not want to have split DNS services.

**Comment by ShreyasZare** [comment]
Thanks for the question. Do you mean to run both MS DNS Server and Technitium DNS Server together for the zones hosted on MS DNS server? You can add a secondary zone on Technitium DNS Server so that both the servers respond to the zone. Or you can use conditional forwarder zone which will work similarly but will require that your primary zone remains available all the time.

If this is not the case you are looking at then let me know a bit more details on your scenario so that I can give some suggestions.
