### ISSUE TITLE
DHCP: Windows unable to acquire DHCP lease from Technitium

### ISSUE THREAD

**Issue by LordMike** [TechnitiumSoftware/DnsServer#228]
This is odd. I've just set up a Raspberry Pi 4 w/ Technitium to be my new dedicated DNS / DHCP server, and I was excited to start doing DHCP with it (been running in docker so far).

My iPhone, laptop and Windows 10 Pro desktop are all unable to get a lease from the server. The server logs that it is offering (the same) addresses over and over - to no avail. I've made a packet capture.

The capture covers my desktop (Win10), during the course of a `ipconfig /renew "vEthernet (LAN)"` command which renews just the one interface. 

I'm seeing:

* DHCP Discover (Client -> Broadcast)
* DHCP Offer (Server -> Broadcast)
* DHCP Request (Client -> Broadcast)
* DHCP Ack (Server -> Broadcast)
* DHCP Request (Client -> Old DHCP server) <-- this should not happen

In this case, the IP's are:

* 192.168.1.1 - My router / old DHCP
* 192.168.1.2 - New technitium Raspberry Pi
* 192.168.1.100 - my desired IP for desktop, as handed out before

The command I run on Windows, is: `ipconfig /renew "vEthernet (LAN)"`, and it outputs:

> An error occurred while renewing interface vEthernet (LAN) : unable to contact your DHCP server. Request has timed out.

[Technitum-DHCP.zip](https://github.com/TechnitiumSoftware/DnsServer/files/5929126/Technitum-DHCP.zip)

In the event log (Microsoft-Windows-Dhcp-Client), I can see the following:

> Your computer was not able to renew its address from the network (from the DHCP Server) for the Network Card with network address 0x2C4D54CF135D.  The following error occurred: 0x79. Your computer will continue to try and obtain an address on its own from the network address (DHCP) server.

Googling says this is a client issue, but I'm seeing this on multiple devices (incl. iPhone). :|

**Comment by LordMike** [comment]
I was able to enable more logging in that log, and found events indicating an Ack timeout.. I find this strange as all packets I see are ~10ms apart.. :|

**Comment by ShreyasZare** [comment]
Thanks for the feedback. I checked the pcap file and there are 2 transactions in there:
- Packets 1, 2, 3 and 8 are probably from your desktop PC (ASUS). The device already has an IP (192.168.1.100) and is trying to renew the lease from the old DHCP server (192.168.1.1). Its not getting any response since the old server is down now but its still trying to renew the IP.
- Packets 4, 5, 6 and 7 are from another device (Ubiquiti) which is requesting 192.168.1.240 IP address allocation and it got that IP address leased from the DHCP on your raspberry pi. This transaction looks complete and you should see the lease on the web console.

So, on your desktop, what you can do is release the IP address first using **ipconfig /release** and they try to renew back using **ipconfig /renew**. This should fix the issue. For other devices try to disconnect the network or try rebooting them and see if they are getting new leases.

**Comment by LordMike** [comment]
Huh ... I was convinced all packets were related to my own desktop - but you're right .. it's ofc. broadcasts.. :|

Ok - so the issue isn't a network one .. it's windows being stuck with the previous DHCP server. My lease time is 7200 seconds, so I guess if I just wait, then all devices should be on the new DHCP server.. :O

I wonder why my iPhone decided there was no internet.

**Comment by ShreyasZare** [comment]
> 
> 
> Huh ... I was convinced all packets were related to my own desktop - but you're right .. it's ofc. broadcasts.. :|
> 
> Ok - so the issue isn't a network one .. it's windows being stuck with the previous DHCP server. My lease time is 7200 seconds, so I guess if I just wait, then all devices should be on the new DHCP server.. :O
> 
> I wonder why my iPhone decided there was no internet.

Do try rebooting the devices, on reboot they should try to get new lease if old lease is not getting renewed.

**Comment by LordMike** [comment]
Cool. I'll give it a whirl. It probably works fine then.. :)

Thanks!

**Comment by LordMike** [comment]
(do you accept github sponsors or patreon?)

**Comment by LordMike** [comment]
Can confirm. Works fine after my old leases expired.
