### ISSUE TITLE
Technitium in Master/Slave setup

### ISSUE THREAD

**Issue by izghitu** [TechnitiumSoftware/DnsServer#236]
Hi,

Currently I have 2 Technitium  DNS servers and I am manually mirroring all the records for the domains that I have in them.

I was wondering if it's possible to configure Technitium DNS server in a Master/slave setup where the master will automatically push new domains to the slave and any changes as well.

I searched on google and through the docs but I cold not find any information regarding this.

Please let me know.
Thanks in advance.

**Comment by ShreyasZare** [comment]
Thanks for asking. There is a clustering feature planned to have two or more DNS servers in cluster. This feature should be available in a couple of updates.

For now, I would recommend that you setup primary zones on one server and secondary zones on the other server for all your domain names so that any change in the records are automatically synced. You will have to create secondary zone for all domain names though but it would be a one time thing. Let me know if you need any help with setting up secondary zones.

**Comment by izghitu** [comment]
@ShreyasZare thanks for the recommendation, can't wait for the cluster feature!
