### ISSUE TITLE
Is it possible to resolve official domain names on the Internet

### ISSUE THREAD

**Issue by qcjxberin** [TechnitiumSoftware/DnsServer#237]
I currently have a domain name that can be accessed on the Internet. Can I use this system to resolve the domain name and officially use it on the Internet instead of only testing it locally. If so, how can I do it. In addition, is it possible to support the resolution of multiple top-level domain names?

**Comment by ShreyasZare** [comment]
Thanks for asking. If you meant to know if you can use the DNS server for hosting live domain names then yes its possible to do that. However, please do this only if you know how to manage it correctly since it could be a bit difficult to manage your own authoritative DNS server.

For this, you will need a server with static IP address. Install the DNS server on that server and configure your domain name. Lets say for example that the domain name is example.com. You need to now correctly configure the NS records at your domain name registrar so that the DNS requests are directed to your new DNS server running on the static IP address. To do that, login to the registrar's web panel where you have the domain name. Find the child name servers option and configure it for "ns1.example.com" with the static IP address of your server. Once you have done this, find the name servers option for the domain name and delete the existing name servers and enter "ns1.example.com" name server that you had configured as child name server. 

Now, on the DNS server, in the example.com zone, make sure that you have a NS record for "ns1.example.com" with the static IP address.

Once all these settings are done, your DNS server should start receiving queries for your domain name. Note that it may take few hours for the name server records at the TLD to reflect the changes. You can use the dnsclient.net website to check if the domain name is recursively resolving correctly.

**Comment by qcjxberin** [comment]
Is there a cluster version or a shared database version? In this way, multiple nodes can be deployed to realize the use of dns server. We currently have this requirement and want to manage our own domain name.

**Comment by ShreyasZare** [comment]
The clustering feature is planned and should be available in a couple of releases. Clustering will make it easy to configure all the nodes in one go. But, for now, you have have primary zone on one node and create secondary zones on the other nodes. The secondary nodes would get synced automatically for any changes to the records in the primary zone.

**Comment by qcjxberin** [comment]
Can you provide a specific graphic configuration tutorial? Because it is the first time to use, I am not sure if I can understand it correctly

**Comment by ShreyasZare** [comment]
I don't have any tutorial/documentation for this now. Its quite straight forward to configure secondary zone. 

Firstly, all your name servers should have child domain names with their static IP addresses registered on the domain name and configure the domain name's name servers with all the child name servers you create.

Now make sure that you have NS record for the domain name of the secondary server added in the primary zone. Since you are using child name server, put the IP address of the secondary server as the glue address for the NS records.

For adding secondary zone for a live domain name, you can just specify the domain name and add the secondary zone. The secondary zone will sync automatically in few seconds.

**Comment by qcjxberin** [comment]
Then I will try it step by step, and I will ask if there is a problem

**Comment by ShreyasZare** [comment]
Just one thing I mentioned incorrectly: instead of putting the IP address as glue in NS record, create A record for domain in NS record.

**Comment by qcjxberin** [comment]
OK
