### ISSUE TITLE
Dynamic Dhcp I can not receive IP 

### ISSUE THREAD

**Issue by Haimirick** [TechnitiumSoftware/DnsServer#243]
Hi, I have just installed Technitium.
I set my "power_qms.com" Zone.
I added my record A with :+1: 

www | A | 3600 | 192.168.1.2

where 192.168.1.2 it is the Win 7 Machine IP where Technitium Service is running with static IP  and where gatway it is my Router with IP 192.168.1.1 with DCHP disabled where subnet mask it is 255.255.255.0, where my DNS it is itself (192.168.1.2) and second dns it is  my router(192.168.1.1)

Now problem is  I can not receive and Ip on other Win7 Machine on the some Workgroup
At the moment DHCP have following scope:

Name | Scope Range/Subnet Mask | Network/Broadcast | Interface |  

Default DHCP | 192.168.1.1 - 192.168.1.254 255.255.255.0 | 192.168.1.0 192.168.1.255 | 192.168.1.2

DNS TTL : 900 seconds
Domain Name :  the same of Win7 Machine (it is a workgroup)
Router Address: 192.168.1.1

Exclusions Starting Address | Ending Address |  
                192.168.1.1 | 192.168.1.10   

I have no idea, where I wrong, thanks.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Your config looks good overall. It could be just that the Windows firewall is blocking the incoming UDP port 67 that DHCP server uses. Try adding a inbound firewall rule for UDP port 67 and see if that works.

If its still not working then do check the logs to see if there are any errors being reported. You can also install Wireshark and try to capture the traffic on the network when your other computers try to get IP address from the DHCP server. Send over the captured pcap file so that I can get a complete picture of the issue.

Another thing that I would recommend is to not use your router's DNS as secondary DNS in your DHCP settings. This is since your router will not resolve the local zone that you have created on the DNS server causing arbitrary failure in local name resolutions on the computers in your network.
