### ISSUE TITLE
[Feature request]  DHCP lease release 

### ISSUE THREAD

**Issue by exilewolf** [TechnitiumSoftware/DnsServer#246]
Any chance of a DHCP lease release button on the leases page or way to kill current leases some how ?

**Comment by ShreyasZare** [comment]
Thanks for the request. The option has deliberately not been provided since if you delete a lease, the device with the lease does not know that and will keep using the leased IP address. So, the DHCP server can in such case allocate the same IP address to another device and then both the devices wont be able to access the network. Fixing such issues would not be possible for many users since it will be quite hard to debug such things.

The best approach is to set the lease expiry to lower value and let the lease expire when its not being used if the device exits the network.

**Comment by exilewolf** [comment]
Thanks for the quick response! Yeah you are of course correct the end client would not know if you have released the IP or not, but that is not an issue really for the reason I requested this feature.

The reason why this would be useful (for me at least) is with DHCP reservations. I use them a lot..  Since the DHCP server requires the IP you use for a reservation to be in the active scope this creates an issue because the IP's keep getting assigned out before I can create a reservation. 

Once I assign the IP to a reservation, The server will still keep giving out that IP to the first registered requested it.. Not the reservation... ? Rebooting the server will not resolve this issue and the only way I can see around this is as you said.. Setting the expiry to lower.. but am I going to need to do this ever time I need to set a reservation and then have to set it back?  That could be some hassle if I have the expiry set to something longer and then need to set reservation.. Then I would need to wait that length of time etc..

Anyways that was my intention behind this feature, Its not so much to just be able to get the client to get a new IP as such but more so for reservation configuration and when manually needed to force an IP change when you reconnect the end client.

**Comment by ShreyasZare** [comment]
Thanks for the details.

> 
> The reason why this would be useful (for me at least) is with DHCP reservations. I use them a lot.. Since the DHCP server requires the IP you use for a reservation to be in the active scope this creates an issue because the IP's keep getting assigned out before I can create a reservation.

My recommendation here is to use reservations only for devices which need to have a fixed IP address. For the rest all use cases, you can just configure a local domain for the DHCP scope and use the domain names. Using the domain names is actually more convenient and you don't have to worry about what the IP of the device is.

Now, when you really need to use reserved leases, make sure you keep a range of address excluded in the scope so that the server does not use those ranges for dynamic allocations. You can then assign your reserved lease addresses in that range. 

If you don't have exclusion range configured now, just do it and any device that has dynamic address inside the exclusion range will not get the same address lease when it tries to renew, connects back to the network, or when it reboots. So the range can be made available once you configure it.

> Once I assign the IP to a reservation, The server will still keep giving out that IP to the first registered requested it.. Not the reservation... ? Rebooting the server will not resolve this issue and the only way I can see around this is as you said.. Setting the expiry to lower.. but am I going to need to do this ever time I need to set a reservation and then have to set it back? That could be some hassle if I have the expiry set to something longer and then need to set reservation.. Then I would need to wait that length of time etc..

Ya, the device that holds the dynamic lease will keep getting renewed by design. Only way to make it stop is to either create a reserved lease for that device with another address or define an exclusion range over that address. Thus when the device tries to renew, connect back to network, or reboot, it will get a new address.

So, the solution could be to let things get dynamic addresses and use the domain name, or just create an exclusion range as a fence and keep reserved leases and dynamic leases separate.

**Comment by exilewolf** [comment]
no worries I will keep working with it and see how I go :) There are certainly work arounds and I missed the exclusion range so that is also helpful 👍
