### ISSUE TITLE
Old versions archive

### ISSUE THREAD

**Issue by Globulopolis** [TechnitiumSoftware/DnsServer#251]
Where I can download previous version of DNS Server?

**Comment by ShreyasZare** [comment]
Thanks for the request. There is no archive for now but I will try to make it available soon.

**Comment by josh0036** [comment]
I like Version 6.1 on my other servers.
It helps to detect unknown threats ( such as bots, trojan downloaders, and similar) crawling in my network.

I will use it as a secondary firewall in my networks without making any mess in the operating system or routers.
And bots and viruses can't detect this method. 

Since you need to manually "allow" or authorized every single request.

**Comment by ShreyasZare** [comment]
> 
> 
> I like Version 6.1 on my other servers.
> It helps to detect unknown threats ( such as bots, trojan downloaders, and similar) crawling in my network.
> 
> I will use it as a secondary firewall in my networks without making any mess in the operating system or routers.
> And bots and viruses can't detect this method.
> 
> Since you need to manually "allow" or authorized every single request.

That was a bug in v6.1. You can update to v6.2 and then add "*" to blocked zone and make the server block all domain names. Then you can add only the ones allowed to the Allowed zone.

**Comment by ShreyasZare** [comment]
Older versions archive is now available at: [https://download.technitium.com/dns/archive/](https://download.technitium.com/dns/archive/)
