### ISSUE TITLE
TLS Configuration - "The certificate data cannot be read with the provided password, the password may be incorrect."

### ISSUE THREAD

**Issue by Flagelmann** [TechnitiumSoftware/DnsServer#270]
Hello all,

I'm here to ask some support about TLS certificate configuration for the Technitium DNS Server.

I have configured it with no issues and it is working as expected (query, allowed an blocked zones, etc.  all ok).

Now I would like to enable TLS for both web management portal and for DNS-over-TLS, but, when I specify the path in the respective fields (I'm on a Linux system) of the .pfx file, with or without passowrd, it gives me always the following error:

"The certificate data cannot be read with the provided password, the password may be incorrect."

No matter if I give the pfx file different permissions or ownerships.....it just gives me always the same error, so I cannot configure it with the TLS certificate generated (and converted in PFX) by Lets' Encrypt.

Is there any way to fix this? Am I wrong on any of the steps?

I have tried following the steps on the Technitium blog, but all the images are broken so I cannot even check there if there's something wrong on my side.

Many thanks

**Comment by ShreyasZare** [comment]
Thanks for the post.

> 
> Now I would like to enable TLS for both web management portal and for DNS-over-TLS, but, when I specify the path in the respective fields (I'm on a Linux system) of the .pfx file, with or without passowrd, it gives me always the following error:
> 
> "The certificate data cannot be read with the provided password, the password may be incorrect."

Please share the openssl command that you used to generate the pfx file. Its possible that the format is incorrect or you provided some white space as password while generating it.

> No matter if I give the pfx file different permissions or ownerships.....it just gives me always the same error, so I cannot configure it with the TLS certificate generated (and converted in PFX) by Lets' Encrypt.

This is mostly not related to permission or ownership since the error description would have mentioned that.

> 
> I have tried following the steps on the Technitium blog, but all the images are broken so I cannot even check there if there's something wrong on my side.

On the blog post, `-passout pass:mypassword` is being used for the pkcs convert script. Do make sure if there was anything set there.

The images on [the blog](https://blog.technitium.com/2020/07/how-to-host-your-own-dns-over-https-and.html) are loading well here. Do reload with a hard refresh (Ctrl+F5) and see if that works.

> Many thanks

You're welcome.

**Comment by Flagelmann** [comment]
Hello,

ok, regarding the images on the Technitium blog it was an issue related to the blocked domains that I configured on the DNS server (too strict). :D 

Instead, regarding the main issue, I figured it out by removing the "-certfile" parameter in the openssl command, so using the following approach (using Let's Encrypt):

openssl pkcs12 -export -out /etc/letsencrypt/live/example.com/example.com.pfx -inkey /etc/letsencrypt/live/example.com/privkey.pem -in /etc/letsencrypt/live/example.com/cert.pem

I have checked and it seems that it does not like the .pfx when it is included also the fullchain.pem (or .crt). If I included also the fullchain it showed the above error. 

During the first tries I thought it was due to some permissions/ownership missing, but after these tries I was already convinced that it was not the issue.

After the removal of the fullchain, so leaving the cert and the key for the pfx output, the DNS has accepted the DNS-over-TLS configuration and the HTTPS for the web portal.

I have also tested the DNS-over-TLS on Android (using Private DNS in Automatic mode in LAN) and it works with no issues.

**Comment by ShreyasZare** [comment]
Thanks for the details. Using `fullchain.pem` will cause issues. You need to use `chain.pem` with the `-certfile` option. Without adding chain to the pfx certificate, it may not work with some web browsers or devices.

I would recommend that you use the `pkcs12convert.sh` script given in the [blog post](https://blog.technitium.com/2020/07/how-to-host-your-own-dns-over-https-and.html) since this will help with auto renewal of the cert with the pfx getting regenerated.
