### ISSUE TITLE
Feature Request: OpenNic

### ISSUE THREAD

**Issue by necrogami** [TechnitiumSoftware/DnsServer#272]
Is there a way to be able to process requests to opennic tld's?

**Comment by ShreyasZare** [comment]
Thanks for asking. There is no built in feature specially for supporting another root servers. But, you can configure stub zones for each of the TLDs hosted by OpenNIC and the DNS server will resolve those TLDs normally.

I added .geek TLD to my local DNS server which looks like below:
![image](https://user-images.githubusercontent.com/10008172/123067334-859a5400-d42e-11eb-8319-2cd21de16f8f.png)

Once, the stub zone is added, it will resolve sub domains normally:
![image](https://user-images.githubusercontent.com/10008172/123067539-b4b0c580-d42e-11eb-8c89-bdd9d895f8b3.png)

**Comment by emmatebibyte** [comment]
Would there be a way to automatically resolve OpenNIC tlds without adding them?

**Comment by ShreyasZare** [comment]
> Would there be a way to automatically resolve OpenNIC tlds without adding them?

No, since these are part of alternate root zones and conflicts with Internet's root zone. You will need to add Stub zone (like above) for either the specific TLD or for the root zone that OpenNIC provides. You an also create a Secondary root zone such that you get a local copy of OpenNIC's root zone.
