### ISSUE TITLE
Feature request: trigger command on specific query

### ISSUE THREAD

**Issue by shawnkhall** [TechnitiumSoftware/DnsServer#283]
My goal is to have a public recursor with sinkhole built in with my own rules. It's worked fine for, well, *years* thanks to Technitium DNS Server...until about a month ago. Logs jumped from 20 KB to over 20 MB overnight and continued to grow. Unfortunately, the increase is the result hundreds of IP addresses (that change!) each day requesting the EXACT SAME malicious domains. Clearly this is *intended* as abuse and needs to be *treated* as such. Unfortunately, the only way I can identify the culprits is to enable `log all queries` which hurts privacy (I want it as anonymized as possible) and balloons the logs even more.

What I'd really like to be able to do is setup `DNS triggers`.

Whenever certain domains are queried I'd like to trigger an external command. This command would take parameters that allow it to parse context and perform actions (and possibly create it's own detailed log for analysis). For example, it would allow me to block those IP addresses on their first request of the malicious domain, so I don't have to deal with 40,000 malicious requests every day for the same domain from these people.

`if {qname} = "evil.example.net" do "ipset add blocklist {ip}/32"`
or
`if {qname} = "evil.example.net" do "echo {timestamp}  {ip}>/etc/blocklist.txt"`

By making it as generic as possible it would be capable of being used for the domain equivalent of port-knocking as well.

Optional variables should include: timestamp, IP, protocol, qname, qtype, qclass, and answer.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. If I guessed correctly, you must be getting these queries for "pizzaseo.com" with type RRSIG or a query for "sl" with type ANY or a similar. You can google "pizzaseo.com dns attack" and get people talking about it. In fact, I am right now getting these same queries on my live DNS server too.

Blocking the individual IP address is not going to work as you expect since these will keep changing every day and you will just end up with an ever increasing list of blocked addresses.

The thing about these attacks is that the IP addresses you see are that of the victims! The attacker is spoofing the IP address of the victim in the UDP requests so that any response for the queries are sent to the victim's network. These attackers select domain name and types (like RRSIG here) so that the query is small, usually a few bytes while the response is quite large. So the query to response data ratio can be as large as 10-15x or even more with EDNS0 extension support. So if an attacker is sending queries to random DNS servers on the internet at 1mbps speeds then the target network gets 15x bandwidth consumed. These are called DNS Amplification attacks.

One mitigation is to rate limit the number of queries. In Technitium DNS Server you can set the Queries Per Minute option to limit abuse of the server. However, these attackers know that a lot of servers do rate limiting so they send the queries at a very low rate to each individual server. Instead then find a huge volume of DNS server IP addresses to increase the effects.

I am working on improving this rate limiting feature too for making it more effective.

You can also configure recursion ACL option in the DNS server or configure it using iptables and allow only the network addresses that you commonly use and block all other networks from making recursive queries.

**Comment by shawnkhall** [comment]
Thanks, @ShreyasZare. That is one of the reasons I created this request. I'm familiar with amplification attacks and how DNS attacks are generally forged thanks to the untethered nature of DNS via UDP.

However, I've been actively blocking the participating IP addresses for a couple days now and all but a tiny fraction of the requests are effectively blocked using the IP address that appears in the logs. Traffic for the pizzaseo requests has dropped over 80% since I started monitoring the logs and blocking those IP addresses - and I've been late to the party by parsing the logs manually and infrequently. It's not a perfect fix, but it is better than nothing. Using triggers I think I could drop this to a mere 1-2% of what was hitting my server when it wasn't filtered at all.

It isn't really material that the IP addresses used are likely also victims, since blocking the requests is effective either way and they would benefit as well, since the amped response isn't being replied to their IP. It saves them and I bandwidth, resources, and reduces backscatter, too.

I'm afraid that QPM/rate limiting can't work as a solution. The actual pizzaseo requests, while a large amount of requests as a whole, amount to less than 1000 requests per day from any individual IP address (usually under 90), so the individual IP addresses would never hit QPM limits. Even setting *very* low limits, such as two requests per minute, would still allow these attacks to continue. The logs show that very few of the IP addresses involved make requests more frequently than once every 31-34 seconds.

In any case, while the goals above are the impetus behind this, once I realized that triggers could be used for other useful things, such as precaching DNS and websites, or automating other activities, I really wanted it for those purposes...in addition to automated blocking of the pizzaseo stuff, of course.

**Comment by ShreyasZare** [comment]
Thanks for the detailed feedback. I agree, rate limiting is not a perfect solution for this especially if you are running a resolver on public IP.

I have planned for a change in the DNS apps framework which should make it possible to make apps that can do such things actively. So, this will be much more flexible to have to implement such a feature with those new changes in the design. 

I wont be able to add this in the upcoming release since its already delayed due to some features that took a lot of time. So, do expect this in the release after the current one probably a month later.

**Comment by ShreyasZare** [comment]
New version 7.0 is now available with a new Drop Requests app that can fix the issue discussed. Do update and let me know if any changes are required. Closing the issue for now.
