### ISSUE TITLE
Windows beginner: Created zone but when I type it in browser or ping it is not found 

### ISSUE THREAD

**Issue by kimhadfun** [TechnitiumSoftware/DnsServer#292]
I created a zone called test.local that I believe is mapped to 127.0.0.1

IIS Express is running a website on 127.0.0.1:8080

When I go to test.local:8080 nothing comes up
When I try to ping test.local nothing is found.

Please help.

![Untitled](https://user-images.githubusercontent.com/88814208/129136337-fad34779-f99c-49e8-bd34-f836ba902cf0.png)

**Comment by ShreyasZare** [comment]
Thanks for the post. You need to configure your network adapter with 127.0.0.1 as the DNS server so that the DNS requests are sent to your locally running DNS server. 

To make it easy, you have an option in the system tray tool that comes with the DNS server. Just right click on the icon in the system tray, go to Network DNS and then select Technitium and the too will configure your network to with the local DNS server.

**Comment by kimhadfun** [comment]
Thanks @ShreyasZare 

That was amazingly easy

![Untitled](https://user-images.githubusercontent.com/88814208/129195550-b5fbec86-5002-4893-a093-649f178afd66.png)
