### ISSUE TITLE
DoH DoT logging revese proxy

### ISSUE THREAD

**Issue by Wunderharke** [TechnitiumSoftware/DnsServer#298]
I run a public Technitium DNS for some time and it works great! So far, the only feature I'm missing is DNSSEC.

Recently, my server has been increasingly targeted by DDOS attacks, therefore I now work more with the log files to block any IPs early.
I noticed that in my setup with TLS terminating reverse proxy all requests over HTTPS or TLS are logged as requests from localhost.
Is there a possibility to read the X-Forwarded-For header for such requests? This would make the logs and the statistics more meaningful.

**Comment by ShreyasZare** [comment]
> Thanks for the suggestions! DoT I now serve directly, that works without problems and also have the rate limit enabled. Is there any way to easily estimate how many requests a normal client sends?

Its not possible to know what values to set for rate limiting since it depends on many factors and will vary widely. You will have to find out the values by trial and error or by observing the trends for last few days.

> I am using apache as a reverse proxy and have tried using `RemoteIPHeader X-Real-IP` to set the `X-Real-IP` header. So far it doesn't work and I don't know a good way to debug it. Should I finally be successful I will describe the procedure here (and possibly create a doc pull request).

I have not used apache for this before but from the docs it looks like you have used the correct directive. I would suggest that you try using packet capture and see if the header is indeed being added by the apache reverse proxy.

**Comment by Wunderharke** [comment]
I've investigated this and had success with `RequestHeader set X-Real-IP %{REMOTE_ADDR}s`.
