### ISSUE TITLE
[feature request] ipv4 / ipv6 only

### ISSUE THREAD

**Issue by cubakcabak** [TechnitiumSoftware/DnsServer#30]
please add an option to have ipv4 only request answered and cached.

having an options to disable/remove ipv6 answer for ipv4 client will increase browsing performance.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. This feature is not feasible to implement since this is not how DNS is supposed to respond to queries. DNS Server will respond with an IPv6 address when the application requests an AAAA resource record. Application is supposed to decide what type of query it must send based on the type of network access it has.

On a modern OS like Windows 10, there is already IPv6 transition technology working called Teredo which will add a software Teredo network adapter which will have an public IPv6 address assigned. This setup exists if there is any IPv6 only website or host that the client needs to communicate with. In such cases, its vital that the DNS responds with correct AAAA resource record.

There is a similar DNS "feature" called DNS64 which is used by IPv6 only networks. In there, the DNS responds with a AAAA record even when the domain has only A record using a DNS64 IPv6 network prefix. The client connecting to such an IPv6 address will send the request to ISP which has NAT64 in place which does network address translation from IPv6-only to IPv4-only network thus allowing IPv4 network access from an IPv6-only network.
