### ISSUE TITLE
Feature Request - Option to clear DHCP lease

### ISSUE THREAD

**Issue by micush** [TechnitiumSoftware/DnsServer#307]
Hi. Sometimes it is helpful to be able to clear a specific DHCP lease from the server. I realize removing the lease from the server does not remove it from the client, but having the option to clear a lease and also remove its associated DNS data without having to wait for the lease to expire would be a big help. Thanks much.

**Comment by ShreyasZare** [comment]
Thanks for the request. This option had been requested many times and has not been added due to potential issues it may cause in the network.

As you mentioned that you know the client wont know if the lease is removed but there are a lot of people who don't know this and will abuse this option causing IP conflict issues all over the network. Most wont be able to debug why the clients are losing connectivity randomly and a lot will blame it on the DHCP server giving out same IP address to multiple clients. Anyone who knows why this happened too will find it a tedious task to fix each client manually.

So just to make sure that things run well for everyone that this option is not added. Using a lower lease value will be much better way to manage this.

**Comment by micush** [comment]
Hi,

There needs to be a way to remove an unwanted lease manually. Since the
config files are binary, there's no way to do it outside of the
application.

This can be done in just about every DHCP server I have ever used, so you
must provide a way to do it. Implement the option to ping a DHCP address
before assigning the lease should help cover the scenario for a duplicate
IP being assigned by removing a lease early.

Regards,

Michael

**Comment by ShreyasZare** [comment]
I understand why you would want this option and you are a professional who knows these stuff well. What I am concerned is that if there is a button to remove a lease then there will be a lot of people who are not aware of the technical details and are going to misuse it thinking its safe to do so only to see lots of IP conflicts.

Using ping to do duplicate IP detection is not reliable at all. Like you can have this feature added but it wont be reliable in all networks. There are a lot of devices that dont respond to ping. And not all networks have AD like policy to make sure that ICMP is not blocked. Also there are people block ICMP outright everywhere because they think it will make their network secure somehow.

So, if there has to be an option then it has to be made difficult to be used in the GUI just to prevent footgun scenario.

**Comment by ShreyasZare** [comment]
I can also imagine support emails saying the network no longer works for some clients when using the DHCP server. Only to find out after 10 emails that the user decided to delete leases. lol.

**Comment by novafiddler** [comment]
I don't find it funny. If a user is advanced enough to stand up there own Technetium instance, why wouldn't they be knowledgeable enough to manage a simple DHCP server? 

I just tried to set an IP reservation in technetium and it DID NOT respect the manual IP I set. I figured this behavior was coming from a still-in-use lease. Upon trying to delete the lease, I realized that technetium DID NOT have this crucial feature. 

Now, in order to set the manual ip reserveration, I have to wait for the lease to expire (2 days), which is ridiculous.

**Comment by ShreyasZare** [comment]
> I don't find it funny. If a user is advanced enough to stand up there own Technetium instance, why wouldn't they be knowledgeable enough to manage a simple DHCP server? Just saying.

Thanks for the comment. Probably you have not come across such issues. I have seen a lot of admins that don't have much detailed understanding. Also, this product is being used by non professionals too.
 
> I just tried to set a DHCP IP/lease reservation in technetium and it DID NOT respect the manual IP I set. I figured this behavior was coming from a still-in-use lease. Upon trying to delete the lease, I realized that technetium DID NOT have this crucial feature.
> 
> Now, in order to set the manual ip reservation, I have to wait for the lease to expire (2 days), which is ridiculous. There should definitely be a way to delete at a minimum individual leases. Thank you.

There is one fix that you can do if you have access to this client with the lease. You can add an Exclusion for that IP address and renew the lease on the client either by command or by rebooting it. This will force the client to release the lease and will get another one.

So, I have given this a though and will get this option added in the next release which may come mostly by next month. The option will be made a bit difficult to access with a warning message before confirmation just to make sure that the user is aware of what may go wrong.

**Comment by ShreyasZare** [comment]
New version 7.0 is now available with option to delete DHCP lease.

**Comment by micush** [comment]
Thanks for the usability improvements. Much appreciated.
