### ISSUE TITLE
Feature Request - Configure forwarder protocol per forwarder

### ISSUE THREAD

**Issue by micush** [TechnitiumSoftware/DnsServer#308]
Hi. In "Settings" -> "Proxies & Forwarders" it would be advantageous to be able to configure the forwarder protocol on a per forwarder basis. That way some forwarders in the list could use TLS, some could use HTTPS, and some could use TCP/UDP. As it looks to be right now all forwarders in the list must use the same protocol. It would be better to associate the protocol to the forwarder.

**Comment by ShreyasZare** [comment]
Thanks for the post. This forwarder config is done deliberately to prevent users from mixing multiple protocols together. This is done for privacy and security reasons since mixing encrypted protocols with UDP/TCP will disclose all traffic and effective security will be of the lowest protocol security wise.

You can use conditional forwarder zones to do this if you wish to. To do that you will need to create a conditional forwarder zone for "." i.e. root and then add multiple FWD records that use different protocols. But I would not recommend this to be done due to the issues mentioned above.

**Comment by micush** [comment]
Hi,

As the end user/administrator I should have the choice to make that
decision myself. In case I want to use both TCP/UDP forwarders and DoH/T
forwarders I then have to use two different DNS servers? That makes no
sense. Maybe put the option of ordering the servers in order of preference
and the option to enable/disable an item within that list. I can move the
servers around and enable/disable them in the list for the preference of
protocol I choose.

Regards,

Michael

**Comment by ShreyasZare** [comment]
Thanks for the suggestion. The current implementation randomly chooses the forwarders for load balancing and also does 2 requests concurrently so that the fastest response is then used. This implementation makes the resolution fast and also fault tolerant. 

Making the implementation to use a preference will be a step backwards since this will mean that the first forwarder will be used to send the request and the DNS server will have to wait for timeout and do retries before it tries the second forwarder.

Another issue with this will be that an active attacker can just block you DoT or DoH requests and wait for you to send them with UDP/TCP. So, downgrade attacks will be possible with such a config.

If you still want to mix up the protocols and be able to enable/disable them then you can do it with conditional forwarder zone as I mentioned earlier. All you need to do is create a forwarder zone with name as "." and add multiple FWD records. You can then enable/disable these records as required. Such a setup will work just like the forwarders option in the Settings.

**Comment by ShreyasZare** [comment]
Closing this issue since it can be achieved with conditional forwarders.
