### ISSUE TITLE
SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL

### ISSUE THREAD

**Issue by Flagelmann** [TechnitiumSoftware/DnsServer#335]
Hello all,

I'm having, since few weeks, a strange error never appeared before:

---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
---> Interop+Crypto+OpenSslCryptographicException: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown

The TLS certificate installed and loaded for Technitium DNS Server is valid (with newer root chain ISRG Root X1 of Let's Encrypt).

This error appears when, specially from mobile devices, some hosts does some queries. The actual server seems working, in DNS-over-TLS mode (port 853).

I have a doubt, related to the expiration of the DST Root CA x3 that happened on September 2021 and on which Let's Encrypt was on.

Is that happened to someone else? Someone have some suggestions about this scenario?

Many thanks and kind regards.

**Comment by Flagelmann** [comment]
Hello again, 

I would try to use the "Private DNS" feature, for further tests, but I think that, on Android 9, the OS supports/checks only up to TLS 1.2 version for that feature. I have seen that Technitium is using TLS 1.3 version.

Is it possible to add, on the web gui interface, a way to switch between these two versions (in the Web Service tab maybe)?

Or, is there any other way to modify it?

Many thanks and kind regards.

**Comment by ShreyasZare** [comment]
> 
> 
> Hello again,
> 
> I would try to use the "Private DNS" feature, for further tests, but I think that, on Android 9, the OS supports/checks only up to TLS 1.2 version for that feature. I have seen that Technitium is using TLS 1.3 version.
> 
> Is it possible to add, on the web gui interface, a way to switch between these two versions (in the Web Service tab maybe)?
> 
> Or, is there any other way to modify it?
> 
> Many thanks and kind regards.
> 
> **UPDATE**: ok, it seems that on my server is actually enabled only TLS 1.3, while TLS 1.2 is disabled. Checking another valid "Private DNS" on Android, like Quad9, it is possible to use it on Android and it is actually enabled for both TLS 1.2 and 1.3. So, to let using Technitium DNS Server also on Android devices, with "Private DNS" it would be needed to enable also TLS 1.2.

Thanks for the request. Will try it out and implement it. Do let me know which OS are you running the DNS server on so that I can test it out on it.

**Comment by Flagelmann** [comment]
Hello,

sorry for the delay.

I'm using a Raspberry Pi 4 (Linux 5.10.63-v7l+).

Anyway, I have an update.

During the last days I've been back on this issue and the following are the news:

I have checked again the certificate and it was still with the old DST Root CA X3 (now expired). So I removed all and re-issued again a new one and now it is correctly ISRG Root X1 (using acme.sh).

Now the strange issue is that, if I check the three different files generated by the request (ca.cer, example.cer and fullchain.cer) it is all ok (they are validated correctly against ISRG Root X1).....but, if I export to pfx and use it into Technitium DNS server, when I try using DNS Client web app (using example.com:853 and TLS as protocol) for google.com, it just gives me the following error: 

The remote certificate is invalid because of errors in the certificate chain: PartialChain

The question is: is it possible to not use pfx and instead specify the three different cer files?

I'm asking it as, in Nginx, for example, using them (with other domains but always with Let's Encrypt), they are correctly checked (Error Code 0) with _openssl s_client -connect example.com:443_.

If I try openssl s_client -connect p.flag0s.click:853 it gives _Verify return code: 20 (unable to get local issuer certificate)_

Many thanks

**Comment by ShreyasZare** [comment]
Well, its not an issue with the pfx certificate unless you didn't include the certificate chain when generating the pfx file. I have seen this issue with a couple of installations on my setup but I haven't found a fix yet.

I have Raspberry Pi 3 and 4, both running same OS with same updates but, one of them is able to use DoH URL from a cloud server running Technitium DNS Server with DoH service and the other one fails with the `PartialChain` or `TimeNotValid` errors. The DoH server is fine since I can verify the cert it returns using any web browser. Its the client that is failing to validate the certificate for some unknown reasons.

I have a Ubuntu server running too which has this issue while another setup running Ubuntu does not. Both of these servers are updated to latest.

This issue occurs only for Let's Encrypt certificates and affects only a few deployments which makes it a strange and difficult to reproduce. Like if I try a fresh setup on a Ubuntu VM, it works perfectly fine for the same DoH URL which the other server fails with an error.

**Comment by Flagelmann** [comment]
Ok, fixed it and also the Private DNS feature on Android systems.

I have used ZeroSSL instead of Let's Encrypt, then recreated the pfx with openssl (using the below approach) and finally restarted the service.

After doing that I tried again to make a dns query to google.com with TLS protocol and it works as expected. Then I have tried using the FQDN in Android for Private DNS functionality and now it accepts it with no issues.

So....all fixed. :D

The openssl approach I used (to create pfx):

openssl pkcs12 -export -out /etc/dns/example.pfx -inkey /root/.acme.sh/example/example.key -in /root/.acme.sh/example/fullchain.cer -certfile /root/.acme.sh/example/ca.cer -passout pass:xxxxxxxxxx

**Comment by ShreyasZare** [comment]
Yes, the ZeroSSL cert will work as expected. The issue is only with Let's Encrypt certs on some deployments.

**Comment by fullet-tortuga** [comment]
Is there a place where I can download the apps in zip archives as a workaround?

I'm also getting this error when clicking the "App Store" button:
"Error! The SSL connection could not be established, see inner exception."

And this is the trace:

[2022-02-13 00:26:49 Local] [127.0.0.1:39544] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: NotTimeValid
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at DnsServerCore.WebServiceAppsApi.GetStoreAppsJsonData() in Z:\Technitium\Projects\DnsServer\DnsServerCore\WebServiceAppsApi.cs:line 74
   at DnsServerCore.WebServiceAppsApi.ListStoreApps(JsonTextWriter jsonWriter) in Z:\Technitium\Projects\DnsServer\DnsServerCore\WebServiceAppsApi.cs:line 189
   at DnsServerCore.DnsWebService.ProcessRequestAsync(HttpListenerRequest request, HttpListenerResponse response) in Z:\Technitium\Projects\DnsServer\DnsServerCore\DnsWebService.cs:line 756

**Comment by ShreyasZare** [comment]
> Hi there. Is there a place where I can download the apps in zip archives as a workaround in the mean time?
> 
> I'm also getting this error when clicking on the "App Store" button: "Error! The SSL connection could not be established, see inner exception."

Yes, you can manually download the DNS app zip files by referring to this [json link](https://download.technitium.com/dns/apps/apps.json). Just open the link in any web browser copy the zip file url that you want to install and download it. You can then use the Install button in the Apps section to manually install the zip file.

**Comment by fullet-tortuga** [comment]
That's great! Thank you very much, both for the help and for this excellent DNS server.

**Comment by ShreyasZare** [comment]
So, I had to fix this issue for a setup and found a solution that works. I am assuming the OS to be Ubuntu and the steps work on both Ubuntu server and Raspberry Pi. 

Follow these steps on your server running the Technitium DNS Server:
1. Install the "ISRG Root X1" and "Let’s Encrypt R3". Both of these certificates are available here: https://letsencrypt.org/certificates/

```
# apt-get install -y ca-certificates
# wget https://letsencrypt.org/certs/isrgrootx1.pem -O /usr/local/share/ca-certificates/isrgrootx1.crt
# wget https://letsencrypt.org/certs/lets-encrypt-r3.pem -O /usr/local/share/ca-certificates/lets-encrypt-r3.crt
# update-ca-certificates
```

2. Generate the PFX / PKCS12 certificate again using the following command:

```
# openssl pkcs12 -export -out /etc/letsencrypt/live/example.com/example.com.pfx -inkey /etc/letsencrypt/live/example.com/privkey.pem -in /etc/letsencrypt/live/example.com/cert.pem -passout pass:mypassword
```
Note: The above command does not pass the `chain.pem`. The DNS server will automatically load the installed "Let’s Encrypt R3" certificate.

The DNS server will automatically reload the new PFX file within a minute so you do not need to restart the DNS server. Once you see that the TLS certificate was reloaded in the DNS server logs, you can test the DNS-over-TLS or the DNS-over-HTTPS that you have configured the certificate for.

You can use the following openssl command to test the DNS server's DNS-over-TLS service:
```
# openssl s_client -connect example.com:853
```

You can use the following openssl command to test the DNS server's DNS-over-HTTPS service:
```
# openssl s_client -connect example.com:443 -servername example.com
```

**Comment by ShreyasZare** [comment]
The above fix was tested on multiple setups and is working well.
