### ISSUE TITLE
API HTTP return code

### ISSUE THREAD

**Issue by echodreamz** [TechnitiumSoftware/DnsServer#343]
Seems like all API requests return 200 OK response even if there is an error. For example, when doing a login request, would it be good to return 403 code on invalid login attempts, or a 429 return code on too many login failures. If you do a request that has an error returned, returning a 500 error to indicate the server had a problem processing your request along with your normal JSON response.

Thoughts?

**Comment by ShreyasZare** [comment]
Thanks for asking. The application API errors and HTTP errors are kept separate so that both of them can be handled separately and correctly. 

Like when the server returns `500` then it is clear in the current case that this error is not related to the application API but something else related with the web server like configuration issues.

A lot of deployments do reverse proxy to the DNS server. In such case, a `429` error could be ambiguous since the reverse proxy may have a rate limiting configured. So, the client may not be sure if its a issue with too many login attempts or simply making to many calls frequently. A reverse proxy may also add its own basic auth so it will respond with `401` error which is clearly not coming from the application API.

A lot of HTTP clients in some languages or libraries throw exception when the response code is not `200`. So, in such cases, the handling of negative response from API requires doing exception handling and do tasks in a `catch` block. This also has performance issues since exceptions are expensive to handle.

Having a `status` in response json makes its easier to handle response with a single switch case. So the code is not split for success and error callbacks.
