### ISSUE TITLE
Feature Request: Per-zone caching settings

### ISSUE THREAD

**Issue by xenorites** [TechnitiumSoftware/DnsServer#356]
Thanks for this software, it's fantastic!

I'm running into an issue where I wind up with NXDOMAIN records cached for excessively long times, and I have to manually clear the cache. It would be nice to be able to modify settings like the maximum TTL - or even disable caching entirely - on a per-zone basis.

**Comment by ShreyasZare** [comment]
Thanks for the compliments.

The NXDOMAIN negative cache uses TTL provided by the domain's SOA MINIMUM value. If SOA is not available in the response then the Negative Cache TTL value from the Settings is used. This implementation is as per standards. Thus if a NXDOMAIN is being cached for too long then its just due to how the domain admin has configured it in the SOA record.

There is also Serve Stale feature enabled by default which will keep the expired records in cache till the serve stale TTL expires. So, you will see expired records in the cache with TTL 0 in such cases. You can reduce the Serve Stale TTL value to delete the records early or disable the feature. Its recommended to keep the feature enabled though since it helps to improve resiliency.

As you have mentioned, using Maximum TTL will put a cap on all records and thus the cache will expire early. Having these settings on per-zone basis will make it quite difficult to configure correctly.

Do let me know the use case of having such a feature. It might be that there is a better way to do this.

**Comment by xenorites** [comment]
Adjusting the SOA MINIMUM to very low values on the upstream zone works, but I still think it would make sense to have the ability to disable caching for forwarder zones. Perhaps a per-zone basis is excessive, but at least for zones controlled by TechnitiumDNS it makes sense to have control over the caching behavior - even if it's just on/off.

My use case is hosts being provisioned for FreeIPA; the initial lookup for the hostname is returns an NXDOMAIN, telling the client to perform DNS registration as part of its enrollment. Once the client has registered, the DNS record is made present in the zone's upstream, but TechnitiumDNS will still return the cached NXDOMAIN.

**Comment by ShreyasZare** [comment]
> Adjusting the SOA MINIMUM to very low values on the upstream zone works, but I still think it would make sense to have the ability to disable caching for forwarder zones. Perhaps a per-zone basis is excessive, but at least for zones controlled by TechnitiumDNS it makes sense to have control over the caching behavior - even if it's just on/off.

Turning off cache will hit the DNS server performance quite severely and thus its not a good option to have.

> My use case is hosts being provisioned for FreeIPA; the initial lookup for the hostname is returns an NXDOMAIN, telling the client to perform DNS registration as part of its enrollment. Once the client has registered, the DNS record is made present in the zone's upstream, but TechnitiumDNS will still return the cached NXDOMAIN.

Is the "client" a software that you develop? In that case, querying to the name servers of the domain directly will give you a correct answer without worrying about caching.
