### ISSUE TITLE
Move "logs" and "stats" in different location

### ISSUE THREAD

**Issue by Globulopolis** [TechnitiumSoftware/DnsServer#36]
Maybe it's better to move these folders from config folder because it's not config related content?

**Comment by ShreyasZare** [comment]
Thanks for the suggestion. The name 'config' does not accurately describe the intent. 

A single config folder that contains everything for that instance was done by design so that the DNS Server can be run as a portable app for testing where you give config folder path to use. 

So you can have multiple test setups for different scenarios and then you could start the DNS Server by giving the scenario specific config folder to it as a command line parameter.
