### ISSUE TITLE
Request: Track the last time a record was used / use the query log db to show a timestamp

### ISSUE THREAD

**Issue by LordMike** [TechnitiumSoftware/DnsServer#365]
I have a number of records now, some of which are old and probably not used anymore.

It could be cool, in the zone records list, to see a last-used timestamp. 

It should be possible to get this information from the query log (possibly the sqlite db app), alternatively it could be tracked within the zone itself (in case the log isn't always available).

As an example, I've added a column in the table with "Last used", which could be a timestamp, a "time since" value, or maybe something else. It could even be a link to the query log app, if that exists:
![image](https://user-images.githubusercontent.com/1027111/159119366-bd58db65-59ad-4a98-ba64-9fbcb133fc47.png)

If the zone tracks the value, it could also be an in-memory thing only, such that a server restart will clear the value.

**Comment by ShreyasZare** [comment]
Thanks for the post. It can be done only with Query Log app since it is a queryable database. Cannot do this with text logs or with the dashboard stats data.

There will be performance issues with such an implementation since to load a zone, it will need to query for each record. There can be zone with thousands of records which will take a lot of time to load the zone to view. For example, if you have the root zone running as a secondary zone then it has around 13.6k records.

In-memory counter that the zone manages too will have performance issues since the counter would need to be synchronized across multiple threads which will create a bottle neck taking the performance down significantly.

**Comment by LordMike** [comment]
Actually, you wouldn't need to keep it synchronized - it doesn't matter what the value actually is.. If you stored a datetime (if we wanted to know the exact date and time), it wouldn't matter if two threads concurrently tried to set the value - which of them actually wins. If it's second `44.344566` or `46.4325345` doesn't matter.

Of course, if the counter was separate, and based on a dictionary, you would of course need synchronization for this dictionary. I imagine you would store the value on the record itself, which would only have one field/property for "last-access". This field wouldn't need synchronization.

**Comment by ShreyasZare** [comment]
Ok the in-memory option to store it in the record itself looks good. Will evaluate it once.

**Comment by ShreyasZare** [comment]
Version 8.1 is now available that adds the last used values for zone records. These values are only in memory so a restart will reset them.

Cache records also have these values which are now used to remove least recently used records from cache when the total cache entries exceed the configured option in settings.
