### ISSUE TITLE
Bug: Web Server not responding for hostname, when listen IP is set to other than 0.0.0.0

### ISSUE THREAD

**Issue by LordMike** [TechnitiumSoftware/DnsServer#366]
I have a curious situation. I'm trying to use my DNS server for other things as well, so I want technitium DNS to listen to `192.168.1.2` (port 80), while the other app runs on `192.168.1.3` (port 80).

I changed the Web Service listen IP setting from `0.0.0.0 / [::]` to `192.168.1.2` (no ipv6), and suddenly I can't visit the server at `http://dns.home` (which resolves to `192.168.1.2`). If I change the listener back to `0.0.0.0`, `http://dns.home` works.

## When the listener is `192.168.1.2`
I can confirm I'm hitting the server with `http://dns.home/`, as shown by this curl (note the server responding is NetCore 2.0):
```
$ curl -v http://dns.home/
*   Trying 192.168.1.2:80...
* TCP_NODELAY set
* Connected to dns.home (192.168.1.2) port 80 (#0)
> GET / HTTP/1.1
> Host: dns.home
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Content-Type: text/html
< Server: Microsoft-NetCore/2.0
< Date: Sat, 19 Mar 2022 22:05:56 GMT
< Content-Length: 30
<
* Excess found in a read: excess = 106, size = 30, maxdownload = 30, bytecount = 0
* Connection #0 to host dns.home left intact
<h1>Not Found (Not Found)</h1>
```

Curl to `http://192.168.1.2`:
```
$ curl -sv http://192.168.1.2/ | head
*   Trying 192.168.1.2:80...
* TCP_NODELAY set
* Connected to 192.168.1.2 (192.168.1.2) port 80 (#0)
> GET / HTTP/1.1
> Host: 192.168.1.2
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server:
< X-Robots-Tag: noindex, nofollow
< Content-Type: text/html
< Cache-Control: private, max-age=300
< Date: Sat, 19 Mar 2022 22:08:14 GMT
< Transfer-Encoding: chunked
<
{ [84491 bytes data]
﻿<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
(.. truncated ..)
```

## When the listener is `0.0.0.0`
I perform the same http query for dns.home, and this time it responds with the expected HTML.

```
$ curl -sv http://dns.home/ | head
*   Trying 192.168.1.2:80...
* TCP_NODELAY set
* Connected to dns.home (192.168.1.2) port 80 (#0)
> GET / HTTP/1.1
> Host: dns.home
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server:
< X-Robots-Tag: noindex, nofollow
< Content-Type: text/html
< Cache-Control: private, max-age=300
< Date: Sat, 19 Mar 2022 22:09:12 GMT
< Transfer-Encoding: chunked
<
{ [43611 bytes data]
﻿<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
(.. truncated ..)
```

**Comment by LordMike** [comment]
I think I found the culprit. If the listen IP is `any`, the server will listen to `http://+/..` while in my case it will listen to `http://192.168.1.2/..`

https://github.com/TechnitiumSoftware/DnsServer/blob/d61f31162f0969721180d03b4a41f3fab71e0e18/DnsServerCore/DnsWebService.cs#L4088-L4115

I can't put in anything that makes the host be `dns.home` or `+`, so I don't think I can workaround this.

I'm curious though, why should `host` ever be anything but `+` ?.. the listener will only listen to the IP's specified anyways, so you shouldn't bind to `0.0.0.0` even if you use `+` .. unless I'm missing something.. This whole Http server thingy is very verbose, and could probably benefit from a rewrite to use kestrel .. :)

**Comment by ShreyasZare** [comment]
Thanks for the post. This is an issue with the HTTP web server (HTTPListener) that the DNS server uses. This HTTPListener only takes the host names and will listen on the interface based on the provided host names automatically. So, it does not work as expected when you specify IP address as the hostname and then use a domain name to query the web server. 

Allowing to add the domain name to use as the host name will just make the web server to listen on all interfaces so it just better to keep the default ANY address to allow to use a domain name and use a firewall rule to control the inbound interface.

HTTPListener was used since the project started when .NET Core was very new and thus was using .NET Framework. When .NET Core 3.1 was available, the project was updated to compile as a .NET Standard 2.0 DLL to allow it being used in both .NET Framework and .NET Core 3.1. This was since .NET Core 3.1 didnt have option to run Windows Service so had to keep using the .NET Framework.

With .NET 5 everything was merged into one but the HTTPListener dependency is still there since it will take a lot of time to implement the Kestrel. Changing to Kestrel is already in my to do list but, I am not sure about the timeline for it.

**Comment by LordMike** [comment]
It's also a big change - I noticed a number of other possible refactorings, like using JsonSerializer (Newtonsoft or System.Text.Json), instead of writeproperty/writevalue calls. Is there a reason you made it like this?

**Comment by ShreyasZare** [comment]
> It's also a big change - I noticed a number of other possible refactorings, like using JsonSerializer (Newtonsoft or System.Text.Json), instead of writeproperty/writevalue calls. Is there a reason you made it like this?

Ya, its the same with Netwonsoft dependency too. The current implementation was done such that there is no need to create modal classes for all the responses that needs to be generated. So, this method to generate json was used and then I kept it that way everywhere for consistency. There will surely be a better way to do it now. Need to figure out if the new json classes with dotnet can parse json string into anonymous objects too just like Networksoft.

**Comment by LordMike** [comment]
Else .. there _are_ benefits to strongly typed models, especially for settings where you know all the values that can be.. This helps identify errors where you rename or remove something that is still in use.

Other than that, it seems `System.Text.Json` does support anonymous objects/types in both serialization and deserialization. In addition, it also has `JsonElement` which mimicks `JObject` and friends.

**Comment by shawnkhall** [comment]
So where do we land on a solution here? I have other services that use ports 80 and 443, so +/0.0.0.0 isn't an option for me as IIS is consuming the other IP addresses. Since installing 8.0 I'm no longer able to take advantage of DoH at all on either http or https. It seems that Technitium DNS Server no longer operates as a service on 80/443 whenever anything other than 0.0.0.0 is included.

**Comment by ShreyasZare** [comment]
> So where do we land on a solution here? I have other services that use ports 80 and 443, so +/0.0.0.0 isn't an option for me as IIS is consuming the other IP addresses. Since installing 8.0 I'm no longer able to take advantage of DoH at all on either http or https. It seems that Technitium DNS Server no longer operates as a service on 80/443 whenever anything other than 0.0.0.0 is included.

The issue has not been changed with v8.0, it has been exactly the same since the first version. Eventually, the built-in web server will be replaced with the one that comes with asp.net core to fix the issue.

The DoH web server and the DNS web console are totally different web servers internally. If you want to host DoH server then you can do that by configuring the "DNS Server Local End Points" to run on a specific IP address i.e. on a specific interface so that it works with your IIS taking up 0.0.0.0:443. The other option is to configure IIS to reverse proxy on 127.0.0.1:8053 and just enable the DNS-over-HTTP optional protocol.

Currently, for the DNS web console, the best option is to configure your IIS web server as a reverse proxy and run your DNS web service on loopback IP address. This way, you configure the SSL/TLS cert as with your other websites running on IIS so you wont need to do it on the DNS server itself.

**Comment by LordMike** [comment]
Would it be possible to add to the list of prefixes being listened to?

I imagine that we could change `_webServiceLocalAddresses` to a `List<string>`, and then use that as hostnames. When they're IP's, they work as now, but when they're anything else, they _should_ enable us to listen to the hostnames we want. 

---

I've tested a bit, and found that the way HttpListener finds out which IP/Port to listen on depends on the platform. On Windows, it's System that listens for connections, on all appropriate ports, and then that does its own internal routing to the correct app (likely why two apps can listen on the same port, but with different paths).

On linux, the program itself will listen on the IP that the prefix(es) resolve to. So, if I f.ex. did `localhost:8000` and `192.168.1.0:8000`, it would resolve localhost to `127.0.0.1` and then listen on both IP's. This also means, if I listen for a hostname that doesn't exist, I get an exception like this: `System.Net.HttpListenerException (50): The request is not supported.`. If the hostname I use resolves to an IP that the local system can't satisfy, I get an `System.Net.HttpListenerException (99): Cannot assign requested address`.

So we're in a pickle. If we _do_ use a name, in my case, `dns.home`, it _**must**_ exist at the time of starting. And since this app is exactly a dns server, we have a catch-22. 

I suppose I _can_ make a hosts file entry for `dns.home -> 192.168...` and workaround it that way. Then the hostname exists, HttpListener can resolve it, the IP can be listened to - and everybody's happy.. But it's not exactly .. straightforward. :|

**Comment by ShreyasZare** [comment]
> But it's not exactly .. straightforward. :|

This is the specific reason to keep it this way as it has different behavior on different platform. On Windows its uses http.sys which IIS also uses to allow multiple apps to run websites on port 80 like virtual hosting without conflicting. But when you put in a hostname, it will listen on all interfaces which is what the default config too does that is to listen on `0.0.0.0`. So, adding support for hostname is not helping to get it working on a specific interface.

Currently the best way to get it working is to keep the default config to listen on `0.0.0.0` so that it works with any hostname you wish and configure a firewall to allow only specific networks to use it. Or the other option to allow only specific interface would be to then setup a reverse proxy for it.

The only proper solution is to replace the web server with asp.net one.

**Comment by LordMike** [comment]
Iirc this issue has nothing to do with network connectivity but with the http server not responding to the Host header sent by the browser.

Also. In my case, I’m using Linux :)

Mike.
________________________________

**Comment by ShreyasZare** [comment]
> Just found this issue after breaking our nameservers by switching their web consoles to run over our private net instead of 0.0.0.0. Any idea on how I can reset this back to 0.0.0.0 so it works again, maybe by editing a config file somewhere?
> 
> I'm running it on ubuntu :)

You can just use the private IP to access the DNS web panel. If due to some reason you cannot use the private IP to access it then you can fix this by logging into the server and using curl command to update the settings as shown below:

1. Run the below command to generate auth token. The response from the command will give you a token that must be used in the next step.
`curl "http://<private-ip>:5380/api/user/login?user=admin&pass=<your-password>"`

2. Use the token you get from step one and run the next command shown below to change the settings:
`curl "http://<private-ip>:5380/api/settings/set?token=<token-from-step-1>&webServiceLocalAddresses=0.0.0.0,[::]"`

**Comment by ShreyasZare** [comment]
> @ShreyasZare Just attempted this from both the private network and the machine itself with same result to no avail
> 
> ```
> root@xxx:~# curl -k "https://<priv_ip>:53443/api/user/login?user=admin&pass=<your-pass"
> <h1>Not Found (Not Found)</h1>
> ```

Thanks for the details. This is a bug in the web server which works well in Windows but gives such issues in Linux. The web server is getting replaced soon so such issues will get fixed.

There are a few options to fix this issue. If possible, try changing the private IP in the network adapter for a moment. Once the IP is different, restart the DNS server. This will cause the DNS server web service to start on `localhost` so you can use the above curl commands with `127.0.0.1` as the IP to reset the settings. Once the settings are reset, you can then restore the changed private IP on the network adapter to the original one.

The other option is to install the DNS server on a windows machine. Once installed, stop the DNS server using the system tray app. Copy the `dns.config` config file from your linux installation to the windows machine in `C:\Program Files (x86)\Technitium\DNS Server\config` folder. Start the DNS server on windows using the system tray app. This will cause the DNS server to start web service on `localhost` and you will be able to open the Dashboard from the system tray app menu option. Open you get access to eh Dashboard, you can go and edit the Settings to restore the original web server addresses. Once the setting are saved, you can just copy the `dns.config` file from windows machine to your linux server. Just make sure to stop the DNS server on your linux server before copying the `dns.config` file. After the file is copied, start the DNS server and it should fix the issue.

Last option is stop the DNS server and delete the `dns.config` file and start it back. The DNS server will restore a default config and create a new file. You can then access the web panel and configure your Setting again. This option is feasible only when your original config had only limited options changed and you remember them to be able to replicate changes manually.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11 is now available which now uses Kestrel web server and thus fixes this issue. Do check and let me know your feedback.

**Comment by LordMike** [comment]
🎉 

![image](https://user-images.githubusercontent.com/1027111/220200604-c00f6f0a-0a69-400a-910a-09f4c7ab328b.png)
