### ISSUE TITLE
Different time in graphs and logs

### ISSUE THREAD

**Issue by Globulopolis** [TechnitiumSoftware/DnsServer#37]
In graphs I see local time but in logs I see an UTC time. I cannot change this because no option for this available at this time.

**Comment by ShreyasZare** [comment]
Thanks for the suggestion. The software records time in UTC in all places. The dashboard API converts the time from UTC to local so that the charts make sense. However, the logs are text files with UTC entries.

It is common practice to have logs in UTC format so that it helps in correlating log entries across various servers during an incident investigation.

**Comment by Globulopolis** [comment]
Can you add an option to log time in local format? Something like an apache server have?

**Comment by ShreyasZare** [comment]
Ya that can be done. Will try to add it in next release.

**Comment by itsKV** [comment]
We can give option on dashboard setting page to set timezone for server wide use. (this will be applicable for logging too)

**Comment by ShreyasZare** [comment]
Well, there is an problem with implementing this as the log starts to be written before the dns settings are loaded. So, need to find a better way to achieve this.

**Comment by ShreyasZare** [comment]
I have decided to keep the timezone in UTC since the dns settings are loaded after logging starts. Closing the issue for now. If required later this can be reopened.
