### ISSUE TITLE
ARM docker Image 8.0 fails to run

### ISSUE THREAD

**Issue by michael-pellegrini** [TechnitiumSoftware/DnsServer#371]
Hello,

Can anyone confirm they have a running instance of the latest docker image on ARM or a raspberry pi?
I ran the latest docker image (8.0) on my raspberry pi 4 and it keeps restarting. 
I can run the latest image on AMD64 without issue.

**Comment by ShreyasZare** [comment]
Thanks for the post. This is relate to the issue here: https://github.com/dotnet/runtime/issues/62402. Its not really an issue with the docker image but due to older version of `libseccomp2` installed on your Raspberry Pi OS.

Follow the instructions given in this comment to fix the issue: https://github.com/dotnet/runtime/issues/62402#issuecomment-987330538. Once you have updated `libseccomp2`, the container will work as expected.

Let me know if that worked.

**Comment by ShreyasZare** [comment]
Just for completeness, adding the steps to update `libseccomp2`:

1. Edit `/etc/apt/sources.list` file and add the following line to include the testing repo as a source:
> deb http://raspbian.raspberrypi.org/raspbian/ testing main

2. Then run `apt-get update` followed by `apt-get install libseccomp2`.

3. Again edit `/etc/apt/sources.list` file and remove the testing repo line you added in step 1.

Once done, the docker container should start working. Run `docker ps -a` to confirm.

**Comment by michael-pellegrini** [comment]
Worked  like a charm.
