### ISSUE TITLE
[request] support DNS-over-TLS

### ISSUE THREAD

**Issue by shawnkhall** [TechnitiumSoftware/DnsServer#38]
This is the most feature rich DNS server I've found, but while it is able to consume DNS-over-TLS from other providers, it is not yet able to receive and respond in kind.

I know it's a big ask, but this would be a huge improvement to be able to assign my own TLS certificate (or better yet, integrate Let's Encrypt) in order to be able to provide DNS-over-TLS (and DNS-over-HTTPS).

**Comment by ShreyasZare** [comment]
@shawnkhall Thanks for the compliments and suggestion. Both these protocols are already in my to-do list. 

Since this may take some time to implement, I have a web app for [DNS-over-HTTPS](https://github.com/TechnitiumSoftware/DNS-over-HTTPS) ready to use meanwhile.

DNS-over-TLS can be achieved for any DNS server using SSL termination feature of nginx. 

You can find instructions to configure both protocols in [this blog post](https://blog.technitium.com/2018/12/configuring-dns-over-tls-and-dns-over.html).

**Comment by ShreyasZare** [comment]
Feature is now available with release of v3.0. In addition, DNS-over-HTTPS is also supported.
