### ISSUE TITLE
little confused installer bundled file

### ISSUE THREAD

**Issue by tkpaul92** [TechnitiumSoftware/DnsServer#380]
hello!

I am a little confused of a Virustotal.com bit of info on the setup file of the current version of DNS Server (https://www.virustotal.com/gui/file/69ae74e4a5d715339c66b75ab107a670f77e6b04ca6ed73073061a654075aa65)
Under the tab "Relations" it lists a file that is detected by almost all engines (59/69) as a virus. (https://www.virustotal.com/gui/file/a8529d442f9138f4075892ded3009ac00f3c5ac957f5109e8b447ceedcfb60fa)
I know AV detections are not always accurate, but usually that many detections are not a coincidence.
What confuses me a bit is that I did not find a file with this checksum anywhere in the DNS Server installation directory.
Does this just mean that somewhere on the Internet someone is offering a malicious version of the installer and Virustotal has linked that to the original installer somehow or is the problematic file somewhere embedded in the original installer?

**Comment by ShreyasZare** [comment]
Thanks for the post. It could be that of the setup installer exe since its the only EXE that could be compiled in VC++ as given in the details. Rest all of the binaries are that of dotnet.

The DNS server uses Inno Setup to generate the installer. Most of the installer software are abused so that can show up in virus total database.
