### ISSUE TITLE
Removing a duplicate lease removes the wrong lease

### ISSUE THREAD

**Issue by Zorlin** [TechnitiumSoftware/DnsServer#385]
Simply put, I've got duplicate leases, and when I remove one, the wrong one gets deleted.

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/1369772/165191766-4d3daa3b-744b-4ffe-9039-f21521d77ae1.png">
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/1369772/165191779-888fa57d-0325-478e-a0d5-0b3c40991cad.png">
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/1369772/165191791-a0ff5efe-6ec8-46f5-af76-39a1fbdc3fb2.png">

**Comment by ShreyasZare** [comment]
Thanks for the feedback. This is not exactly a bug but how the things with DHCP are. There are 2 ways for a client to request lease, one is to use MAC address as the client identifier and the other is to use a random client identifier. So a lot of clients have default config to use a random client identifier which when is changed for some reason, the DHCP server will think that the lease request is for a new client because that client ID is what is used to identify a client. This will make it look like you got a duplicate lease which in reality is just that the client id got changed and the DHCP server cannot figure it out.

The second issue of deleting the lease is that the delete option uses MAC address as the identifier. So, when you tried to delete the lease, the first entry that matched the MAC address was removed which in this case was not the lease that was expected to be deleted. This can be fixed by using the client id instead of using MAC address. Will get this one changed in the next update.

**Comment by ShreyasZare** [comment]
Version 8.1 is now available that fixes this issue.
