### ISSUE TITLE
Zones public or domain public

### ISSUE THREAD

**Issue by GranGuorgeMC** [TechnitiumSoftware/DnsServer#387]
How to public the zones or the domain

Im using ubuntu 20.04

**Comment by ShreyasZare** [comment]
If you mean that you want to self host your domain name on the DNS server then you need to have a server with a static IP address to run the DNS server preferably a VPS.

The domain name's TLD must support creating "child" name servers. Like say if your domain is "example.com" then the child name server's domain can be "ns1.example.com". Not all TLDs support this but popular ones do like .com or .net. Check your domain's registrar's web portal to see if there is an option to configure child name servers.

Once you have both of these requirements confirmed, you can proceed to follow the steps below:
1. Change the "DNS Server Domain" in Settings > General section to the domain name you have chosen for the name server e.g. ns1.yourdomain.com. Its not really a requirement to do so as your server's domain name can be different from the one you plan to use for your hosted domain but, its is so that things remain consistent.

2. Create a zone for your domain name on the DNS server. Add all the records you want in the zone. Make sure that your zone's SOA record is the domain name you want to use as the child name server e.g. "ns1.yourdomain.com". Also, name sure the NS record has the same domain name. If you had used the same name in previous step then both these SOA and NS records will have the same domain name. Add an A record for "ns1.yourdomain.com" that points to the static IP address of your server.

3. Once you have confirmed that all records in the zone are added, you can now proceed to login to your domain's registrar account. In there, go into your domain's settings and find option to create child name servers. Use the same domain name that you used i.e. "ns1.yourdomain.com" and add your server's public IP address there.

4. Now in the same registrar's panel, find option to change the name servers. Remove any existing name servers and put in your name server address i.e. "ns1.yourdomain.com". Once you save this change, it may take few minutes or even an hour for the TLD zone to update the new name server records. When this new name server is updated, all new requests to resolve your domain name will start arriving to your DNS server and will show up in the stats on the dashboard.

It will be good to add a secondary name server too in case your primary server goes down for some reason. For this, you can create another server or use [this free secondary DNS service](https://ns-global.zone/).

Let me know if you have any queries.
