### ISSUE TITLE
DNSSEC validation when acting as recursive server?

### ISSUE THREAD

**Issue by ajp2k13** [TechnitiumSoftware/DnsServer#39]
Is is possible to make it validate DNSSEC signatures when in DNS-over-UDP/Recursive mode?

**Comment by ShreyasZare** [comment]
I would really like to add DNSSEC support but there is really no motivation to spend time to add it. The lack of motivation is due to the fact that DNSSEC deployment is negligible. 

Practically, nobody really uses DNSSEC. No major company like Google, Apple or Microsoft have DNSSEC enabled on their domain. Everyone relies on SSL/TLS and do not bother to deploy DNSSEC.

DNSSEC is validated only at recursive resolvers and end users never check for it. Thus its not really end-to-end and users implicitly trust DNS resolvers.

I may revisit this later and plan to add DNSSEC but, there is no plan as of now.

**Comment by ajp2k13** [comment]
I understand completely, worth a try though! :)
