### ISSUE TITLE
A reserved DHCP host lease overwrites and deletes a statically defined DNS host entry

### ISSUE THREAD

**Issue by besynnerlig** [TechnitiumSoftware/DnsServer#394]
**Expected behavior**
When I manually add a A record for a host in a zone, I expect the entry to persist in the zone file until I manually delete it.

**Actual behavior**
If a reserved DHCP lease for a host has been defined, any existing DNS host entry (including its comments) gets overwritten when the lease is initiated. When the DHCP lease eventually expires the DNS host entry in the zone file gets deleted.

**Information about the Issue**
Having the zone file dynamically updated is a nice feature but the behavior described above causes data loss. Host entries are just disappearing and I'll have to add them  again manually.

**Steps to reproduce the behavior**
- Optionally (set the DHCP scope lease time to some low value while testing)
- Add a host in a zone file with its name, type, TTL, IPv4 Address and a comment.
- Add a reserved lease in the DHCP scope entering Host Name, MAC Address, IP Address. Use the same host name as in previous step.
- Have the host accept that reserved DHCP lease.
- Notice that the host comment in the zone file is now empty.
- Turn off the host so that the DHCP lease expires.
- Notice that the the host entry for that host has now been lost and name resolution for that specific host has ceased working.
- Optionally (set the DHCP scope lease time back to original value)

**Comment by ShreyasZare** [comment]
Thanks for the detailed feedback. This is actually an expected thing to happen by design. Dynamic leases wont be able to overwrite DNS records but reserved leases do since when reserved lease is created, its often expected that it's DNS records are correctly updated so that any app using the services hosted on that server can access it. If the reserved lease didn't do that then people who expected the record to be overwritten will then see it as a bug.

There is no marker on the record that says if the record was manually added or was added by DHCP. Also, there can be case when the reserved lease is updated with another IP address and so the DHCP server has to overwrite existing DNS record to reflect the new IP address. Also, you can configure hostname for the reserved lease to make sure that the device's hostname when changed does not affect the DNS record being used.

I would recommend config changes to avoid such issues of records getting overwritten. The setup can have 2 separate zones, one for manual config that is used as a general zone like "name.corp", and the other which is used to dynamically update records via DHCP like "vlan1.corp". Say if you have a NAS on your network with dhcp with hostname nas1, it would create "nas1.vlan1.corp" record. You can now create a "nas1.corp" CNAME entry in your "corp" zone which points to "nas1.vlan1.corp". This way things are decoupled and there wont be issues with records getting overwritten.

**Comment by besynnerlig** [comment]
Thanks @ShreyasZare :clap: :thumbsup:

I've set up some redundancy in my home LAN for name resolution and DHCP. Recently I had only a single DHCP server and a single DNS server built into my router. Needless to say, one day when my router ceased working no hosts in my LAN could communicate with each other due to expired DHCP leases and non existing name resolution. I guess you can imagine what a havoc that was, nothing worked :sweat:

Now I have a double set of DNS servers and DHCP servers in my LAN residing on separate machines. The DHCP servers providing non overlapping address ranges of course to avoid conflicts. (The reserved leases do exist identical on both DHCP servers though but it shouldn't give me any problems). I've also set up [unbound](https://github.com/NLnetLabs/unbound) to be used by is a validating, recursive, and caching DNS resolver to be used by the Technituim DNS Server. (Nice combo BTW) All together this redundancy gives me the opportunity to perform maintenance (temporary turn off) one machine without causing a total mess. I'm very happy to finally have this redundancy in my home LAN. The Technitium DNS server is of course the first (highest priority) dns server configured for both my DHCP servers scopes.

Even though the Technitium DHCP server seems to handle out the main part of the DHCP leases in my home LAN I can not be sure. Sometimes the DHCP server in my router handles out a lease and that's when the DNS problems start to occur. This is when the host in the Technitium DNS server gets deleted (even though the host is actually online and has been assigned the proper IP, just by another DHCP server). Another serious situation occurs if I turn off the Technitium DNS server for some time so that multiple DHCP leases expires while the server is down. When restarting the Technitium DNS server again lots of server (they are dependent of each other in various ways... databases, MQTT and so on) and if the hosts have been deleted from the DNS zone file it will take some time for me to get things up and going again. I think you get the idea. I simply need my LAN server IP:s to be resilient, resolvable and persist between reboots.

I appreciate your kind help providing a possible solution using double zones but it won't work here since I've multiple DNS servers. 

For now, I've simply disabled the DHCP Zone, removed the current leases and once again added the lost hosts into my zone file. It means that I've actually only have one DHCP server left in my LAN (on my router) but it gives me some time to figure out a more permanent solution. I'll probably want to add another DHCP server for redundancy. And who knows, maybe Technitium DNS will add the possibility in the future to write protect specific host entries in the zone file either by a checkbox or by entering a specific string in the comment field. Thanks for reading my lengthy comment! I appreciate your work a lot!

**Comment by ShreyasZare** [comment]
Thanks for the detailed description of your setup. This issue you have is since you are running two instances of Technitium DNS Server with the built-in DHCP server on both of them. The built-in DHCP server is currently only capable of updating DNS records on the same DNS server its running with. The dynamic DNS update feature is planned which will allow any DHCP server to update the DNS records. This feature when available will cover the scenario that you currently have setup.

There is also plan to add clustering support to the DNS server which will be implemented in coming months. When the clustering feature is implemented, you will be able to manage two or more Technitium DNS server instances as a single cluster from a single web panel. All the zones and settings will be automatically synced across all the other instances. This includes DHCP scopes that will provide redundancy across the instances.

Right now, what you can do is configure the other DNS server instance with the secondary zones for the primary zones that you run on the first instance. This will keep all records sync between them automatically. The DHCP on the second instance still wont be able to update the zone since it can only update a primary zone. So, you will need to manually create records for your clients to make it work well.

The other option that can be done here is to configure a different primary zone for the second DHCP instance so that it can update it. Now, you can have a DNS entry for a device in one of the two different zones. You can make the one that works resolve using the Failover DNS app. You can add an APP record for the Failover app with the CNAME option and add both the domain names for the device in there. Configure the health check to check for a TCP port on the server which is expected to run. So, this APP record setup will return only the domain name which has the TCP port open. This setup is kind of complex but will work.

PS: Technitium DNS server is also validating, recursive, and caching DNS so you wont gain any additional benefit of forwarding requests further to Unbound.

**Comment by besynnerlig** [comment]
Thanks @ShreyasZare 

I'll consider your proposed solutions. I don't have 2 instances of Technitium DNS though. The other DNS and DHCP software is proprietary from the router manufacturer. I don't like it's GUI but it's stable and reliable.

> PS: Technitium DNS server is also validating, recursive, and caching DNS so you wont gain any additional benefit of forwarding requests further to Unbound

That's interesting and I will check it out further. I suppose that I can simply unset forwarder and Technitium DNS will query the root servers then. Sound very interesting really. Thanks!

**Comment by besynnerlig** [comment]
I close this issue. I know how it works now and I have set up a ISC DHCP server in a Debian LXC container. It won't do any dynamic DNS updates :smile: 

I've also tested to remove the forwarders and now the Technitium DNS server is now using the ROOT SERVERS to perform recursive name resolution which is what I want. Using unbound is indeed not necessary when the functionality is built into the Technitium DNS server. 

Thanks again @ShreyasZare and keep up the good work with this amazing software!
