### ISSUE TITLE
Strange records in cached zones

### ISSUE THREAD

**Issue by Globulopolis** [TechnitiumSoftware/DnsServer#40]
Today I found records listed below in cache. What's this?
```
[
  {
    "name": "zyzurjxdrbkn",
    "type": "A",
    "ttl": 0,
    "rData": {}
  }
]
```

and many more(see screenshot).
![screenshot-server-5380-2019 02 21-12-28-46](https://user-images.githubusercontent.com/740757/53158295-4fd1d000-35d4-11e9-89e8-d8eee2997286.png)

PS! I use no proxy and cloudflare forwarder.

**Comment by ShreyasZare** [comment]
This is a very old thing actually and is mostly due to Google Chrome (or Chromium) making weird DNS queries. I don't remember exact purpose of these requests but you may explore more on this by searching on it. I found a few pointers which you may like:

https://isc.sans.edu/diary/Google+Chrome+and+%28weird%29+DNS+requests/10312
https://productforums.google.com/forum/#!topic/chrome/hl0Knv7p4-4
https://bugs.chromium.org/p/chromium/issues/detail?id=47262
https://groups.google.com/a/chromium.org/forum/#!topic/chromium-discuss/F70-k_PGhEg
