### ISSUE TITLE
Cannot save settings on Windows host

### ISSUE THREAD

**Issue by mobiledork** [TechnitiumSoftware/DnsServer#403]
either from local dashboard or connecting from machine on same subnet.
![Screenshot_20220528-013115](https://user-images.githubusercontent.com/52812734/170817785-d0651251-d5c1-4c79-afb1-6cf89d860c20.png)

**Comment by ShreyasZare** [comment]
Thanks for the post. This error is coming since the Query Logs app is writing to the database file while you are trying to make the backup.

There are 2 options to fix this:
1. Edit the Query Logs app's config to set `enableLogging` to `false`, then take the backup, go back and set the option to `true` again. This will stop the app from logging data to the file while you do the backup.
2. The other option is to uncheck the `DNS Apps` option in the backup so that the error is avoided.
