### ISSUE TITLE
Domain blocking: stats reported in the UI for them but no actual blocking takes place?

### ISSUE THREAD

**Issue by ZzZombo** [TechnitiumSoftware/DnsServer#407]
For example, the domain `events.gfe.nvidia.com` is blocked according to my settings but the domain still resolves successfully:

```
> ping events.gfe.nvidia.com

Обмен пакетами с events.gfe.nvidia.com [185.136.68.145] с 32 байтами данных:
Ответ от 185.136.68.145: число байт=32 время=128мс TTL=55
Ответ от 185.136.68.145: число байт=32 время=129мс TTL=55
Ответ от 185.136.68.145: число байт=32 время=129мс TTL=55
Ответ от 185.136.68.145: число байт=32 время=129мс TTL=55

Статистика Ping для 185.136.68.145:
    Пакетов: отправлено = 4, получено = 4, потеряно = 0
    (0% потерь)
Приблизительное время приема-передачи в мс:
    Минимальное = 128мсек, Максимальное = 129 мсек, Среднее = 128 мсек
```

I have the following lists enabled:

```
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
https://dbl.oisd.nl/
http://localhost:5380/blocklist.txt
```

After I manually added the domain to the Blocked zone, it is no longer the case.

**Comment by ShreyasZare** [comment]
Thanks for the post. To check if a domain, the best tool is the DNS Client tab that is built-in to the DNS web console. Test the domain name there by querying This Server and see the results to confirm. You can also set the type to TXT to get a report that will explain why the domain is blocked.

On your computer, you can use `nslookup` instead of `ping` command. Use nslookup to query the DNS server with type TXT to get the report like mentioned above.

This type of test is recommended since DNS responses get cached at multiple levels so even if you get the domain blocked at the DNS server, your OS's cache will still have the old records and thus will make your ping command work,

Let me know if you need help interpreting the results.

**Comment by ZzZombo** [comment]
I think I figured it out. If configured to reply with `NXDOMAIN`, the OS (Windows 10) resorts to query the same domain with the `.local` suffix appended. Somehow it does get resolved in certain cases (don't know what is the pattern here though), but not all. I change the software to reply with `0.0.0.0`/`::`, and ever since blocking works correctly.

**Comment by ShreyasZare** [comment]
> I think I figured it out. If configured to reply with `NXDOMAIN`, the OS (Windows 10) resorts to query the same domain with the `.local` suffix appended. Somehow it does get resolved in certain cases (don't know what is the pattern here though), but not all. I change the software to reply with `0.0.0.0`/`::`, and ever since blocking works correctly.

Ya, the `.local` suffix is used for mDNS resolution over local network. But there are no chances for it to resolve a public domain name with `.local` suffix appended. There must be something other than that like the client being configured with secondary DNS server which is able to resolve the domain name.
