### ISSUE TITLE
Root DNS issue?

### ISSUE THREAD

**Issue by asterriya** [TechnitiumSoftware/DnsServer#409]
I did setup of Root DNS server list like it described here https://blog.technitium.com/2021/07/running-root-server-locally-on-your-dns.html but not sure if it's working like it must to. Because browserleaks show me DNS of my ISP, but I use DNS addresses from here https://www.iana.org/domains/root/servers, so it must show their IP's. Isn't it? Maybe there is a tool available to check setup?

**Comment by ShreyasZare** [comment]
Thanks for asking. The DNS leak tests are going to show you **your** IP address when you have the DNS server running as a recursive resolver. The root servers do not tell you the answer for DNS queries, they merely tell you who to ask next. The root servers also do not perform and kind or proxy for you to see their IP address in the leak tests.

Now that you are running a copy of root zone locally, the DNS server does not ask the root servers anything since its itself a root server now. The root zone copy tells the list of name servers for all the top level domains (TLDs). So, when you query for "google.com", your DNS server already knows the list of "com" name servers from the locally running root zone so it does not need to ask the actual root servers for it.

If you want to hide your IP address from the leak tests then you must configure the DNS server with forwarders. The forwarder server will then perform the lookup and return an answer so that your IP address does not show up on the leak tests.

**Comment by asterriya** [comment]
So how to test if I did set up properly because I don't see any improvement in latency test at all. And it starts to show DNS from my VPS where it placed. And this is confusing me that after set up nothing improved.

**Comment by asterriya** [comment]
Also, I'm interest how secure they are. Instead of DoH/DoT for example? Try to find infi about that, but fail.

**Comment by ShreyasZare** [comment]
> So how to test if I did set up properly because I don't see any improvement in latency test at all. And it starts to show DNS from my VPS where it placed. And this is confusing me that after set up nothing improved.

If you are running the DNS server as a recursive resolver on a VPS then you should see the IP address of the VPS server in your dns leak tests. If you still see your ISP's IP address then check your config to make sure that you have configured your VPS's IP address as the DNS server in your network.

If your network's DNS config is correct and you still see your ISP's IP address in dns leak test then it means your ISP is hijacking all outbound DNS requests so they are not actually reaching your DNS server running on the VPS. In that case you must configure DoT/DoH on your DNS server that you have on the VPS and configure your web browser to use that DoH server's URL. You can also run a local DNS server and configure your DNS server running on the VPS as the forwarder with DoT/DoH protocol so that your ISP cant hijack the requests.

**Comment by asterriya** [comment]
Yes, I see DNS of my VPS which, not DNS of my ISP. So my setup was right? Then why it doesn't add improvement? DNS latency still high with root. And when I choose public resolvers like DoH Google, it's helping me a lot. 

Also, I'm interest how secure they are. Instead of DoH/DoT for example? Try to find info about that, but fail.

**Comment by ShreyasZare** [comment]
> Also, I'm interest how secure they are. Instead of DoH/DoT for example? Try to find infi about that, but fail.

The recursive resolution works over UDP and is only secure if the domain name being resolved is DNSSEC signed. DNSSEC does not provide privacy though. Using DoT/DoH will give you privacy by hiding your traffic over the network.

If you configure DoT/DoH on your DNS server running on the VPS and configure a locally running DNS server with it as the forwarders then you will get privacy and security between your local DNS and the VPS DNS.

**Comment by ShreyasZare** [comment]
> Yes, I see DNS of my VPS which, not DNS of my ISP. So my setup was right? Then why it doesn't add improvement? DNS latency still high with root. And when I choose public resolvers like DoH Google, it's helping me a lot.
> 

When the DNS server does recursive resolution for "example.com", it has to first query root servers to get a list of com servers, then query com servers to get a list of example.com servers then query example.com servers to get the final answer. So, there are at least 3 queries involved to resolve the example.com domain name. Running a local root server just reduces the first query. So, you still need to make the other queries.

The time taken to resolve a domain thus depends on the time it takes for all the individual queries to resolve. Some name servers that host the domain name may not respond in time causing the DNS resolver to make retries and later switch to the next name server and try again. This is the reason why recursive resolution is not going to be fast to resolve domain names.

The reason why your ISP's DNS or other public DNS providers seem fast is just because they have a lot of users and someone has already made a request for the same domain name and has the answer cached thus you get the response faster.

**Comment by asterriya** [comment]
But I'm using caching stuff from TechnitiumDNS server with Root Servers, and it doesn't help still.

**Comment by ShreyasZare** [comment]
> But I'm using caching stuff from TechnitiumDNS server with Root Servers, and it doesn't help still.

Cache helps the second time you query for the same domain name. Just try the DNS Client tab on the web console to query for a domain with cache cleared and check the response time in the output. Try the query again and compare the response time.

**Comment by asterriya** [comment]
Yes, I did that. During 7 days running Root zone DNS I/F/A/I/K because they ping near 1-2 ms and turn on default settings in cache. And start from clear cache. And still it's slower after 7 days. Ping is good but page opening slower. But when I do the same settings with DOH, it's opening faster. I'm confused. But maybe I must try again? And I suppose that using root DNS servers zone only is not secure for my anonymity and my VPS IP can be blocked, right?

**Comment by ShreyasZare** [comment]
> Yes, I did that. During 7 days running Root zone DNS I/F/A/I/K because they ping near 1-2 ms and turn on default settings in cache. And start from clear cache. And still it's slower after 7 days. Ping is good but page opening slower. But when I do the same settings with DOH, it's opening faster. I'm confused. But maybe I must try again? And I suppose that using root DNS servers zone only is not secure for my anonymity and my VPS IP can be blocked, right?

If you can ping root servers with 1-2 ms delays then you are not really pinging them but there is some other server very near in your network that is responding to those pings.

Also, DNS performance cannot be measured by ping or "page opening slower" since DNS is only responsible to give you the IP address. The other delays you see is due to network congestion or other issues.

Running local root zone will expose your VPS's IP address so if you are concerned about privacy such that you dont want to disclose even your VPS's IP address then use a public DNS provider as forwarder (make sure to remove root zone then). Your VPS IP address is not going to get blocked just by running a recursive resolver.

**Comment by asterriya** [comment]
Ok, if it's safe to use DNS root servers, then I will try again. I'm used DOH points only because afraid of blocking my VPS IP.

So I can use root servers that can't be pinged too?

**Comment by ShreyasZare** [comment]
> Ok, if it's safe to use DNS root servers, then I will try again. I'm used DOH points only because afraid of blocking my VPS IP.
> 
> So I can use root servers that can't be pinged too?

Ping, which uses ICMP protocol, has nothing to do with DNS. Just use the root server addresses given in the blog post to create the secondary zone.

**Comment by asterriya** [comment]
I will try again and hope that it will help to me. With default settings.

**Comment by asterriya** [comment]
Also, I must say that version 8.1 worked much better and more smoothly. And less resolver errors was there. Now I get almost 5% of errors through DNS resolvers like Google DoH with default settings. So I think maybe something wrong in code? Maybe that's why it's get slower even with DoH points? DNSSEC turned off.

**Comment by ShreyasZare** [comment]
The one possible reason why you may be seeing websites loading slow or fast can be due to your VPS being in a different geo location than your actual geo location. So you will get IP addresses for CDN networks that are near to your VPS region.Whereas when you use Googlr DoH, you will get CDN IP addresses that are near to your actual geo location.

**Comment by asterriya** [comment]
No, I thought about that reason. But before when version was 8.1 with the same config and same data works much faster.

**Comment by ShreyasZare** [comment]
There is not much difference with v8.1 other than some bug fixes that wont affect performance in any ways.If you disable DNSSEC then there will be some difference since DNSSEC validation takes a few more queries to complete the resolution.

**Comment by asterriya** [comment]
That's why I disabled it. Then it's so strange. I will try to play with configurations then.

**Comment by asterriya** [comment]
Yes. I was right. Something wrong with TechnitiumDNS. Just re-installed OS Debian 10. Trying to install on fresh OS, and it doesn't work at all. Then I installed AdGuard Home, and it's working perfect with fast speed as before. So try to check code or fix something because it's not only for me but for another guy the same error.

**Comment by ShreyasZare** [comment]
> That's why I disabled it. Then it's so strange. I will try to play with configurations then.

Disabling DNSSEC is your call and not recommended since that will stop validating signed domain names.

**Comment by ShreyasZare** [comment]
> Yes. I was right. Something wrong with TechnitiumDNS. Just re-installed OS Debian 10. Trying to install on fresh OS, and it doesn't work at all. Then I installed AdGuard Home, and it's working perfect with fast speed as before. 

You cannot compare Technitium DNS server working as a recursive resolver with AdGuard which is a DNS proxy. Recursive resolver performance depends upon your network as well as the name servers of the domain being resolved. If you just configure a public DNS provider like Google/Cloudflare as a forwarder then you will get similar performance that you get with AdGuard.

> So try to check code or fix something because it's not only for me but for another guy the same error.

You need to define the issue clearly, post any error messages, or steps to reproduce the issue. Then only it can be acknowledged and fixed.
