### ISSUE TITLE
X-Real-IP vs X-Real-Ip : IIS as proxy not being logged correctly

### ISSUE THREAD

**Issue by shawnkhall** [TechnitiumSoftware/DnsServer#410]
I'm using IIS to proxy requests to DoH on my Technitium DNS Server 8.1.2. In versions prior to 8.0, without any adjustments to the Server Variables block within the rule in the URL Rewrite module, requests logged the IP correctly in the Technitium log as [HTTPS] values. Since 8.0 it is only recording 127.0.0.1. I'm going to cover everything I've done, just to make sure that you understand the issue. 

Per the docs:

     When using a reverse proxy with the DNS-over-HTTP service, you need to add X-Real-IP header 
     to the proxy request with the IP address of the client to allow the DNS server to know the real IP 
     address of the client originating the request. For example, if you are using nginx as the reverse 
     proxy, you can add proxy_set_header X-Real-IP $remote_addr; to make it work.

I'm using IIS so the process should be adding `X-Real-IP` with a value of `{REMOTE_ADDR}` to the `Server Variables` block (after adding `X-Real-IP` to `allowedServerVariables` in `applicationHost.config`). I've done that. I restarted IIS and the DNS server and it's still recording 127.0.0.1. I tried `X-Forwarded-For`, just in case, and still no joy. 

I then removed those and modified the `ARR Cache`, `Proxy Settings`, `Custom Headers`, `Preserve client IP in the following header`, and set that to `X-Real-IP`, then recycled everything. Still no joy.

I then tried using a different URL on the rewrite so I could capture the request headers to make sure they're really doing what they're supposed to with the ARR cache proxy rules. They're not. It turns out that the header is actually being written as `X-Real-Ip` instead of `X-Real-IP` . It turns out IIS reformats added headers to Hyphenated-Title-Case regardless of the case they're created in the configuration files.

This is an issue because the code at [DnsServer.cs](https://github.com/TechnitiumSoftware/DnsServer/blob/master/DnsServerCore/Dns/DnsServer.cs) on line 676 only tests for the case-sensitive `X-Real-IP`. Can you please replace the existing code with the code below (untested but should be close) in order to handle accurate logging via proxy on IIS? I've also added parsing for `X-Forwarded-For`, since that is the default behavior on IIS and most other proxies.

```
string xRealIp = httpRequest.Headers["X-Real-IP"];
if (IPAddress.TryParse(xRealIp, out IPAddress address))
{
	//get the real IP address of the requesting client from X-Real-IP header set in nginx proxy_pass block
	remoteEP = new IPEndPoint(address, 0);
}
else
{
	xRealIp = httpRequest.Headers["X-Real-Ip"];
	if (IPAddress.TryParse(xRealIp, out address))
	{
		//get the real IP address of the requesting client from X-Real-Ip header set in IIS proxy
		remoteEP = new IPEndPoint(address, 0);
	}
	else
	{
		xRealIp = httpRequest.Headers["X-Forwarded-For"];
		if (IPAddress.TryParse(xRealIp, out address))
		{
			//get the real IP address of the requesting client from X-Forwarded-For header set in many proxies
			remoteEP = new IPEndPoint(address, 0);
		}
	}
}
```

**Comment by ShreyasZare** [comment]
Thanks for the feedback. In the `httpRequest.Headers["X-Real-IP"]` call, the key part is [compared case insensitive](https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.namevaluecollection?view=net-6.0#remarks) so it does not matter what the case of the header was in the request.

You can test it out using this curl command (update the DoH url for your setup): 
`curl -H "accept: application/dns-json" -H "x-real-ip: 1.1.1.1" "http://localhost:8053/dns-query?name=google.com"`

With this curl test, I can see the correct IP `1.1.1.1` being logged.

The `X-Forwarded-For` header is deliberately not implemented since the value is a list of comma separated IP addresses for each HTTP intermediary between the client and the server. Thus without additional configuration that tells the DNS server the IP address for the reverse proxy, it becomes possible to spoof the header to write a fake IP address into the logs.

In your case, it is possible that the header is not being sent. Try running Wireshark for the `Adapter for loopback traffic capture` that will show the DoH request between IIS and the DoH server on port 8053 in clear text. Let me know what you find there.

**Comment by ShreyasZare** [comment]
I hope this issue is fixed with config changes. Reopen this issue if you still have the same problem.
