### ISSUE TITLE
Please let us to increase blocklists cache time to one month

### ISSUE THREAD

**Issue by rustforfuture** [TechnitiumSoftware/DnsServer#431]
Hello

My internet connection has limited speed (very low somehow that I can't say for privacy reasons)

May you please let us to cache blocklists for one month or more?

This will be great because i use several big blocklists and their overall size has become big, so updating them every week will cause my internet to be unable yo use every week for several hours.

Thank you very much

Also a question, what server will do if proxy server won't work or it can't connect to dns server?

I ask this because probably many internet shutdowns (making it just a local countywide network) is predictable here, so i wanted to know, may you make the server to work and Reply with its cache recursively if it find this kind of situations and won't delete the cache in this situations until the user makes changes itself? (Specially blocklists)

This will be great for such locations like where i live.

Thank you

**Comment by ShreyasZare** [comment]
Thanks for the post. I think I will add an option to stop the automatic update of block lists. So, you can manually trigger the update using the Update Now button when needed. 

For now, what you can so is download all the block lists manually and keep them in the `www` folder that you will find in the DNS server's config folder. You can then use the `http://localhost:5380/block-list-example.txt` path for each of them in the Settings so that the DNS server downloads them from the local web server that the DNS web panel uses. When you want to update the block lists then manually download the files again and replace them with the old files in the `www` folder.

If you are using a proxy server such that the DNS server uses the proxy server and the proxy server requires the DNS server then it will cause a dependency loop which will fail to work. You will need to change the config to something else to make it work for your scenario.

**Comment by ShreyasZare** [comment]
> And also thank you for that local download guide.
> 
> But won't it get in conflict with proxy server setup?

You can configure the Proxy Bypass List by adding `loopback` into it so that the local request wont use proxy server.

> Thank you very much. You are a great person.

You're welcome.

**Comment by ShreyasZare** [comment]
New version 9.0 now allows you to set the block list update interval to `0` which will disable automatic update.
