### ISSUE TITLE
Hi there is an error on the mac address changer

### ISSUE THREAD

**Issue by cqdcc** [TechnitiumSoftware/DnsServer#435]
![image](https://user-images.githubusercontent.com/109258396/178885936-c06d2701-1aa4-44bc-b287-399daddf4739.png)
I tried checking for updates but it is up to date.

But sometimes it opens but there is nothing.

**Comment by ShreyasZare** [comment]
Technitium MAC Address Changer is not in active development since many years now. There are few known issues that come up on some installations which includes the issue you posted. There is a plan to rewrite TMAC with .NET that will fix all known issue but there is no timeline known for the project yet.

Closing this issue since its not related to the DNS server project, If you have any more queries regarding TMAC then do post it on reddit.com/r/technitium or send an email to support@technitium.com.
