### ISSUE TITLE
RFC7766 delay time is too long

### ISSUE THREAD

**Issue by thb007** [TechnitiumSoftware/DnsServer#437]
I want to test whether the DNS Server supports RFC7766. Through the command test, I found that it is supported, but the response received time is too long. The screenshot shows that 4000ms is DNS Server, and 48~58ms is google dns
The test command is the default one that comes with this project https://github.com/IrineSistiana/mosdns

![8~P@}AVGCG%3J 2R1` A1D](https://user-images.githubusercontent.com/17548936/180228898-4b0e3e0d-7f74-4eea-b502-9d11f1fd3480.png)

**Comment by ShreyasZare** [comment]
Thanks for the post. From the response latency of 4000 ms it seems that Technitium DNS server has not yet resolved the domain in the request and is responding with ServerFailure RCODE after the default 4000 ms time which is configured in Settings > General section as Client Timeout. You can test this out by running tcpdump and inspecting the response. 

Also check the DNS logs from the web panel to see what response or error is being logged. Do enable query logging and test again so that the logs show you the responses.

**Comment by thb007** [comment]
The rfc7766 detection command only detects whether the DNS of the TCP protocol supports rfc7766. This command does not resolve the domain name, so I don't see any useful information in the log

**Comment by thb007** [comment]
You can also test through this project https://github.com/IrineSistiana/mosdns , the test command is:
'''
/ mosdns probe pipeline  tcp://127.0.0.1:53
'''

**Comment by ShreyasZare** [comment]
> The rfc7766 detection command only detects whether the DNS of the TCP protocol supports rfc7766. This command does not resolve the domain name, so I don't see any useful information in the log

The tool will have to make queries to resolve some domain name to work. Anyways, will check it once.

**Comment by ShreyasZare** [comment]
Just tested here and its working as expected, see screenshots below for the mosdns command:

![image](https://user-images.githubusercontent.com/10008172/180442079-3c5003e7-5621-4f03-bbf1-12a17673c07d.png)

Wireshark capture for the same command:

![image](https://user-images.githubusercontent.com/10008172/180442142-102586ca-4bfa-424b-b973-236e078a22dc.png)

In your case, due to network issues its taking a lot of time resolving those random .com domain names which results in the DNS server returning ServerFailure after waiting for 4000 ms.

**Comment by thb007** [comment]
> Just tested here and its working as expected, see screenshots below for the mosdns command:
> 
> ![image](https://user-images.githubusercontent.com/10008172/180442079-3c5003e7-5621-4f03-bbf1-12a17673c07d.png)
> 
> Wireshark capture for the same command:
> 
> ![image](https://user-images.githubusercontent.com/10008172/180442142-102586ca-4bfa-424b-b973-236e078a22dc.png)
> 
> In your case, due to network issues its taking a lot of time resolving those random .com domain names which results in the DNS server returning ServerFailure after waiting for 4000 ms.

I use unbound to test rfc7766. The result is that the unbound time is relatively low, but the DNS server time is relatively long. Is this because there is no cache?

**Comment by ShreyasZare** [comment]
> I use unbound to test rfc7766. The result is that the unbound time is relatively low, but the DNS server time is relatively long. Is this because there is no cache?

It depends if the DNS server is configured with forwarders or is running as recursive resolver. Also depends on your network/ISP when running as a recursive resolver.

**Comment by thb007** [comment]
时。
 


> > I use unbound to test rfc7766. The result is that the unbound time is relatively low, but the DNS server time is relatively long. Is this because there is no cache?
> 
> It depends if the DNS server is configured with forwarders or is running as recursive resolver. Also depends on your network/ISP when running as a recursive resolver.

ok, thanks for answering patiently
