### ISSUE TITLE
DoH Redirecting to hostname

### ISSUE THREAD

**Issue by libDarkstreet** [TechnitiumSoftware/DnsServer#438]
DNS over HTTPS redirects to the hostname. This is a problem because, if the service is used with reverse proxy, users will be redirected to an unreachable hostname. 

Couldn't you just return a 400 http error code?

**Comment by ShreyasZare** [comment]
Thanks for the post. The redirection is done so that anyone trying to access the DoH url directly will see the html page that tells how to use it. The DoH service does not know the domain name being used by the reverse proxy so it uses the domain given in the [host header](https://github.com/TechnitiumSoftware/DnsServer/blob/master/DnsServerCore/Dns/DnsServer.cs#L844) of the request to redirect. 

If you manually configure your reverse proxy to set a host header with the domain name being used by it then the redirection will work as expected.

**Comment by libDarkstreet** [comment]
Thanks for the reply!

That was my thought too but unfortunately it didn't work.

Even though the host header was there in the proxy, it didn't redirect to the domain it was requested from but to the hostname the docker was using.

**Comment by ShreyasZare** [comment]
I just tested with nginx on my setup with `proxy_set_header Host $host;` and its working as expected. Which reverse proxy are you using?

**Comment by libDarkstreet** [comment]
I also used nginx with the following config:

```
proxy_http_version                 1.1;
proxy_cache_bypass                 $http_upgrade;

proxy_set_header Upgrade           $http_upgrade;
proxy_set_header Connection        $connection_upgrade;
proxy_set_header Host              $host;
proxy_set_header X-Real-IP         $remote_addr;
proxy_set_header Forwarded         $proxy_add_forwarded;
proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host  $host;

proxy_connect_timeout              15s;
proxy_send_timeout                 15s;
proxy_read_timeout                 15s;
```

I'll try it again soon, maybe I've misspelled something.

**Comment by libDarkstreet** [comment]
Apparently it was my fault. Sorry to bore you with this!
