### ISSUE TITLE
Server hangs on opening highly populated Zone

### ISSUE THREAD

**Issue by itsKV** [TechnitiumSoftware/DnsServer#44]
When we open zone page, say _.com_ zone from _Blocked Zone_ page, as that zone is highly populated, web page goes non-responsive for more than 40-50sec rendering the page. (see below image)

![Untitled1](https://user-images.githubusercontent.com/22906069/56722866-83acab80-6765-11e9-9a0a-9e9aead623f7.jpg)

After some time web page changes as follows..

![Untitled2](https://user-images.githubusercontent.com/22906069/56722927-9f17b680-6765-11e9-93b5-0f625a66088b.jpg)

Web page remains as in above image for more than 2-3 mins. 
Meanwhile, until page becomes responsive again, server doesn't serve any DNS queries. 

Seems server process overloads server system resources rendering zone contents on web page.

We may solve this issue by offering page-number-wise display (prev-next) (say, only 50 contents per page) for zone contents.

> Test server - Windows 10 pro, i5-7th gen, 16gb RAM

**Comment by ShreyasZare** [comment]
Thanks for the feedback. 

True that there are too many entries for nodes like .com in the Blocked zone. However, its not the DNS Web Service that is getting non-responsive but the web browser. Web browsers are not really good at loading too many items of data into the DOM for display. 

In fact, when your browser is stuck loading the data, you can use another browser and see that the DNS Web Service is responding well. Also, the main DNS Server is running on different ports and using separate threads to serve requests and is not in any way dependent on the DNS Web Service.

When the browser is stuck while it renders the page, the DNS Server is working well and you test it using the nslookup command. Do try running 'nslookup google.com 127.0.0.1' when the browser is stuck and let me know the feedback.

I am exploring ways to have a better UI to browse all the zones to fix the browser stuck issue caused due to too many entries to display. I have added the Browse button for the same reason to allow you to jump to a known domain to avoid getting the browser stuck.

Do post any more data that you have on this issue here.

**Comment by ShreyasZare** [comment]
You may also find different results if you use Chrome instead of Firefox. Firefox takes a lot of time while Chrome is a bit better at rendering the same data.

**Comment by itsKV** [comment]
Yes, true. It serves nslookup while stuck on FF.
Also, Chrome renders zone page faster than FF.
