### ISSUE TITLE
[Question] How to configure network to use DHCP?

### ISSUE THREAD

**Issue by zpxp** [TechnitiumSoftware/DnsServer#446]
How to configure my network to use Technitium as the DHCP server? 

What settings do i need for the router ip; DHCP server ip; gateway and subnets?

Someone pls help

**Comment by ShreyasZare** [comment]
Thanks for the post. I am assuming that you are setting this for your home network and have a wifi router already running.

Firstly, you need to configure the server that is running Technitium DNS server with a static IP address. You can login to your router's web panel and find out the IP address range being used and also the IP address of your router. If your router's IP is 192.168.1.1 then you can use something like 192.168.1.2 as the static IP address of your server. The subnet mask will be 255.255.255.0 and the gateway IP address will be the IP address of your router.

Next, you need to configure the Technitium DHCP server's scope with the IP address range that you already on your network. Use that same network range with your DHCP server's scope eg. start address as 192.168.1.1, end address as 192.168.1.254, subnet mask as 255.255.255.0, router address as the IP address of your router, and the DNS Servers as the IP address of the server which is running the DNS server. You can then exclude first 10 IP addresses in the scope's exclusion options so that those IP addresses are not allocated to other devices and will be available for you to assign statically for any device if needed in future. Check out the config of the default scope that exists to get an idea. In the scope settings, the Router IP will be your wifi router's IP address.

Once you have your DHCP scope configured, enable it and login to your router's web panel and disable the router's DHCP server. Only one DHCP server must be active on a LAN network to avoid config issues. Now any device that connects to your network will get its IP address leased from the Technitium DHCP server.

**Comment by zpxp** [comment]
Thanks, Im running it in docker so I had to open the ports as well. To get computers to find the DHCP server tho I had to set DHCP relay in the router to the sever.

**Comment by zpxp** [comment]
I also had to untick the "Use This DNS Server" option and manually specify the server address as it was using the docker container IP as the DNS I think.

**Comment by ShreyasZare** [comment]
> Thanks, Im running it in docker so I had to open the ports as well. To get computers to find the DHCP server tho I had to set DHCP relay in the router to the sever.

When you have DHCP server deployed with docker, you need to configure the docker container to use [host network mode](https://github.com/TechnitiumSoftware/DnsServer/blob/master/docker-compose.yml#L7-L8). This is required so that the DHCP server can receive the broadcast requests that DHCP clients send.

Once you have the container configured correctly you wont require the DHCP relay agent running on your router.
