### ISSUE TITLE
Some issues with the Enable Serve Stale menu

### ISSUE THREAD

**Issue by thb007** [TechnitiumSoftware/DnsServer#448]
If this option is enabled, for DDNS domain names, if the ip has been updated, the ip resolved by the ddns domain name will still be the old ip value.

**Comment by thb007** [comment]
For the above question, how can the DnsServer program update the ip corresponding to ddns in time?

**Comment by ShreyasZare** [comment]
Thanks for the post. The serve stale feature will cause the DNS server to return stale/old IP only when the domain fails to resolve in 1800 ms, meanwhile the DNS server keeps trying to resolve the domain main in background. In such a case, the stale/old IP is served with a TTL of 30 seconds so that the client's cache expires soon and gets the new IP if the background process completed the resolution by then.

In case when you have serve stale disables, the DNS server will just return a Server Failure response and will cause an error in client. If the client has a retry mechanism then it will try again to resolve the domain.

**Comment by thb007** [comment]
> Thanks for the post. The serve stale feature will cause the DNS server to return stale/old IP only when the domain fails to resolve in 1800 ms, meanwhile the DNS server keeps trying to resolve the domain main in background. In such a case, the stale/old IP is served with a TTL of 30 seconds so that the client's cache expires soon and gets the new IP if the background process completed the resolution by then.
> 
> In case when you have serve stale disables, the DNS server will just return a Server Failure response and will cause an error in client. If the client has a retry mechanism then it will try again to resolve the domain.

ok ，thanks
