### ISSUE TITLE
Can't make Block Page app work

### ISSUE THREAD

**Issue by EHRETic** [TechnitiumSoftware/DnsServer#459]
Hi there,

Maybe I don't understand how this is supposed to work but as far as I understand, this app would add to Technitium the capability to serve a custom blocking page from the server itself. 

If I am wrong, well... this should be clearer in the information given that it is not possible😊

If not, so lets say I have my DNS server, IP 192.168.1.1. web console ports are 80 & 443 (with redirect). It's a dedicated Technitium instance using TLS certificates I generate with my own CA - this part works very well.

In the blocking setting, I'll give the custom IP address 192.168.1.1 but, the Blocking Page settings are somewhat "obscure":
```
{
  "webServerLocalAddresses": [
    "192.168.1.1",
    "::"
  ],
  "webServerUseSelfSignedTlsCertificate": false,
  "webServerTlsCertificateFilePath": "/etc/dns/cert/mycert.pfx",
  "webServerTlsCertificatePassword": "mycertpass",
  "webServerRootPath": "wwwroot",
  "serveBlockPageFromWebServerRoot": false,
  "blockPageTitle": "Website Blocked",
  "blockPageHeading": "Website Blocked",
  "blockPageMessage": "This website has been blocked by your network administrator."
}
```

I'm not sure about **webServerRootPath** setting but I would assume if **serveBlockPageFromWebServerRoot** option is set to false, this would not be used anyway, even if it doesn't exist.
This setup redirects me to Technitium login mask whenever I try a blocked website and doesn't give the information that website has been blocked.
What am I doing wrong here?

Thx in advance for the help 😉

**Comment by ShreyasZare** [comment]
Thanks for the post. The Block Page app is a web server in itself which will listen on the specified `webServerLocalAddresses` for port 80 and 443. Since you already have both of those ports configured for the DNS web console, the app must be failing to listen on those ports. Check the logs to see if there is any error logged to confirm.

With this setup, when you visit a blocked website, the IP address that you have configured in the blocking settings will be returned and the web browser is going to use port 80 (HTTP) or port 443 (HTTPS) so it will get served with the Technitium DNS login page on those ports.

So, you just need to switch the DNS web console ports to the default 5380 (HTTP) & 53443 (HTTPS) so that the Block Page app can listen on those ports and serve the block page message. 

Rest of the app's config looks fine. The `serveBlockPageFromWebServerRoot` when set to false will return the messages from the config as html page. If you set the `serveBlockPageFromWebServerRoot` to true then the index.html page from the wwwroot at the app's folder will be served which you can modify as per your requirements.

**Comment by EHRETic** [comment]
Hi there,

Yep I tested and it worked but I'd love to find a way to have something more "integrated" that would not display a certificate error.
But I don't know how to achieve that, if ever possible.

Aaaanddd, as usual, you support ist perfect! 👌😉

**Comment by ShreyasZare** [comment]
Thanks for the compliments.The only way to not get cert error is to install the cert on each client device which is feasible only on local networks.

**Comment by ShreyasZare** [comment]
Closing this issue. Do reopen if needed.
