### ISSUE TITLE
[Feature Request] Inbuilt HTTPS support

### ISSUE THREAD

**Issue by itsKV** [TechnitiumSoftware/DnsServer#46]
Can we have inbuilt HTTPS support for server (self signed and/or third party) ? 
This will help to serve admin dashboard over HTTPS, and can also have onboard DoH/DoT support.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. 

The DNS Web Service relies on a low level HTTP web server (HttpListener) which supports SSL only on Windows platform. And since the software is aimed to work on all platforms, its not feasible to add SSL support to the web console. Its recommended to use an SSL Terminating reverse proxy (like IIS on windows or nginx on linux) to achieve HTTPS support for the web console.

There is already DoT/DoH support with TLS. For DoH, the DNS Server has a built in web server written from scratch that uses SslStream to provide the support for the DoH protocol. The built in web server supports only DoH requests and is not a general purpose implementation that can be used for the web console. While, DoT is just an TLS tunnel over DNS-over-TCP, its too implemented using SslStream. Both the DoT/DoH services already support TLS and you can use them with an .pfx certificate.

**Comment by itsKV** [comment]
Kindly provide detailed documentation for how we can configure DoH/DoT from admin console. 
Your blog [here](https://blog.technitium.com/2018/06/configuring-dns-server-for-privacy.html) only shows back-end configuration for server. Nothing is explained for front-end configuration.(i.e how to set following configuration)
![Untitleda](https://user-images.githubusercontent.com/22906069/56879484-90d3de00-6a76-11e9-8200-f50b530c3dc8.jpg)

**Comment by ShreyasZare** [comment]
I will be adding an Help Topics section on the DNS Server page and also have added link in the web console about section. This feature configuration details will get covered in there. Expected release for help topics will be a couple of weeks.

**Comment by itsKV** [comment]
Thanks.

**Comment by ShreyasZare** [comment]
After a lot of delay, the documentation is now available in this blog post: [How To Host Your Own DNS-over-HTTPS And DNS-over-TLS Services](https://blog.technitium.com/2020/07/how-to-host-your-own-dns-over-https-and.html)
