### ISSUE TITLE
DHCP: Reservations

### ISSUE THREAD

**Issue by djarbz** [TechnitiumSoftware/DnsServer#461]
Please allow us to create reservations outside of the starting and ending address.
I have a scope where I only need DHCP for a few hosts and most others will be reservations.
In this case I would like to make .250-.254 to be DHCP and the rest to be reserved.
As of now, I need to make an exclusion for .1-.149.

**Comment by ShreyasZare** [comment]
Thanks for the post. Scope start and end address is used to identify which scope to select so having reservation outside of it will not work even if its allowed. 

Using exclusions is the correct way to do that since the option exists exclusively for this purpose.

Another option is to make 2 scopes, one which is used only for reserved leases and does not do dynamic allocations while the other one that only does dynamic allocations. Using exclusions is the better way though.

**Comment by djarbz** [comment]
The exclusion way works, I guess I am just used to the scope being defined by the subnet mask rather than the start/end address.
