### ISSUE TITLE
[Feature Request] DHCP Proxy

### ISSUE THREAD

**Issue by micush** [TechnitiumSoftware/DnsServer#462]
Hi,

In addition to the DHCP server, it would be nice to also include a DHCP Proxy/helper/forwarder as well. The two a mutually exclusive. If the DHCP server is active then the forwarding is disabled. If the forwarding is active then the DHCP server is disabled. 

That way we can either serve DHCP requests directly or if need be forward them on to another DHCP server for processing.

Thanks and Regards,
micush

**Comment by ShreyasZare** [comment]
Thanks for the post. The thing you are asking for is DHCP Relay Agent which is usually available in routers. Router is the proper place to have a DHCP Relay Agent since it can serve one or more networks and then route the DHCP requests to the DHCP server on another network. So having a DHCP Relay Agent bundled with the DNS server wont be actually useful.

**Comment by micush** [comment]
Hi. You are right. However, it can also be installed on a server to accomplish the same thing. Right now I install and configure isc-dhcp-relay and don't define any DHCP scopes in TDS to prevent the DHCP server from starting in order to accomplish this task. But it would be nice to not have to do this and to be able to configure it all from the same GUI.

**Comment by ShreyasZare** [comment]
Implementing DHCP Relay Agent is extremely simple in code, but the config you have to do with any existing relay agent is quite simple too - just 2 parameters, DHCP server IP and interface to listen. Relay agent is also a configure-once-and-forget kind of thing since you will need to update config rarely like only if your DHCP server changes or you add another network. Which is why I think it wont make it any better to have a GUI option available. If many people require it then I can think of adding it.

**Comment by micush** [comment]
This is also correct. But, since the two services conflict by their very nature, it's quite simple to forget about one and have the other one step on it's toes and then have to figure out why DHCP isn't working. You are right that it may simply be a 'me' thing in my situation, but not having to worry about two different applications that essentially do the same thing would be helpful.

**Comment by ShreyasZare** [comment]
The built-in DHCP server does not start by default and it starts only when at least one scope is enabled. If you disable the last scope then the DHCP server stops. So, there are no ways both the server and relay have a conflict unless you have a scope enabled.
