### ISSUE TITLE
Run DNS Server as recursive and root

### ISSUE THREAD

**Issue by ChristoffBo** [TechnitiumSoftware/DnsServer#469]
Hi,

Just wanted to ask is it possible to run 1 server as a recursive and as root?

as in to run the following: https://blog.technitium.com/2021/07/running-root-server-locally-on-your-dns.html

on one server and not two?

kind regards

**Comment by ShreyasZare** [comment]
Thanks for asking. Yes, its possible to run root in the same single instance that you use as recursive resolver but its highly not recommended for security reasons.

The root secondary zone is synced without DNSSEC validation. So, its possible if there is an on path attacker on your network to hijack a zone transfer request and modify DNSSEC related records. Such an attack will then allow the attacker to spoof valid DNSSEC responses. This attack works since the DNS server fully trusts locally running authoritative zones and thus will use the altered root zone records as trusted one.

When root secondary zone is running in a separate instance (as recommended in the blog post), the main instance where you perform recursive resolution will do DNSSEC validation checks for each query it sends to the root secondary zone. So any such attack as described above will fail due to DNSSEC validation.

**Comment by ChristoffBo** [comment]
Thank you, yes as you know I am running mine a bit differently as an Addon, i can load two instances of Technitium, but cannot get them to communicate to each other. I can however get the secondary to pull down the root zone.

I think it has to do to the fact that I cannot build them as you showed with the IP addresses of 127.0.0.1 and 127.0.0.2.

I also wanted to ask, since both instances has port 53 open all my dns queries seems to root through both now as they are sitting on the same local address of *.*.*.100. So i guess if i wanted one to be root and recursive I just have to build the root zone on my primary? I changed the port 53 on my secondary to something different but then my primary will not accept the ip as it seems to only want the ip and not an ip with a port "*.*.*.100:5335

**Comment by ShreyasZare** [comment]
The blog post instructions were tested in both Linux and Windows, and with docker and it works without issues. It could be some other issue in your setup that caused it to not work as expected.

Since both the DNS server instances listen on different IP addresses, so there is no issue with using same port numbers. I am not sure why you cannot configure them to use the `127.0.0.1` and `127.0.0.2` loopback addresses since it works on all platforms pretty well. If you use `0.0.0.0` with port 53 for any one of the instance or have another processing using it then it will cause a conflict with the port number. This is why you have to use specific IP addresses to listen on for port 53.

If you can share your config details then I can help with fixing it.

**Comment by ChristoffBo** [comment]
Hi thank you, yes it seems the way Homeassistant is built will not allow for this.

But thank you and again awesome product.

**Comment by ShreyasZare** [comment]
You're welcome. Anyways, running root zone locally is only useful for large networks where you have many clients using the DNS server. For small networks, it does not provide much benefit but adds complexity in configuration and maintenance.

**Comment by ChristoffBo** [comment]
Just for interest sake how would you run the root zone on a primary server for recursion? I do understand the security implications. Would just be interesting to no

Christoff Bothma
Sent From Mobile
________________________________

**Comment by ShreyasZare** [comment]
> Just for interest sake how would you run the root zone on a primary server for recursion? I do understand the security implications. Would just be interesting to no

Its quite easy, just add the root zone as secondary zone and its done.

**Comment by ChristoffBo** [comment]
Should i still have forwarders active on the primary server?

**Comment by ShreyasZare** [comment]
> Mmm dit that then I start getting servail errors, perhaps that is the same reason I get the serfail errors when running two servers.

ServerFailure is a very generic error code that is used for everything. You need to check the logs from DNS web panel to find out what actually went wrong.

**Comment by ShreyasZare** [comment]
> Should i still have forwarders active on the primary server?

If you add a root zone then forwarders get ignored since local authoritative zones have highest priority.

**Comment by ChristoffBo** [comment]
Hi,


Metadata": {
    "NameServer": "technitium (127.0.0.1)",
    "Protocol": "Tcp",
    "DatagramSize": "139 bytes",
    "RoundTripTime": "1.64 ms"
  },
  "EDNS": {
    "UdpPayloadSize": 1232,
    "ExtendedRCODE": "ServerFailure",
    "Version": 0,
    "Flags": "None",
    "Options": [
      {
        "Code": "EXTENDED_DNS_ERROR",
        "Length": "88 bytes",
        "Data": {
          "InfoCode": "NetworkError",
          "ExtraText": "k.gtld-servers.net (192.52.178.30) returned RCODE=ServerFailure for Takealot.com. A IN"
        }
      },
      {
        "Code": "EXTENDED_DNS_ERROR",
        "Length": "2 bytes",
        "Data": {
          "InfoCode": "CachedError",
          "ExtraText": null
        }
      }
    ]
  },
  "DnsClientExtendedErrors": [
    {
      "InfoCode": "NetworkError",
      "ExtraText": "technitium (127.0.0.1) returned RCODE=ServerFailure for Takealot.com. A IN"
    }
  ],
  "Identifier": 29348,
  "IsResponse": true,
  "OPCODE": "StandardQuery",
  "AuthoritativeAnswer": false,
  "Truncation": false,
  "RecursionDesired": true,
  "RecursionAvailable": true,
  "Z": 0,
  "AuthenticData": false,
  "CheckingDisabled": false,
  "RCODE": "ServerFailure",
  "QDCOUNT": 1,
  "ANCOUNT": 0,
  "NSCOUNT": 0,
  "ARCOUNT": 1,
  "Question": [
    {
      "Name": "Takealot.com",
      "Type": "A",
      "Class": "IN"
    }
  ],
  "Answer": [],
  "Authority": [],
  "Additional": [
    {
      "Name": "",
      "Type": "OPT",
      "Class": 1232,
      "TTL": "0 (0 sec)",
      "RDLENGTH": "98 bytes",
      "RDATA": {
        "Options": [
          {
            "Code": "EXTENDED_DNS_ERROR",
            "Length": "88 bytes",
            "Data": {
              "InfoCode": "NetworkError",
              "ExtraText": "k.gtld-servers.net (192.52.178.30) returned RCODE=ServerFailure for Takealot.com. A IN"
            }
          },
          {
            "Code": "EXTENDED_DNS_ERROR",
            "Length": "2 bytes",
            "Data": {
              "InfoCode": "CachedError",
              "ExtraText": null
            }
          }


Christoff Bothma
Sent From Mobile
________________________________

**Comment by ShreyasZare** [comment]
This is the reason for the ServerFailure:
`k.gtld-servers.net (192.52.178.30) returned RCODE=ServerFailure for Takealot.com. A IN`

If you keep getting these errors then it could be due to your ISP hijacking DNS requests which is quite common thing that many ISPs do. 

You can test if DNS request is getting hijacked by running `nslookup google.com 1.2.3.4` on your command line. If you get a response then it will confirm hijack. If no response then hijack still possible which could be done only for specific IP addresses.

In such case, you cannot run recursive resolver and will have to use encrypted DNS forwarders.

**Comment by ChristoffBo** [comment]
Hi,

No I only receive connection timed out; no server could be reached

**Comment by ChristoffBo** [comment]
but anyways thank you very much yet again. hopefully i wont be bothering you again soon.

thank you

**Comment by ShreyasZare** [comment]
> No I only receive connection timed out; no server could be reached

So, DNS hijack is not confirmed. There is some issue with the network though which is affecting recursive resolution.

> but anyways thank you very much yet again. hopefully i wont be bothering you again soon.

You're welcome.

**Comment by ChristoffBo** [comment]
Hi, me again I seem to have a few issues and I am not sure why, same as with using root domains, if I use a proxy (nord VPN or onion) or even quad 9 I get serv fail. Same result running on my homeassistant addon and my secondary dns. However tls for cloudflare works fine? Router settings are fine and dhcp works perfectly. Apologies I have been bothering you alot. But my nord VPN runs fine on my media server? Am I missing something or do you think it's my ISP? I run a mikrotik router and all on it seems fine

**Comment by ShreyasZare** [comment]
> Hi, me again I seem to have a few issues and I am not sure why, same as with using root domains, if I use a proxy (nord VPN or onion) or even quad 9 I get serv fail. Same result running on my homeassistant addon and my secondary dns. However tls for cloudflare works fine? Router settings are fine and dhcp works perfectly. Apologies I have been bothering you alot. But my nord VPN runs fine on my media server? Am I missing something or do you think it's my ISP? I run a mikrotik router and all on it seems fine

Do share the errors in the logs that you see in the DNS web console. Server Failure is just a generic response so it does not tell anything. Either the logs or the DNS extended errors that you get to see in the DNS Client will help to know what is the actual issue.
