### ISSUE TITLE
[Feature Request] Ability to enable/disable IPvX support

### ISSUE THREAD

**Issue by itsKV** [TechnitiumSoftware/DnsServer#47]
We can give toggle option to enable or disable IPv4 and IPv6 protocols, forcefully.

**Comment by ShreyasZare** [comment]
If I understand the feature request correctly, you can already use the "DNS Server Local Addresses" settings to only run the server on specific IPv4 or IPv6 addresses.

**Comment by itsKV** [comment]
Settings are as follows.

![Untitledz](https://user-images.githubusercontent.com/22906069/56803073-52081300-683f-11e9-82c4-3c0633b78a6a.jpg)

But, server is offering IPv6 resolution too. 

![Untitledx](https://user-images.githubusercontent.com/22906069/56803246-c478f300-683f-11e9-81b7-432ca2638386.jpg)


Admin should be able to control what is being served.

**Comment by ShreyasZare** [comment]
The DNS Server is not offering IPv6 resolution automatically. The nslookup utility is querying the DNS server twice, once for A record and another time for AAAA record, and then displaying both results together.

It is not as per standard to restrict the types of queries the client makes to the DNS Server.

**Comment by itsKV** [comment]
That is what I don't want. If I have not set AAAA local DNS server address then I should not get AAAA response anyhow. It seems server is serving AAAA queries over A address. (may be) 

(I have disabled IPv6 settings from my LAN adapter properties)

![Untitleds](https://user-images.githubusercontent.com/22906069/56879216-4867f080-6a75-11e9-8a3e-1b2e9bc6234a.jpg)

**Comment by ShreyasZare** [comment]
It seems you are a bit confused with this, let me explain. A DNS Server running only on IPv4 network will also respond to AAAA record queries. Similarly, a DNS Server on IPv6 network will also respond with an A record. 

The DNS Server is responding with AAAA record since it received an query for it. You can enable query logging in settings and then check log after running nslookup. You will find that nslookup is making two requests, one for A and another for AAAA.

The query request/responses have nothing to do with the network type you have configured. The AAAA record is just a DNS record among many different types of records.

You are seeing the IPv6 address for your domain name kvaibhav.in since you have an AAAA record in your Cloudflare DNS settings which you probably are using as a CDN.

Check out the response given by your Cloudflare name server yourself: [https://dnsclient.net/#Recursive%20Query%20(recursive-resolver)/kvaibhav.in/AAAA](https://dnsclient.net/#Recursive%20Query%20(recursive-resolver)/kvaibhav.in/AAAA)

**Comment by itsKV** [comment]
Ok. I get it. Thanks for clarification.
