### ISSUE TITLE
[Feature Request] DHCP Domain Name and Search Domain Handling

### ISSUE THREAD

**Issue by gigantuar** [TechnitiumSoftware/DnsServer#471]
Due to DHCP overwriting static DNS records (and removing those records when devices are offline) I have followed the recommendation of using a subdomain for DHCP (dhcp.domain.net vs domain.net). The issue with this is that devices do not search the base domain, only the new subdomain.

The majority of devices are using DHCP reservations and already have A records in domain.net which I never want removed. I have a few suggestions of options which will make DHCP more flexible with DNS.

1. Separate configuration options for which domain DHCP records get stored in and which domain is offered to the client. This is how I typically run ISC-DHCPD. The ddns-domainname is set to dhcp.domain.net while the subnet uses domain.net for the domain-name and domain-search.

2. The ability to specify additional search domains similar to domain-search with dhcpd would allow offering clients domain.net (or other additional domains) as a search domain.

3. An option in the DHCP server to disable DNS record scavenging/cleanup. If an IP address gets issued to a new host the old record would still be overwritten but it would prevent the issue of records being removed when devices are offline.

**Comment by ShreyasZare** [comment]
Thanks for the feature request. I think you are asking for [Domain Search (Option 119)](https://www.rfc-editor.org/rfc/rfc3397) which is planned to be implemented in a couple of releases. This will allow configuring multiple domain names that the client can search for.

> 1\. Separate configuration options for which domain DHCP records get stored in and which domain is offered to the client.

The problem with such a implementation is that the DHCP server will add a DNS record for `hostname.dhcp.domain.net` while the client thinks its domain is `hostname.domain.net` which will fail to resolve since there is no record in DNS for it. This is since the DHCP server tells the domain `domain.net` to be used during lease allocation and in response clients tells the DHCP server the fully qualified domain name `hostname.domain.net` that should be used. So its the client that decides the domain name for itself.


> 3\. An option in the DHCP server to disable DNS record scavenging/cleanup. If an IP address gets issued to a new host the old record would still be overwritten but it would prevent the issue of records being removed when devices are offline.

DHCP server cannot know if a device is offline. DNS records are removed only when the lease expires.  When the lease expires, the DNS record is anyways of no use. When the same IP address is allocated to a new host, the old record wont get overwritten since the hostname for the new host will be different so a new record will be created. Not cleaning up the DNS records will keep adding multiple records which have same IP address and potentially create confusion which record is stale and which one is in use.

**Comment by gigantuar** [comment]
Closing this as domain search is already planned which will solve the root issue.

**Comment by ShreyasZare** [comment]
Reopening it so that I will remember to post updates here when the DHCP option is available.

**Comment by ShreyasZare** [comment]
Version 10 is now released that adds Domain Search DHCP option 119. Do update and let me know your feedback.
