### ISSUE TITLE
[Feature Request] Ability to specify listen addresses for separate DHCP scopes

### ISSUE THREAD

**Issue by s4n-app** [TechnitiumSoftware/DnsServer#474]
When using multiple DHCP scopes inside a container, I encountered an inability to specify a listen address.

If I run it on bare metal or VM - everything is fine. The listen address from the corresponding network interface is automatically substituted into the configuration. However, in a container using [host networking](https://docs.docker.com/network/host/) this does not work.

The ability to manually specify the listening address should solve this problem.

**Comment by ShreyasZare** [comment]
Thanks for the post. The only way to run DHCP server with docker is using the host networking mode. The DHCP server cannot just listen on a specified IP address without access to the network interface. The case with DHCP is different than DNS since DHCP server requires receiving broadcast requests which can only be received in host network mode. Just mapping container ports to host ports for the container does not work with DHCP like it works for DNS.

Post the specific errors that you see with host network mode config here for which I can provide a fix.

**Comment by s4n-app** [comment]
I think you are right. Unfortunately, I couldn't find any errors in the logs, I can only say that 0.0.0.0 was specified for all dhcp scoups in the "Interface" column.

Perhaps this is due to the migration of the configuration from bare metal to the container. After making some changes in dhcp scopes (unrelated - removing unnecessary static routes), everything began to work as expected, and the corresponding IP addresses began to be displayed in the "Interface" column.

My apologies for disturbing and thank you very much for your help!

**Comment by ShreyasZare** [comment]
> I think you are right. Unfortunately, I couldn't find any errors in the logs, I can only say that 0.0.0.0 was specified for all dhcp scoups in the "Interface" column.

The DHCP scope will use `0.0.0.0` to listen when it does not find any network interface for that scope and assumes that a DHCP Relay Agent on the actual network will be configured which will forward all DHCP requests to the DHCP server.

> My apologies for disturbing and thank you very much for your help!

You're welcome!
