### ISSUE TITLE
[Feature Request] set default values for new zones

### ISSUE THREAD

**Issue by shawnkhall** [TechnitiumSoftware/DnsServer#48]
I've been using this for about 6 months and now need to be able to create many custom zones for testing. Unfortunately, each one defaults to using my server device name instead of an IP (I'd like to be able to expose this over the Internet so the device name will be useless). It also requires me to manually assign the A and AAAA records for each.

I'd like to be able to quickly type (or paste) example.com, click Add, then have the IP address pre-filled with either the last IP I used for that DNS Type or a default assigned at Settings. This would accelerate the process drastically.

Alternatively, could you provide a sample using automation as you've mentioned in the past? I dug through the code and found a way to trigger the changes via Node.js but I'd really like to have my changes be as lightweight as possible for the best performance.

**Comment by ShreyasZare** [comment]
Thanks Shawn for the feedback. 

By default, the DNS server uses the computer's name for itself which you can change from Settings to a valid domain name so that you can actually host domain names directly on the Internet. The DNS Server's domain name would then be used for all zones for SOA and NS records.

Right now, the web UI and the server are completely independent of each other such that the web console uses the server API to do all tasks. You can do a couple of things to make your deployment task easier:

- Create a zone and configure it with A and AAAA record and then use it as a target for other zones using the CNAME record. This will help you with updating IP address in one single place and the rest of the zones will automatically respond with new IP address. Right now CNAME record for zone root works but it will soon be updated with new ANAME record IETF draft standard in upcoming updates.

- You can edit the main.js from the DNS installation folder and update the form rendering method's html template with your default values. This update will get served and you will get all your default values available in the web console.

- As you mentioned, you could directly use the API from node.js to create zone and add/update records by looking at the calls the web console main.js makes via the web browser's developer tools network tab. I am working on adding API details in documentation that is being prepared. Link to the documentation is already added to the About > Help Topics section but its not uploaded yet so you would get 404 for now. It should be available in a week or so.
