### ISSUE TITLE
Issue running under Mono.

### ISSUE THREAD

**Issue by e3ndr** [TechnitiumSoftware/DnsServer#484]
Howdy, I'm trying to run the DNS server on a Raspberry Pi 0 (I know, unsupported). I've gotten Mono to install successfully, however running the server results in a fatal error which Google doesn't have an answer for. Any help is appreciated!

```
$ mono DnsServerApp.dll

Unhandled Exception:
System.TypeLoadException: Could not resolve type with token 01000016 from typeref (expected class 'System.Environment' in assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not resolve type with token 01000016 from typeref (expected class 'System.Environment' in assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
```

```
$ mono --version
Mono JIT compiler version 6.12.0.182 (tarball Tue Jun 14 22:53:32 UTC 2022)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  armel,vfp+hard
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(610)
        Suspend:       preemptive
        GC:            sgen (concurrent by default)
```

**Platform:**
Raspbian 11 (bullseye)
armv6l/armel

**Comment by ShreyasZare** [comment]
Thanks for the post. The DNS Server requires .NET 6 runtime and thus wont run on mono runtime which is capable of running binaries that are compatible with .NET Framework. 

.NET Framework is a windows only runtime while .NET 6 is a cross-platform runtime which tells that Microsoft is very good at naming things.

All models of generation 1 and Pi Zero are not supported because the .NET 6 JIT compiler depends on armv7 instructions not available on those versions.

**Comment by e3ndr** [comment]
Ah, that's where my confusion arose. Microsoft is truly the best when it comes to naming stuff 🥴
