### ISSUE TITLE
Improving display/usability of Allowed/Blocked tabs

### ISSUE THREAD

**Issue by Aerowinder** [TechnitiumSoftware/DnsServer#508]
Greetings,

Presently, the Allowed and Blocked tabs display information in an appropriate hierarchy for DNS, but it's not particularly human-friendly.

Would it be possible to show an aggregated list of all Allowed/Blocked zones in a simple list format somewhere, instead of having to click through the hierarchy to see them all? I came from Pi-hole, and I was able to copy all of my allowed domains over because they are in a simple list format. Maybe a button to export them all to text file? That would work as well.

Also, could it be possible to import multiple Allowed/Blocked zones at once using a comma-separated list?

**Comment by ShreyasZare** [comment]
Thanks for the post. These tabs are designed to be browse-able since the underlying data structure is a tree. So, it shows you sub domain names for the current node in tree and you can navigate up or down the nodes. Showing it as a list means to read all nodes in that tree and the show the list which can take a lot of time if there are too many records in the tree.

There is already options to import and export domain names from both the Allowed and Blocked tabs. Just check out the options in the top right corner in that section. It exports as a text file containing list of domain names and also can import them in same format.
