### ISSUE TITLE
Possible to move resolution failures to Query Log?

### ISSUE THREAD

**Issue by Aerowinder** [TechnitiumSoftware/DnsServer#509]
Greetings,

I use Query Log - I think it's pretty essential for DNS sinkhole (ex-Pihole user). What I'm confused by is why resolution failures appear in the standard log, but not the Query Log. I'm guessing it appears in the log because it's causing an exception, and exceptions are logged - but why does a resolution failure cause an exception, instead of being handled gracefully?

Can it be possible to add the ability to search for resolution failures within the Query Log?
Cab it be possible to prevent resolution failures from throwing an exception?

**Comment by ShreyasZare** [comment]
Thanks for the post.

> I use Query Log - I think it's pretty essential for DNS sinkhole (ex-Pihole user). What I'm confused by is why resolution failures appear in the standard log, but not the Query Log. I'm guessing it appears in the log because it's causing an exception, and exceptions are logged - but why does a resolution failure cause an exception, instead of being handled gracefully?

Exception is how the code know what went wrong. Logging the complete exception in text logs gives the developer enough data to know what went wrong and where to look for it.

If there is any issue with the resolution, the error is logged in text logs and the DNS server returns a response with ServerFailure RCODE. This response gets logged in the Query Logs database which you can filter by RCODE.

> Can it be possible to add the ability to search for resolution failures within the Query Log?

You already have failure logged so just filter by ServerFailure RCODE to list them.

> Cab it be possible to prevent resolution failures from throwing an exception?

This is how the programming is supposed to work. The exceptions are handled gracefully otherwise the DNS server process would have crashed. The exceptions are just being logged to help debug issues by knowing exactly what went wrong.

Most of the exceptions that you see related to domain resolution are just due to operational issues. The most common reason is timeout i.e. the name server didn't respond to the request in time. It could be that there is issue with your Internet or it could be that the name server is busy and didn't respond in time. These issues usually resolve on its own when the DNS server retries. Once the DNS cache has the data resolved, it will use it later too with the Serve Stale feature. So you wont get frequent issues once the domain gets resolved even when the name servers are not responding frequently.
