### ISSUE TITLE
[Feature Request] Immediately create A record for DHCP reservations

### ISSUE THREAD

**Issue by rinseaid** [TechnitiumSoftware/DnsServer#515]
It would be useful if there was the ability  (likely optional) to immediately create an A record for a new DHCP reservation, provided the host name field is populated and the server is authoritative for the zone specified in the DHCP scope.

Currently, it appears that the record is created only when the lease is distributed or renewed.

**Comment by ShreyasZare** [comment]
Thanks for the request. Please explain the issue you are facing due to this since the lease is not allocated which means the clients is offline.

**Comment by rinseaid** [comment]
Not necessarily offline- I experienced name resolution failures for a period while migrating to Technitium DNS Server from another solution due to this.

In other solutions, I've often put devices configured with static IPs into the reservation list to serve both as a DHCP pool exclusion, and as a poor man's IPAM!

**Comment by ShreyasZare** [comment]
> Not necessarily offline- I experienced name resolution failures for a period while migrating to Technitium DNS Server from another solution due to this.

Well, the server was migrating to new network so it wasn't connected to it which means it was offline for the users on the new network even when it was not actually offline. Even if the reserved lease domain name resolves in such case, it would still give clients connection timeout errors. Also, the client hostname in reserved lease is optional do the actual domain in most cases is known only when the client requests for a lease.

The DNS entry is made only after the lease is allocated since the allocation process does validations to ensure that the IP is not in use for any reason. So, making a DNS entry before that would create issues in some scenarios.

**Comment by rinseaid** [comment]
Ok, that all makes sense. Thank you!
