### ISSUE TITLE
[Feature Request] Do not forward non-FQDN to root servers

### ISSUE THREAD

**Issue by Aerowinder** [TechnitiumSoftware/DnsServer#519]
Greetings,

Presently, TDNS will forward any request that it receives which it does not have an answer for to the root servers... like any DNS server would. Most definitely expected behavior.

This includes non-FQDN requests like the hostname of another system on the network, and sometimes even IP addresses. my nginx servers send their non-FQDN hostname to the DNS server every time they boot. My network monitor sends IP addresses to the DNS server, all of which get forwarded to the root servers, then cached locally.

Would it be possible to have an option to automatically return NxDomain for non-FQDN requests when TDNS doesn't have an A/AAAA record for the request?

**Comment by ShreyasZare** [comment]
Thanks for the post. In the DNS protocol, there is no concept of FQDN since the DNS request/response always contain fully qualified domain names. Thus there is no way for the DNS server to know if the request contains a FQDN or not so such a feature is not possible to implement.

You can however configure your DNS server to handle known host names by using the NX Domain app which will return NXDOMAIN response for them. Or use the blocking feature to block them.

A better way would be to configure your DHCP server with domain name option so that all clients in your network are assigned a FQDN in `hostname.domain` format so that all such queries are automatically handled locally by the DNS server.

**Comment by Aerowinder** [comment]
Greetings,

Your insight is appreciated. I'll make adjustments with my setup to minimize non-FQDN requests.
