### ISSUE TITLE
What do you mean: "only" ?

### ISSUE THREAD

**Issue by dimyme** [TechnitiumSoftware/DnsServer#52]
> Before installing .NET, you'll need to register the Microsoft key, register the product repository, and install required dependencies. This **only** needs to be done once per machine.

Can you explain what "only" here means?

It's a gross tedious hoop-jumping operation bound to fail 90% of the time, so what do they usually do when they do not have rather modest demands **_ONLY_**.

**Comment by ShreyasZare** [comment]
Well, for .NET core runtime installation via apt-get, you need do register the key since Microsoft is running their own repository and thus without registering it the apt-get package manager wont be able to locate and verify the package.

You need to do that only once per machine since once you register it then it will work for all packages that Microsoft is providing. You can then do `apt-get install aspnetcore-runtime-2.2` or `apt-get remove aspnetcore-runtime-2.2` several times on that machine.
