### ISSUE TITLE
Split horizon zone transfers

### ISSUE THREAD

**Issue by selstam** [TechnitiumSoftware/DnsServer#532]
Is there any documentation on how to setup split views for zone transfers containing split horizon app records?

Problem, of course, is that most DNS servers have no clue about record type 108, which I think is being used for this. 108 is normallyu being used for RFC7043 resource records.

So in case you're using an ordinary bind server as secondary dns, is there anything one can do?

**Comment by ShreyasZare** [comment]
Thanks for the post. The split horizon support via DNS app uses APP records which are proprietary records that use private-use type code of [65282](https://github.com/TechnitiumSoftware/TechnitiumLibrary/blob/master/TechnitiumLibrary.Net/Dns/ResourceRecords/DnsResourceRecord.cs#L119).

The APP records being proprietary implementation will only work with Technitium DNS Server. So, your secondary zone must be hosted on Technitium DNS server and have the DNS app installed on it to make it work. 

There is no other way for this since there is no standard on how to implement such a feature. Each DNS server vendor thus implements it as per their design and use-case.

**Comment by selstam** [comment]
Ah, yes, stupid me, it clearly says so (`TYPE65282`) ...

In BIND you can accomplish the same thing by using a "virtual" zone for let's say "public" and another for "private" and only transfer the one that is applicable for the secondary DNS.

But then at least I understand that's not possible here.

It would be nice though! :)

**Comment by selstam** [comment]
So any idea on how to set up a hostname which publically would indicate a certain IP and the same hostname resolves to an internal ip or cname in the private sphere ... and which works with zone transfers to non-Technitium DNS servers?

**Comment by ShreyasZare** [comment]
> In BIND you can accomplish the same thing by using a "virtual" zone for let's say "public" and another for "private" and only transfer the one that is applicable for the secondary DNS.

You can accomplish something similar but that will require some changes how the zone is structured. The workaround is to have a primary zone that does not have any proprietary records and that can be used by any 3rd party DNS server as a secondary zone. 

Now, create another primary zone for a subdomain of the main zone where you can put the APP records. In your main zone, use CNAME entries that point to the APP record in the second zone. You can now have a similar primary zone for the subdomain name on another DNS server that uses its own proprietary method to do the same. This way you keep the proprietary records separate only with one issue of having to configure multiple DNS servers in case you need to update the dynamic records.
