### ISSUE TITLE
[Feauture request] Dashboard untrusted list

### ISSUE THREAD

**Issue by agomezxff** [TechnitiumSoftware/DnsServer#54]
First of all, thanks for your impressive work!

I would like to suggest you some improvements. I'm using this to monitor-block undesired connections, so using for a single client, I watch all queries and block the zones I don't like.
Would be great if I had a "trusted list" and a list where all the "untrusted" domains where listed. If it had an "add to blocked zone" link would be fantastic.

Bonus: Block zones allow regex
Bonus 2: In the log when "log all queries" flag blocked zones as "blocked". It shows the query with QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [0.0.0.0]

**Comment by ShreyasZare** [comment]
Thanks for the compliments and feedback.

Having a list of trusted/untrusted domains on dashboard will be an issue since the list can be huge. I also did not understand the classification since right now, you add any untrusted domain in block zones and rest all domain names are allowed.

I will explore the regex option to see how it fits in current zone design.

Logging changes can be done for clarity in next update.

**Comment by agomezxff** [comment]
Hi Shreyas,

I think of if as a small,pucntual analysis. For example, turn on that option in a browing session, watch all the queries requested and having an option to add to blocked zones easily

**Comment by Matthew-Bonner** [comment]
@agomezxff in the dashboard there is a list of top domains, and in https://github.com/TechnitiumSoftware/DnsServer/issues/45 there is a suggestion to add a link to easily block the domains which appear.

Also, in terms of a filter, would a keyword filter not be better for performance? Using regular expressions can be a big hit on performance. Most DNS servers opt for a keyword filter as opposed to a regular expression to block DNS queries.

**Comment by ShreyasZare** [comment]
Version 9.1 is now available that now has options on dashboard to allow/block domain names in the list. Do update and let me know your feedback.
