### ISSUE TITLE
Add option for ROOT SERVERS

### ISSUE THREAD

**Issue by Doimatcuabautroi** [TechnitiumSoftware/DnsServer#545]
How can I choose DNS over TCP for ROOT SERVERS, because no forwarders are configured, but this option supports only UDP protocol. Can it be support TCP protocol?

**Comment by Doimatcuabautroi** [comment]
![Screenshot 2023-02-01 at 16-21-35 pc - Technitium DNS Server v10 0 1](https://user-images.githubusercontent.com/18320809/216002902-162ee6e8-a757-4992-bc67-1c043eb1fd9b.png)

**Comment by ShreyasZare** [comment]
Thanks for the post. These options are to configure a forwarder. So the protocol you select here only applies to a forwarder.

When no forwarders are configured, the DNS server does recursive resolution which will by default use UDP and will upgrade to TCP automatically in certain scenarios like if response is truncated or if there was an invalid response received over UDP.

Enabling TCP by default for recursive resolution is not supported. The reason is that it increases resolution time and there are many name servers who do not have TCP enabled even when its mandatory to have both UDP and TCP available.

There is one option to force TCP though if its absolutely needed. To do that, you will need to setup a HTTP proxy server and then configure the DNS server to use that proxy. Since HTTP proxy servers support only TCP connections, the DNS server will automatically upgrade to TCP for recursive resolution via the proxy server.

**Comment by Doimatcuabautroi** [comment]
Thank you for your reply. Look like recursive resolution time (TCP) is too slow for something like DNS. May you add "Time out" option for DNS server when resolution time is too slow? ex: if the recursive resolution (UDP) via the HTTP proxy is too slow, then it will automatuc upgrade to TCP after 1 second. 
BTW, If I use recursive resolution (+ via HTTP proxy), how EDNS works, may you explain 2 cases?

**Comment by ShreyasZare** [comment]
> Thank you for your reply. 

You're welcome.

> Look like recursive resolution time (TCP) is too slow for something like DNS. May you add "Time out" option for DNS server when resolution time is too slow?

The DNS server already has timeout and retry mechanisms. It works well for UDP but for TCP it will take more time to resolve the request since TCP requires handshake to complete before sending the DNS request.

> ex: if the recursive resolution (UDP) via the HTTP proxy is too slow, then it will automatuc upgrade to TCP after 1 second. 

HTTP proxy does not support transporting UDP so the DNS server can only use TCP when HTTP proxy is configured. 

Upgrading to TCP when UDP fails is counterproductive. The DNS recursive resolver switches to the next name server to query when the first one does not respond. Adding TCP upgrade will make the domain resolve for too long time to be helpful.

> BTW, If I use recursive resolution (+ via HTTP proxy), how EDNS works, may you explain 2 cases?

EDNS works for all DNS transports and is not dependent on any specific feature of the transport protocol. 

Recursive resolution via HTTP proxy is not recommended since you wont be able to resolve a lot of websites as they don't have TCP enabled.

**Comment by Doimatcuabautroi** [comment]
>  Adding TCP upgrade will make the domain resolve for too long time to be helpful.
So, this is feature you will support? I dont get it, sorry.
Btw, If I use recursive resolution via TOR (HTTPTunnel command), should I worry about scamming, phising,... ?

[Suggestion] If a SOCKS5 proxy has builtin DNS resolution, instead of passing a remote DNS server (8.8.8.8, 1.1.1.1 and others), ask the proxy for resolve domains directly with its own DNS. The same with HTTP proxy.

**Comment by ShreyasZare** [comment]
> > Adding TCP upgrade will make the domain resolve for too long time to be helpful.
> 
> So, this is feature you will support? I dont get it, sorry. 

No DNS server does this since it does not work well in practice. So recursive resolution will use UDP as a default and only upgrade to TCP when needed.

> Btw, If I use recursive resolution via TOR (HTTPTunnel command), should I worry about scamming, phising,... ?

If you use TOR, you will be using SOCKS5 config on the DNS server. The DNS server will do recursive resolution using TCP over TOR since TOR does not support UDP. It is possible that a TOR exit node hijacks DNS requests so your requests may not always return correct IP address. So, you should use a forwarder with encrypted DNS protocol when using TOR, Recursive resolution over TOR is not recommended due to this security threat.

> And I have a suggestion: If a SOCKS5 proxy has builtin DNS resolution, instead of passing a remote DNS server (8.8.8.8, 1.1.1.1 and others), ask the proxy for resolve domains directly with its own DNS. The same with HTTP proxy.

Yes, the proxy servers will resolve domain names to IP address on their side for requests but they do not tell you the IP address it resolved in response. For example if you use proxy to connect to "example.com" it will make a connection but you wont know which IP address it actually connected to.

If you configure "dns.google" as the forwarder for the DNS server then that forwarder domain name will be resolved via the proxy. Any other request that the DNS server receives will be resolved by forwarding the request to the configured forwarder i.e. "dns.google".

**Comment by Doimatcuabautroi** [comment]
Aw, maybe you and i are confusing each other. 
First, in my view when you explain, DNS server has to wait the first response failed and then it upgrade to TCP for the retry. Is there anyway to force recursive resolution upgrade to TCP immediately or set the timeout shorter while DNS server use UDP via HTTP proxy. 
Next, about my suggestion. If I configure SOCKS(HTTP) proxy, then I configure forwarders(8.8.8.8,1.1.1.1,...), in this case I'm using DNS over SOCKS(HTTP). However, I dont want use forwarders over SOCKS(HTTP), I want to use builtin DNS resolution that provided by SOCKS(HTTP), in this case it is not recursive resolution over SOCKS(HTTP), it is buitin DNS resolution by SOCKS(HTTP).
Could you explain more about "dns.google" as the forwarder. Look like, I'm not familiar with it.

**Comment by ShreyasZare** [comment]
> Aw, maybe you and i are confusing each other. First, in my view when you explain, DNS server has to wait the first response failed and then it upgrade to TCP for the retry. 

No, there is no upgrade to TCP for retry. Retries are always over UDP. TCP upgrade happens only when the UDP response is truncated or when the response has invalid ID/QNAME etc which could be an spoofing attack attempt.

> Is there anyway to force recursive resolution upgrade to TCP immediately or set the timeout shorter while DNS server use UDP via HTTP proxy. 

There is no option to make it upgrade to TCP and there is no plan to do that since its not a good idea. HTTP proxy does not support UDP so DNS server cannot use UDP when HTTP proxy is configured.

> Next, about my suggestion. If I configure SOCKS(HTTP) proxy, then I configure forwarders(8.8.8.8,1.1.1.1,...), in this case I'm using DNS over SOCKS(HTTP). 

SOCKS proxy and HTTP proxy are both different type of proxies. SOCKS proxy supports UDP so DNS server can use it to perform recursive resolution over UDP. HTTP proxy does not support UDP.

> However, I dont want use forwarders over SOCKS(HTTP), I want to use builtin DNS resolution that provided by SOCKS(HTTP), in this case it is not recursive resolution over SOCKS(HTTP), it is buitin DNS resolution by SOCKS(HTTP). 

When you configure proxy for the DNS server and don't have any forwarders configured then the DNS server will perform recursive resolution over the proxy. If the proxy server supports UDP then the DNS server will use it or it will automatically use TCP to do recursive resolution.

Using recursive resolution over Tor, like you mentioned earlier is bad idea from security perspective since it allows an Tor exit node to hijack DNS requests.

> Could you explain more about "dns.google" as the forwarder. Look like, I'm not familiar with it.

I just gave an example earlier to set "dns.google" as the forwarder with DoH or DoT. But since you have not provide IP address for the domain "dns.google", the DNS server will pass the domain name directly to the proxy server and the proxy server will resolve the domain name to connect to it. If you instead configure "dns.google (8.8.8.8)" then the IP address is known by the DNS server and it will use it to connect via the proxy server so proxy server in this case does not get to resolve the domain name.
