### ISSUE TITLE
Disable resolving the DNS chain

### ISSUE THREAD

**Issue by agneevX** [TechnitiumSoftware/DnsServer#556]
It appears that every CNAME in the DNS chain is being resolved rather than letting upstream servers handle it and querying upstreams for the single query being requested.

Can this behavior be disabled?

**Comment by ShreyasZare** [comment]
Thanks for the post. This behavior cannot be disabled and is required by design. The CNAME domain in response is required to be processed for several things like checking if that domain is locally hosted or has a conditional forwarder zone or requires to be processed by a DNS app. The DNS server thus accepts only the first CNAME record in the answer and discards the rest.

With the current design, each CNAME domain is then queried again internally to be resolved. Thus all internal processes and DNS apps get a chance to see the query and take action.
