### ISSUE TITLE
Feature Request: Option to remove PTR record when A record is removed

### ISSUE THREAD

**Issue by ajeffco** [TechnitiumSoftware/DnsServer#588]
It would be nice to have the option to remove other records such as PTR or CNAME records when an A record is deleted, if they exist.

**Comment by ShreyasZare** [comment]
Thanks for the request and contribution. Will get an option to remove PTR records added in the next update. 

For CNAME its not feasible since it will require scanning all zones for finding the CNAME record which wont be optimal. Plus there can be CNAME to a CNAME so it will require multiple passes to find and remove the records.

**Comment by ajeffco** [comment]
Thank you.  The CNAME being impractical makes sense.  The PTR thing is a quality of life thing for me, I knew better and forget to remove PTRs and had a handful hanging around ;)

**Comment by ShreyasZare** [comment]
I had checked this and there is already feature that removes PTR record for the deleted A/AAAA records. This is done by default so there is no additional option available. Do try it once on a test setup and check.
