### ISSUE TITLE
NextDNS DoH3

### ISSUE THREAD

**Issue by HellboyPI** [TechnitiumSoftware/DnsServer#596]
Hello!
NextDNS supports DoH3. Wenn I write "h3://dns.nextdns.io/xxxxxxxx" into Forwarders, it doesn't work.

"xxxxxxxx" is my profile ID. NextDNS doesn't have "/dns-query" at the end of url. Technitium DNS is installed on Debian 11. Libmsquic library and openssl are also installed.

**Comment by ShreyasZare** [comment]
Thanks for the post. I checked the NextDNS URL and it does not seems to support HTTP/3. It only supports HTTP/1.1 and HTTP/2. There is no `alt-svc: h3=":443"; ma=86400` header seen with HTTP/1.1 or HTTP/2 requests.

**Comment by ShreyasZare** [comment]
Ya, I too think its some subtle issue with how HTTP/3 is being implemented. Since HTTP/3 is quite a new protocol it may take a while for things to settle. 

Technitium DNS Server is using HTTP/3 client which is Microsoft's implementation and it works with a lot of HTTP/3 websites too without issues. The DoH implementation is using it and its working with Google and Cloudflare, but not with dns0 and Adguard.

However, since HTTP/3 uses QUIC transport protocol, which is the same being using with DNS-over-QUIC, you can switch your config to use DNS-over-QUIC which dns0, NextDNS and Adguard supports and is working fine with Technitium DNS Server.
