### ISSUE TITLE
Clients do not get DHCP reserved IP.

### ISSUE THREAD

**Issue by Lausterwork** [TechnitiumSoftware/DnsServer#606]
I am having a reoccurring issue of my servers not getting their reserved IP, even if the lease is not expired (or maybe because the lease is not expired?)
Instead a new lease is added to the db and the client is assigned that.

Attached is a screenshot to show what I mean:
<img width="854" alt="image" src="https://user-images.githubusercontent.com/116890130/232038061-04b87a92-a5c6-4c9c-bdec-97e2e952eca3.png">

**Comment by ShreyasZare** [comment]
Thanks for the post. The reserved lease are allocated based on the MAC address in the DHCP request but, during renewing lease its the DHCP Client Identifier that is matched with the reserved lease.

The issue you are seeing is due to the DHCP client changing its Client Identifier. You need to edit your DHCP client config to set it to use the Client Identifier based on MAC address. 

Check this issue on [StackOverflow](https://superuser.com/questions/1338510/wrong-ip-address-from-dhcp-client-on-ubuntu-18-04#1338515) on how to configure it for Ubuntu.

**Comment by Logiz57** [comment]
*sigh* yet another thing to dislike about systemd.
Thanks for the answer though 👍 - i'll add it to the list of things that need doing on new machines.

**Comment by ackstorm23** [comment]
For anyone else using systemd-network,  just add this to your device config

```
[DHCP]
ClientIdentifier=mac
```
