### ISSUE TITLE
DNSSEC error - "System.InvalidOperationException: Operation is not valid due to the current state of the object."

### ISSUE THREAD

**Issue by AceBlade258** [TechnitiumSoftware/DnsServer#611]
I have tried disabling and re-enabling dnssec, but the error persists. Best I can tell it's happening every 15 minutes when it goes to refresh the signatures. I am unsure why it's failing to refresh the signatures, however...

```
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at DnsServerCore.Dns.Zones.AuthZone.RefreshSignatures() in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\Zones\AuthZone.cs:line 487
   at DnsServerCore.Dns.Zones.PrimaryZone.TryRefreshAllSignatures() in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\Zones\PrimaryZone.cs:line 1847
   at DnsServerCore.Dns.Zones.PrimaryZone.DnssecTimerCallback(Object state) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\Zones\PrimaryZone.cs:line 442
```

**Comment by ShreyasZare** [comment]
Thanks for the post. The error is coming since the primary zone is missing RRSIG record(s) which is unexpected thing to happen for a signed primary zone. 

Can you describe more about this primary zone you have? Do you have it signed with DNSSEC? Or, did you use DNS Client to import zone from somewhere?

**Comment by AceBlade258** [comment]
The zone is a root zone for one of my domains, it is signed by DnsServer. I have attempted to disable and re-enable DNSSEC - thus re-signing the zone - but the error persists.

**Comment by ShreyasZare** [comment]
Since this is a very specific issue, I would need you to share details about your zone. Do share screenshots of the zone which shows all the records including the DNSSEC records, and also screenshot of the DNSSEC properties. Send them to support@technitium.com and you will get a response over email.

**Comment by AceBlade258** [comment]
Email sent, let me know if you need anything else from me.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11.1 is now available that fixes this issue. Do update and let me know your feedback.
