### ISSUE TITLE
[Feauture request] Upon blocking a zone the top domains and top blocked domains aren't updated.

### ISSUE THREAD

**Issue by Matthew-Bonner** [TechnitiumSoftware/DnsServer#62]
Upon blocking a zone the top domains and top blocked domains aren't updated.

I blocked flingo.tv, which is a content recommendation engine and viewer tracking application designed for Smart TVs, as my smart tv is trying to make a connection to it every second.

The stats on top domains and top blocked domains have remained unchanged, so I was wondering, given the large number of times flingo.tv was requested, could an option be provided to flush the stats in the web console next to the other buttons for flushing blocked domains, etc.

![image](https://user-images.githubusercontent.com/7858744/61490998-15633800-a9a6-11e9-9e38-23dc62d9af43.png)

**Comment by ShreyasZare** [comment]
The stats on dashboard should get updated after a while. I did a test and it works as intended: 

![image](https://user-images.githubusercontent.com/10008172/61520627-425a2e00-aa2c-11e9-84ac-98d9aaff894f.png)

The flush options in settings are to flush in memory data to allow testing. Flushing stats will mean to delete the stats files from disk which will be a permanent action.

**Comment by Matthew-Bonner** [comment]
The dashboard was updating, but maybe the issue is the rate at which it refreshes, it just felt like a long time before it showed what I expected to see.

**Comment by ShreyasZare** [comment]
Stats are compiled for each minute so what you see on dashboard is up to the last minute. Dashboard javascript is set to refresh every 60 sec.

**Comment by Matthew-Bonner** [comment]
In theory that means it could take up to 2 minutes to refresh, if the javascript refreshes at 58 seconds and the stats refresh at 59 seconds, then it would be another minute before the stats are updated.

Is it worth reducing this time to 30 seconds in the javascript and 30 seconds on the server so that the max time it would take is a minute?

**Comment by ShreyasZare** [comment]
The server refresh cannot be updated since it computes stats for a minute at minimum so cannot do that twice each minute. Even if you do that then you will see the values on chart change for the last minute on next refresh which will make it seem like the data is inconsistent.

On the dashboard what you see is stats up to the last minute so, you will see data up to 1 min late if the JS timer is firing just before the server computes the minute stats. Thus can be up to 2 mins old data on the dashboard.

Making JS timer refresh every 30 sec will reduce the delay but it has another side affect of refreshing to the same stats for every alternate refresh cycle which may get really annoying (or trigger OCD!) since you expect it to show new data for every refresh.

**Comment by Matthew-Bonner** [comment]
This might as well be closed as I originally logged it as I expected to see flingo.tv show up in the blocked list but after a while of not seeing it was a little surprised. Having thought about it some more, I feel like a bit of an idiot now because the TV was turned off so I was waiting for the queries to be blocked despite the device not being on, which is fundamentally what lead where we are now. Given your comments, it sounds like there is nothing really to be done here too.
