### ISSUE TITLE
Query Log: Separate Log File on Filesystem

### ISSUE THREAD

**Issue by ztheory** [TechnitiumSoftware/DnsServer#626]
The query Log is a great feature!

Would it be possible to keep the query logs in a separate log file so they are not mixed in with the application logs?

You could use the same daily log rolling, so application logs are in, for example:

`2023-05-08`

And query logs are in, for example:

`2023-05-08_query`

**Comment by ShreyasZare** [comment]
Thanks for the request. The query logs are kept in the same log file since most of the errors logged are resolution errors and the query logs help with understanding the context.

You can use the Query Logs (sqlite) DNS app so as to see the query logs independently which will also give you options to filter the data based on multiple conditions from the Logs > Query Logs section on the web app.
