### ISSUE TITLE
This software starts with OS by default

### ISSUE THREAD

**Issue by JeanPaulLucien** [TechnitiumSoftware/DnsServer#639]
After installation this software starts with OS. I don't like it. I did not find where to disable autostart.
OS: Windows 7, program version is 11.1

**Comment by ShreyasZare** [comment]
Thanks for the post. If the DNS server did not start when OS starts then your Internet on the computer wont work. If you wish to stop the DNS server from starting, go to Windows Services from start menu, find Technitium DNS Server in there and then change the startup type to Manual and stop the service. Once you stop the service, make sure to change the DNS servers on your network adapter so that Internet works.

**Comment by pricerc** [comment]
It would be very strange for a newly installed service in Windows to *not* automatically start on boot.

**Comment by ShreyasZare** [comment]
> > It would be very strange for a newly installed service in Windows to _not_ automatically start on boot.
> 
> #640 It will be not strange. If user needs than should check "Start on startup".

Its a server software so its expected to start at boot unlike client apps which the user starts when needed.

**Comment by JeanPaulLucien** [comment]
If your goal is server's users only then I should leave and other people who did not install or will not install this program on server.
Do you wanna to limit users quantity I suppose you do not.

I suggest the program should not start with OS by default. Add the switcher in tray menu. Enable start with OS is not problem for server administrator.

**Comment by ShreyasZare** [comment]
> If your goal is server's users only then I should leave and other people who did not install or will not install this program on server. Do you wanna to limit users quantity I suppose you do not.

The software being a server software does not mean that it has to be installed only on server hardware. The DNS server can be installed on low powered devices like Raspberry Pi or by end users on their Windows laptops. When its installed by an end user on their laptop to use locally, its still a server software. This does not mean there is any limit on where the software should be used.

> I suggest the program should not start with OS by default. Add the switcher in tray menu. Enable start with OS is not problem for server administrator.

Almost everyone who would install the software expect it to start with the OS by default. This is because, if the DNS server is being used locally then the the service not starting will cause Internet connectivity issues. Only in exceptional cases like yours where you do not want it to start at boot, its just a matter of changing the service preferences.

If the DNS server does not start with OS by default or if there was an option for this in setup then it will create issues with a lot of users who would end up opening new issues on GitHub or sending email to support. The DNS service is set to start by default precisely because a lot of end users are not aware of Windows Services and thus wont be sure on how to make the service auto start. 

Very rarely its a case that the user does not use the DNS server locally and wants it to not start with the OS. In such cases, such advanced users can easily change the service startup mode.
