### ISSUE TITLE
SVCB auto-inclusion of relevant A records may result in duplicate records returned

### ISSUE THREAD

**Issue by ruifung** [TechnitiumSoftware/DnsServer#641]
For example:
If there are two SVCB records for _dns.resolver.arpa, i.e. for example, in the DDR use case with separate records for the doq and dot ALPN.

When the SVCB query is done using the DNS client in the web interface, it results in the same A record for the target specified in both SVCB records (which is the same target) being returned twice in the additional section. Perhaps not returning duplicate records there might be a good idea.

**Comment by ShreyasZare** [comment]
Thanks for the post. This is acceptable response where the client is supposed to prefer the A record in the additional section when available over the `ipv4hint` in the SVCB/HTTPS records. The IP hints in the records are to be only used when a client does not receive A/AAAA records in the additional section for the first connection attempt. It should then resolve the actual A/AAAA records and use them instead of the IP hints.

**Comment by ruifung** [comment]
I mean, it returns the same A record multiple times in the additional section.

**Comment by ShreyasZare** [comment]
Thanks for that feedback. Will take a look at it. 

Also, you can use a single SVCB record with alpn set to `dot,doq` instead of two separate records.

**Comment by ruifung** [comment]
Not if they are (potentially) using different ports. But I suppose that will indeed work if they are on the same port.

**Comment by ShreyasZare** [comment]
Version 11.3 is now available which fixes this issue. Do update and let me know your feedback.
