### ISSUE TITLE
Exception thrown when starting DNS Server upon Windows 2008 R2 restart

### ISSUE THREAD

**Issue by Matthew-Bonner** [TechnitiumSoftware/DnsServer#65]
I keep getting the following error upon restarting my server:

> [2019-07-19 23:41:44 UTC] [192.168.1.3:67] DHCP Server failed to activate scope: Default
> System.Net.Sockets.SocketException (0x80004005): The requested address is not valid in its context
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
>    at System.Net.Sockets.Socket.Bind(EndPoint localEP)
>    at DnsServerCore.Dhcp.DhcpServer.BindUdpListener(IPEndPoint dhcpEP)
>    at DnsServerCore.Dhcp.DhcpServer.ActivateScope(Scope scope)

The server is a Windows 2008 R2 box.

I've tracked the issue down to the service starting before other services it depends on have started.

I know the IP address is correct and the correct network card is being used.

If you take a look at the following post, it is a common issue, not just specific to the DNS Server:
https://social.msdn.microsoft.com/Forums/en-US/03240f8f-7cc9-4e45-843a-6b8c62cbec4c/#1fd42173-aee3-4cb2-b033-0066ed4c50f0

I tried delaying the service start, and this resolves the issue.

The issue can be reproduced upon every restart.

**Comment by ShreyasZare** [comment]
Well, then it seems delayed start is only fix for this. Since its DHCP server, its expected to run without downtime so delayed start should be acceptable solution.

**Comment by Matthew-Bonner** [comment]
Can the installer be updated so that when the service is created in Windows it is set to delayed start?

**Comment by ShreyasZare** [comment]
Installer can be updated but having delayed start by default will cause delay for starting DNS server too. Which will mean that there will be no connectivity for few mins after each reboot. This will be undesirable for people who are not using DHCP on their Windows 10 client machines.

**Comment by Globulopolis** [comment]
My server on Windows 7, and I cannot set up delay before service start.

**Comment by ShreyasZare** [comment]
> My server on Windows 7, and I cannot set up delay before service start.

Automatic (Delayed Start) option is there in Windows 7 SP1.

**Comment by Globulopolis** [comment]
> Automatic (Delayed Start) option is there in Windows 7 SP1.

My fault. :)

**Comment by Matthew-Bonner** [comment]
> 
> 
> Installer can be updated but having delayed start by default will cause delay for starting DNS server too. Which will mean that there will be no connectivity for few mins after each reboot. This will be undesirable for people who are not using DHCP on their Windows 10 client machines.

Why not separate the two services then, as that is what most would probably expect, at least then one can start instantly and the other can be delayed until Windows is ready.

**Comment by ShreyasZare** [comment]
> Why not separate the two services then, as that is what most would probably expect, at least then one can start instantly and the other can be delayed until Windows is ready.

This will increase complexity since DHCP is updating DNS forward & reverse zones and there are multiple common runtime dependencies that include logging. Its is not desirable since its not affecting end user who uses only the DNS service on their laptop/desktop. While, anyone using DHCP server can configure delayed start and in such scenario the server is supposed to always run with rare reboots.

**Comment by Matthew-Bonner** [comment]
Both should be able to interact with each other through code, or through API endpoints.

There should be a clear separation of concerns and a separate cross cutting library for things like logging.

The control panel will also have to hide or show different tabs based on whether one or the other is enabled.

Sorting this now rather than when the project gets bigger should be a priority in my view, as not doing so is only going to create problems such as that will one day have to be resolved.

**Comment by ShreyasZare** [comment]
> 
> 
> Both should be able to interact with each other through code, or through API endpoints.
> 
> There should be a clear separation of concerns and a separate cross cutting library for things like logging.
> 
> The control panel will also have to hide or show different tabs based on whether one or the other is enabled.
> 
> Sorting this now rather than when the project gets bigger should be a priority in my view, as not doing so is only going to create problems such as that will one day have to be resolved.

That's what I meant that this change will add complexity. Any interaction between both services will require security considerations too. Since the issue can really be fixed by operator with delayed start, this additional complexity is not really going to be good. 

Realistically, the DHCP server in this project is intended for small to medium size networks. Any enterprise having Windows Server will already have a built-in DHCP server which provides more options than this one. So, adding so much complexity does not seem to be justifiable.

**Comment by Matthew-Bonner** [comment]
I'm in the process of moving to Server 2019 core anyway, and in doing so will be setting up a Debian VM and will likely run the DNS and DHCP servers on there, so I shouldn't have a problem then anyway.

That said, I think you underplay the work you have done here, C# is the defacto language for enterprise these days, and the work you've done gets us half way there to providing an enterprise open source solution. The reporting, portability, and API are close to providing everything anyone would need.

Security considerations are important, and as it happens .NET Core provides a number of providers out the box to allow your project to hook up to AD, OpenAuth, or something else, so securing the APIs shouldn't be too much of a challenge.

**Home usage**
So far, I'm using my DHCP server to address problems with not being able to use machine names when I RDP onto machines in my home network from work (connecting to my home VPN first of course), because the machines are on a different subnet, machine names only work when added to the DNS records, so I'm working on a system whereby I keep the reserved leases in sync with the zone I've set up for my LAN. At the moment I'm manually sync'ing the two but my long term plan is to automate this.

**Small to medium office network usage**
On a medium-sized network, I'm fairly certain people might already have a preferred DNS or DHCP server, so running either one or the other should be a consideration to avoid clashes when trying to bind to ports.

**Enterprise usage**
When you consider what people are likely to want for enterprise, the spread from home usage to enterprise isn't all that great in my opinion, and it isn't like people are loving what Microsoft are offering in this area either as a lot of it is antiquated dated tech that can't be changed because too many people will make a lot of noise if MS drastically change their offerings. So there is a market for such a project to cover all home, medium and enterprise networks in my view.

I also think the additional complexity will be inevitable as the project grows, so why not refactor the code now to avoid a massive headache later?

I think at most, the work I'm proposing will be around 2 to 4 weeks worth of refactoring.

**Comment by ShreyasZare** [comment]
> I also think the additional complexity will be inevitable as the project grows, so why not refactor the code now to avoid a massive headache later?
> 
> I think at most, the work I'm proposing will be around 2 to 4 weeks worth of refactoring.

I understand the points you are making. But, this issue already has a solution (delayed start). If there was no fix available then refactoring or finding another way to fix this was absolutely required.

On Win 10 client usage scenario, nobody will be using DHCP. On Win 10/Win Server being used for network service, the server will run 24x7 and delayed start fixes this issue if its occurring. On Linux, its not an issue.

This issue occurs only on some installations where the service is starting before the network is ready wherein the admin can use the solution to fix the issue. And since a DHCP server is not going to be rebooted frequently, this delayed start solution is not adding any inconvenience.

Refactoring DHCP out of the project effectively means to create a separate DHCP Server project which will then require its own API, web service, UI and maintenance.

The time consumed by this refactoring can be effectively utilized to add more core DNS features like zone transfer, secondary zone and related things. These feature will push the capabilities of the software making it useful in even more scenarios.
