### ISSUE TITLE
Dashboard does not work

### ISSUE THREAD

**Issue by hoseinnikkhah** [TechnitiumSoftware/DnsServer#670]
I have used this amazing tool for over a year and installed it again, because of the good dashboard it has. now I can't open dashboard which I don't know why.
here's and image:
![image](https://github.com/TechnitiumSoftware/DnsServer/assets/116885462/82a5ec47-3cd7-4646-a74a-b62b00820264)
I tied opening dashboard by accessing by `http://localhost:5380/' but nothing comes up.
why is that and is there any solution to it? I am looking to use forward settings which is only accessible trough web panel

**Comment by Hemsby** [comment]
Normally this is because the service is not started or running

Get Outlook for <https://aka.ms/ghei36> Android<https://aka.ms/ghei36>
________________________________
From: Hosein Nikkhah ***@***.***>
Sent: Tuesday, June 27, 2023 9:51:02 PM
To: TechnitiumSoftware/DnsServer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TechnitiumSoftware/DnsServer] Dashboard does not work (Issue #670)


I have used this amazing tool for over a year and installed it again, because of the good dashboard it has. now I can't open dashboard which I don't know why.
here's and image:
[image]<https://user-images.githubusercontent.com/116885462/249279877-82a5ec47-3cd7-4646-a74a-b62b00820264.png>
I tied opening dashboard by accessing by `http://localhost:5380/' but nothing comes up.
why is that and is there any solution to it? I am looking to use forward settings which is only accessible trough web panel

**Comment by ShreyasZare** [comment]
Thanks for the post. As @Hemsby said, its due to the Technitium DNS server's Windows Service not running. You can try to start it using the same context menu from Service > Start. If the service is failing to start then you need to check the Windows Event Viewer which will list an error describing why the service failed to start. Do post any error you see in there if you need help with it.

**Comment by hoseinnikkhah** [comment]
Thanks for the help, I used portable version and tried to check if I encounter same issue and it was ok, I did as @ShreyasZare said and it worked fine, as @Hemsby said, it had issues in running.
