### ISSUE TITLE
[Bug] Backup/Restore does not include certificate

### ISSUE THREAD

**Issue by micush** [TechnitiumSoftware/DnsServer#694]
Hi,

The backup and restore process does not include the certificate defined in the TLS certifcate file path under the web settings tab. Examining the backup zip file shows it's missing. Upon restore SSL encryption doesn't work. Maybe not under the optional protocols tab either for DoT/DoH, but admittedly I didn't test that one and both are the same certificate for me. Please fix. :)

Regards,
micush

**Comment by ShreyasZare** [comment]
Thanks for the feedback. The certificate is deliberately not included in the backup. Only items in the DNS server's config folder are in the scope of the backup and restore operation. The certificate file path is usually in a different location and managed by 3rd party apps like certbot which is why the DNS server does not touch it to avoid any issues.

If you restore a backup on another server, the TLS cert path wont exists and thus the HTTPS service wont start. You will need to login with the HTTP url to access the web panel and update the cert paths as needed to complete the migration. 

This is the same case with Optional Protocols like DoT, DoH, and DoQ.

**Comment by micush** [comment]
Sounds reasonable if the certs are outside the DNS folder. I put my certs inside the DNS folder, so maybe evaluate the configured paths and include the certs if they are within the folder? Otherwise, at least for me, I have an incomplete configuration on restore.

**Comment by ShreyasZare** [comment]
If the cert backup option is added, it will cause confusion since a user would select that they want to backup the cert but then since the cert is not in the config folder, it gets skipped and the user would not know that.

Also, even if the cert backup option is made available, your config restore operation is still incomplete since most cases people are using Let's Encrypt and would have to configure certbot on the new setup too. Plus, the certs expire in 90 days so a backup is going to restore old cert in many cases.

Adding this option is not going to help much which is why it was avoided in first place.

**Comment by micush** [comment]
For our certs we generate them from a corporate CA and they do not auto renew. They have expiration dates of 1 year or more, so a certbot type of scenario doesn't apply here.

**Comment by ShreyasZare** [comment]
Ok thanks for the feedback. Will evaluate how this can be implemented.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11.4 is now available that will include certs that are stored in the config folder. Do update and let me know your feedback.

**Comment by micush** [comment]
Confirmed it works well. Thanks for the quick turnaround. Much appreciated.
