### ISSUE TITLE
Hyper-V Default Switch Does not Appear 

### ISSUE THREAD

**Issue by ziasistani** [TechnitiumSoftware/DnsServer#702]
**Environment:**
Windows 10 [Version 10.0.19045.3324] 
with Hyper-V feature installed 
Technitium version is 7.1

**Symptom:**
When Technitium service startup type is automatic then "Default Switch" does not appear in network list (ncpa.cpl)  and Hyper-v manager But I set it's startup type to  Automatic(Delayed start) and everything is OK.

**Note:**
Default Switch is a Hyper-V Default Virtual Switch

**Comment by ShreyasZare** [comment]
Thanks for the post. Firstly, you have a very old version of the DNS server running. It is highly recommended to upgrade to the latest version. Do take a backup of settings before you upgrade for safety reasons.

The issue is mostly due to port getting blocked by the DNS server. The Hyper-V probably has its own DNS service that it expects to run on UDP port 53 but since the port is already in used by Technitium DNS server, there is an error causing the Hyper-V to stop.

You can resolve this by configuring the DNS Server Local End Points option in Settings section. Remove the default end points in there and put your system's static IP address. This will cause the DNS server to run only on that specific IP instead of ANY address and allow Hyper-V to use the ANY address instead.

Try this and let me know if that worked.

**Comment by ziasistani** [comment]
Yes, It is resolved by your solution.
Thanks for the guidance.

**Comment by ShreyasZare** [comment]
> Yes, It is resolved by your solution. Thanks for the guidance.

Thanks for letting me know.
