### ISSUE TITLE
DHCP not working

### ISSUE THREAD

**Issue by usmanafzal159** [TechnitiumSoftware/DnsServer#713]
Hi,

I have tried DHCP server with your product which is not relasing any ip address.
while checking DHCP port, 67 it shows its closed and also tumdump shows Zero packet on port 67

can you please help me out 

**PORT   STATE  SERVICE
67/tcp closed dhcps**

**Comment by ShreyasZare** [comment]
Thanks for the post. Please give more details on your setup so that I can help you with the issue:
- Which OS is the server running?
- Is the DNS server installed natively or is running as a docker container?
- Do you have any firewall running?
- Share screenshot of the DHCP scope list where it shows the "Interface" the scope is running on.
- Share screenshot of the DHCP scope config details.
- Share the details of the server's IP address and subnet mask.

**Comment by usmanafzal159** [comment]
Thanks for your replay 
My reply as,
**Which OS is the server running?**
Ubuntu 22.4
**Is the DNS server installed natively or is running as a docker container?**
Its Native not on docker
**Do you have any firewall running?**
i do have but the problem is tcpdump also showing zero packet on DHCPS port 67.
**Share screenshot of the DHCP scope list where it shows the "Interface" the scope is running on.**
<img width="931" alt="image" src="https://github.com/TechnitiumSoftware/DnsServer/assets/31029667/f316ae74-3969-4765-bd86-c3bb0f54f421">

**Share screenshot of the DHCP scope config details.**
<img width="819" alt="image" src="https://github.com/TechnitiumSoftware/DnsServer/assets/31029667/85629598-a242-47e2-acea-43f370351d4f">


Looking forward

**Comment by ShreyasZare** [comment]
Thanks for the details. The config seems to be good so not sure of the exact reason. If possible do a packet capture while a device attempts to connect to network and share the pcap file (you can email it to support@technitium.com).
