### ISSUE TITLE
Feature request: Duplication a zone using the GUI

### ISSUE THREAD

**Issue by noseshimself** [TechnitiumSoftware/DnsServer#714]
We have a few "template" zone files that we'd like to use for new zones as starting points. Would it be possible to add an option to create a copy of a (primary?) zone under a new name?

**Comment by ShreyasZare** [comment]
Thanks for the feature request. Currently there is no option to do this. However, there is a planned option to import/export zone files in bind format. This may be useful for your case to have a template zone which you can import each time while creating new zones. I will also plan an option in the UI so that you can clone the records directly from existing zone to make it easier.

There is another option that you can do now using HTTP API and scripts until the feature is available.. This will allow you to automate the zone creation and record addition with a simple bat/bash script using curl command.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11.5.2 is now available that adds Clone option to make a copy of an existing zone. Do update and let me know your feedback.

**Comment by noseshimself** [comment]
I imported our templates and tried this; it is working exactly as intended. Thank you very much!

**Comment by noseshimself** [comment]
Totally forgot to mention this: Im- and exporting zone files in combination with this is making things a lot easier.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Yes, the import/export + cloning feature would make it easier.
