### ISSUE TITLE
Feature request: Blocking type REFUSED

### ISSUE THREAD

**Issue by brokoler** [TechnitiumSoftware/DnsServer#724]
Hello,

I recognized that my Apple Devices continiously tried to resolve domains which were blocked via 0.0.0.0 or NX Domain.
After some testing it seems like they generate less requests if the DNS Response is REFUSED.

Would it be possible to add a new blocking type REFUSED to Technitium?

This DNS reply is specified in RFC 1035 (chapter 4.1.1, RCODE 5):
https://datatracker.ietf.org/doc/html/rfc1035

**Comment by ShreyasZare** [comment]
Thanks for the post. The two options currently available are the correct ways to block a domain. The response code REFUSED is not correct for blocking a domain name since its used by authoritative name servers to indicate that the zone is not hosted with them.

Some applications may keep retrying which you can just ignore. If you see a specific query being made too many times then use the Drop Requests app to drop such type of queries so that it does not show up on dashboard stats.
