### ISSUE TITLE
Zone update refused from IP within allowed network

### ISSUE THREAD

**Issue by rinseaid** [TechnitiumSoftware/DnsServer#767]
Technitium DNS 11.5.1

I have set up a zone 'example.net' and adjusted zone options to allow updates from network 10.10.20.0/24.

I have an OPNSense router at IP address 10.10.20.1 with a DHCP scope configured with Dynamic DNS using TSIG. However, when OPNSense attempts to update that zone, the request is refused and I see the following in the Technitium DNS logs:

`[2023-10-30 10:19:49 Local] [10.10.20.1:54627] [UDP] DNS Server refused a zone UPDATE request since the request IP address is not allowed by the zone: example.net`

I've tested the below changes without success (same log entry appears):
- Specifically adding 10.10.20.1 as an allowed IP address for the zone
- Switching between 'Allow Only Specified IP Addresses' and 'Allow Both Zone Name Servers And Specified IP addresses'

The only method I'm finding works in this scenario is setting the zone to Allow All.

Am I configuring this incorrectly?

**Comment by rinseaid** [comment]
Got it. Thank you for the quick response!

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11.5.2 is now available that fixes this issue. Do update and let me know your feedback.

**Comment by rinseaid** [comment]
@ShreyasZare  - yes, it's working perfectly after the update! Thanks so much for the quick fix, and for all the helpful features introduced in 11.5. It will make my DNS management a whole lot easier! Technitium DNS has innovative features unlike any other available DNS server, and it has been a game changer for my Kubernetes setup.

**Comment by ShreyasZare** [comment]
> @ShreyasZare - yes, it's working perfectly after the update! Thanks so much for the quick fix, and for all the helpful features introduced in 11.5. It will make my DNS management a whole lot easier! Technitium DNS has innovative features unlike any other available DNS server, and it has been a game changer for my Kubernetes setup.

Thanks for the feedback. Good to know that its working well now.

**Comment by Cartache** [comment]
Dear,

Very nice piece of software!
I am using the version 11.5.3 but receiving the same error message about technitium refusing "a zone transfer request since the request IP address is not allowed by the zone".
Is there any kind of regression between 11.5.2 and 11.5.3?
I have tried different IP addresses but nothing works.
I will try your workaround about TSIG.

Denis

**Comment by ShreyasZare** [comment]
> Dear,
> 
> Very nice piece of software! I am using the version 11.5.3 but receiving the same error message about technitium refusing "a zone transfer request since the request IP address is not allowed by the zone". Is there any kind of regression between 11.5.2 and 11.5.3? I have tried different IP addresses but nothing works. I tried activating your workaround about TSIG but the combo box does not contain anything.
> 
> Denis

@Cartache Thanks for the compliments. Do check the IP that is in the error log entry with the one you have configured with Zone Options. 

If the issue is still there then do share screenshots of your Zone, Zone Options, and full error log text to support@technitium.com. Will try to see if there is config issue or try to reproduce it locally.

**Comment by Cartache** [comment]
Issue solved, I had to authorize the transfer.
Thanks
