### ISSUE TITLE
"Allow List URLs" for Settings tab

### ISSUE THREAD

**Issue by hl2guide** [TechnitiumSoftware/DnsServer#78]
Please consider adding a section in the settings tab for **Allow List URLs**, which would act the same as **Block List URLs** but for applying to the **allowed zones** instead of **blocked zones**.

This would make adding allowed zones conveniently.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. This option is not really suitable to implement from practical purposes. If you wish to automate adding to Allow list then its best to use the HTTP API. If you wish to manually add then current option in the UI allows bulk import which is adequate.

This cannot be compared with Block List since block lists are updated by 3rd party in frequently and thus it makes sense to update new copy of the list every 24hrs.

If allowed list is implemented similarly then the server would update it every few hours and thus the changes wont reflect immediately. 

Thus HTTP API is more suitable for this operation.
