### ISSUE TITLE
The Portable version does not work with 

### ISSUE THREAD

**Issue by suikast42** [TechnitiumSoftware/DnsServer#802]
If I run in Protable mode then the DNS resultion does not works over the DNS server.

I running  on windows 11. 

I started the server over start.bat with an without admin rights. 

The installer works fine. 

![image](https://github.com/TechnitiumSoftware/DnsServer/assets/5046525/d829f9ec-e146-48f2-8750-4eff16074a69)

**Comment by ShreyasZare** [comment]
Thanks for the post. 

> If I run in Protable mode then the DNS resultion does not works over the DNS server.

Do you mean that the portable app failed to start? If yes then the portable binaries require you to manually install .NET 7 to work. The installer is recommended to be used on Windows platform since it will correctly install everything and also take care whenever .NET runtime is upgraded.

If it did start and its not resolving any requests then you need to check the DNS logs from the admin panel to find out if there are any errors logged in there. Post any errors you see in there if you need help with it.

**Comment by suikast42** [comment]
> If it did start and its not resolving any requests then you need to check the DNS logs from the admin panel to find out if there are any errors logged in there. Post any errors you see in there if you need help with it.

Exactly that. DNS is not resolving

**Comment by ShreyasZare** [comment]
> Exactly that. DNS is not resolving

Thanks for confirming. You need to provide more details so that I can help with the issue. Let me know if you have configured forwarders? how did you test if the DNS is not resolving? Are there any errors in the logs? 

Make sure that the "Ignore Resolver Error Logs" is unchecked in the Settings > Logging section otherwise these errors will be ignored and thus you will never know what went wrong.
