### ISSUE TITLE
I would like to digitally sign individual or small collections of DNS records in a zone...

### ISSUE THREAD

**Issue by mwherman2000** [TechnitiumSoftware/DnsServer#83]
I'm adapting DnsServer to become a more generalized "data server" for Digital Identity related data and records (reference: https://w3c-ccg.github.io/did-spec/).

In this context, I would like to digitally sign individual or small collections of DNS records in a zone.  DNSSEC appears to be a DNS extension that addresses this requirement but it doesn't appear to be currently supported by DnsServer.

Any other options/suggestions?

Best regards,
Michael

**Comment by ShreyasZare** [comment]
DNSSEC is the only option when working with DNS for signing individual records. For any specific requirements it would need something similar to DNSSEC to be reinvented. 

DNSSEC would work only on live domain names since the validation is done using root server keys. Using it for custom locally hosted zone with a custom top level domain (TLD) would be an issue since any DNSSEC validating client would not accept the custom TLD since it was not signed by root servers.

DnsServer currently does not support DNSSEC. This feature is desired but have been placed on low priority as some core features are still missing and DNSSEC implementation is too complex and time consuming.
