### ISSUE TITLE
Problem with DNS rewrites

### ISSUE THREAD

**Issue by ExXxtr3me** [TechnitiumSoftware/DnsServer#842]
Hey, i just switched from Adguard Home to Titianium and really like it so far, but i have a small problem with DNS rewrites.
I want to access test.mydomain.com at home internally and not through the internet, so i created a forward zone for mydomain.com with the forwarder "this server", in this zone i crerated an a record for test.mydomain.com with the ip 192.168.1.10, that's where my Nginx Proxy Manager is. This works now fine for test.mydomain.com and i can access the site locally, but every other site like test2.mydomain.com is not reachable anymore. In my understanding every site without a record in this zone should be available through the DNS Server (1.1.1.1 in my case) that i set up in the settings. Can anyone help me out what i' doing wrong?

**Comment by ShreyasZare** [comment]
Thanks for the post. The config you did for conditional forwarder zone will work as you are expecting. I am not sure why its not working there. It could be that there is something else that is affecting this.

For debugging, you will need to provide more details on your config like screenshot of the zone, details of any DNS apps you have running etc. You can post these details here or send them to support@technitium.com.

If you are able to find out steps to reproduce this issue then do post those steps here so that it can be tried on my setup.
