### ISSUE TITLE
Error starting v12 Docker container

### ISSUE THREAD

**Issue by marcovitali** [TechnitiumSoftware/DnsServer#852]
Hi,
I'm using Technitium DNS Docker image in a container on a MikroTik router (ARM64).
I was using the latest v11 without any problems.
Trying to upgrade to v12, I get the following errors when starting the container:

```
GC: Failed to initialize GCToOSInterface
GC initialization failed with error 0x80004005
Failed to create CoreCLR, HRESULT: 0x80004005
```
Any suggestions?

Thank you,
Regards

**Comment by ShreyasZare** [comment]
Thanks for the post. The ARM64 image is tested to work on Raspberry Pi 4 and is working well so there does not seem to be an issue with the image itself. 

I am not sure why its not loading on your router. I do not have MikroTik router to test it. I would suggest that you try to remove the container and image and try to redo it again once just in case if its some file corruption issue.

Do post any info you find here while debugging so that it would help anyone with same issue.

**Comment by marcovitali** [comment]
Hi,
I tried to recreate everything from scratch, but unfortunately I got the same error.
Unfortunately, I don't have anything to debug. The only thing I know is that version 11.5.3 works perfectly.

Let me send you some links, although not recent, with which perhaps you can understand a little more.
I would try that too but unfortunately I don't know .NET, I work with other technologies.

[https://github.com/dotnet/sdk/issues/7204](https://github.com/dotnet/sdk/issues/7204)
[https://github.com/dotnet/core/issues/733](https://github.com/dotnet/core/issues/733)
[https://github.com/dotnet/runtime/issues/3168](https://github.com/dotnet/runtime/issues/3168)

Thank you very much,
Regards

**Comment by ShreyasZare** [comment]
The only difference with the v12 release is that it now uses .NET 8 runtime. The DNS server docker image uses `mcr.microsoft.com/dotnet/aspnet:8.0` as the base image which you can check [here](https://hub.docker.com/_/microsoft-dotnet-aspnet/). 

I would suggest that you try and see if you are able to run the aspnet image on your device. This should give some clues on the issue. Try the sample container web app given on the [Docker Hub](https://hub.docker.com/_/microsoft-dotnet-aspnet/) page.

The links you posted are too old and do not seem to be relevant for the current .NET release even though the error message is same. 

I guess it could be a platform specific issue since the same arm64 image is working on my test Raspberry Pi 4 device.
