### ISSUE TITLE
Add support for Windows Integrated Authentication

### ISSUE THREAD

**Issue by rgl** [TechnitiumSoftware/DnsServer#859]
To relieve us from yet another password, can the web interface support Windows Integrated Authentication? That way, at least on Windows, we would not need to define another password, instead, the user privileges would be based on their integrated authentication roles. E.g. if the user belongs to the Administrators group, the user would have administration privileges to DnsServer.

**Comment by ShreyasZare** [comment]
Thanks for the request. Since the project is designed to be cross platform, having a windows specific way for auth will be a tough thing to add at the moment. 

There is already an open issue #512 for this support. But it may take a while to implement it since there are many pending features with higher priority.
