### ISSUE TITLE
DNS over HTTPS : Google plans for Chromium and Chrome

### ISSUE THREAD

**Issue by Fedora-Core** [TechnitiumSoftware/DnsServer#87]
The DNS-over-HHTPS solution that google is planning differs from the one that Firefox will use.

Instead of a "canary domain" that inihibits Firefox from using its own DNS-over-HTTPS with the cloudfare servers, chromium/chrome will use another approach. 

The Link to the developers blog =>

[https://www.chromium.org/developers/dns-over-https](url)

The Link to an article about it =>

[https://www.zdnet.com/article/google-to-run-dns-over-https-doh-experiment-in-chrome/](url)

Please consider to give this some review.

Greetings, F.C.

**Comment by ShreyasZare** [comment]
Thanks for the post. I have already read about their plan. It seems to be much better approach than Firefox's forced default option and thus it seems that Chrome wont bypass locally configured DNS or your network DNS unless they detect that you use any of the popular public DNS resolver that support DoH. 

It is however not clear how Chrome will detect which DNS is being used since, a user can have Google DNS configured on their router and DNS on the PC/device can be router's address. They may probably use method to resolve some random subdomain on their domain name and see if the recursive query comes from Google or Cloudflare etc. This would be similar to how DNS leak tests are done.

**Comment by ShreyasZare** [comment]
[Chromium DNS hijacking detection accused of being around half of all root queries](https://www.zdnet.com/article/chromium-dns-hijacking-detection-accused-of-being-around-half-of-all-root-queries/)
