### ISSUE TITLE
DNS Forwarder not working

### ISSUE THREAD

**Issue by marcussacana** [TechnitiumSoftware/DnsServer#89]
For some reason the Techinitium server isn't resolving new domains automatically, but works when I manually import it.

A Video: https://youtu.be/NNADpAlcUXQ 
The Log: [2019-09-22.log](https://github.com/TechnitiumSoftware/DnsServer/files/3639693/2019-09-22.log)

**Comment by ShreyasZare** [comment]
Thanks for the feedback and details. If you import zones then surely the server would respond to it. So, I suggest that you remove all the imported zones before proceeding with further testing. Also, do use the built in DNS Client to query the server for all tests since that will give you an accurate picture of the issue.

From your video, it seems that you are able to query Cloudflare using DNS Client so you should be able to use same as forwarder. It seems that recursive queries are not working for some reason so not using a forwarder will make the DNS server fail to respond. You can try using Wireshark on your server to check if DNS packets are being dropped or if your ISP is trying to filter DNS queries.

From the logs its seems that you have initially set Google DNS with DoH protocol as forwarder and the server is unable to resolve the "dns.google" domain name to proceed. You can try to simulate the same query using the DNS Client, just enter "dns.google" domain and select Recursive Query in server dropdown. Running Wireshark during this test will show the exact issue that is going on in the network.

I am not sure what is the exact reason for this but you can fix it by configuring forwarder for DNS-over-HTTPS with URL + IP address like shown below. This will tell the DNS server the IP address and thus it wont require to find it out itself using recursive query.

https://dns.google/dns-query (8.8.8.8)
https://dns.google/dns-query (8.8.4.4)

You can also try DNS-over-TLS with Google, Cloudflare, or Quad9.

The issue you have seems mostly to be an issue with DNS queries being dropped at network level as seen in a log entry where the DNS server is unable to get any response from all root servers.

Do try the suggestions and let me know if any of them worked.

**Comment by ShreyasZare** [comment]
Also note that when you import a zone for "example.com", it will only import records for that domain and thus wont know where "support.example.com" is as you shown in the video demo. The server is correctly replying NameError for the domain since you have the zone imported and the server does not have any records for the sub domain in that zone. 

So, its best that you remove all the imported zones as it will create more issues that become difficult to debug.

**Comment by marcussacana** [comment]
In the true, this is more a ocasional bug, before not worked, and now is working, maybe in some days will occurs again and I will try do what you said, to it's hard to me 'debug' too... thank you.

I will close the issue until I have more information.
