### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by PonchoPowers** [TechnitiumSoftware/DnsServer#891]
If I start creating some unit tests would you accept a PR for them? I like the idea of testing everything to make the DNS server production ready, so I was thinking that a DnsServerCore.Tests would be quite useful, is this something you are interested in?

**Comment by ShreyasZare** [comment]
Thanks for the post. It would be nice to have it but due to the limited time I have, it would take up more time to maintain the tests since a lot of changes that are planned. Its not that there are no tests done, I do have an old school kind of test setup where certain aspects of the server are tested but its not pushed to the repo.
