### ISSUE TITLE
[FR] Option not to show dropped instances  in Top Clients list

### ISSUE THREAD

**Issue by squromiv** [TechnitiumSoftware/DnsServer#902]
I set some flooding subnets to drop in Drop Requests App options.
![screen_2024 04 10 001](https://github.com/TechnitiumSoftware/DnsServer/assets/15985877/6c9ac946-a33c-4961-9596-081dfd98dc78)

And these IPs still exist as clients in the main Dashboard.
![screen_2024 04 10 002](https://github.com/TechnitiumSoftware/DnsServer/assets/15985877/e4196ec9-f1ba-41ad-9480-6524c092a8d9)
 But they are really not my "clients". Also it is hard to understand whether they are already included in drop settings or not. I have to open Drop Requests App every time. It should be cool to hide info regarding ignored instances at all.

**Comment by ShreyasZare** [comment]
Thanks for the request. This was added recently so that the dropped stats are shown in Dashboard to make it clear when the client is hitting the query rate limit. The Drop Request app uses same mechanism to drop and thus the stats counter is unable to distinguish between both the cases.

Will get that updated so that both the cases are handled differently to prevent the clients that are blocked using Drop Requests to be listed as clients.

**Comment by squromiv** [comment]
> Will get that updated so that both the cases are handled differently to prevent the clients that are blocked using Drop Requests to be listed as clients.

It will be awesome! Thanks a lot. Will be waiting the next release.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v12.2.1 is now available that fixes this issue. Do update and let me know your feedback.
