### ISSUE TITLE
Feature Requests - Reorganise UI

### ISSUE THREAD

**Issue by rednus** [TechnitiumSoftware/DnsServer#907]
Hi Shreyas, I have started on this but haven't completed this yet. But here's the first part. 

![image](https://github.com/TechnitiumSoftware/DnsServer/assets/1540556/c74104cc-d964-439b-8f6d-71e9f801546b)

![image](https://github.com/TechnitiumSoftware/DnsServer/assets/1540556/2c2f01be-6f43-4bff-b792-f8a9af9ae8e2)

![image](https://github.com/TechnitiumSoftware/DnsServer/assets/1540556/2ad8df7f-c1c3-4fe0-b5fb-0a6ac055e1b0)

**Comment by ShreyasZare** [comment]
Thanks for the post. Do you mean to say that you have started to build a new UI or these are just suggestions?

**Comment by rednus** [comment]
Sorry to disappoint you. These are suggestions  - I can not do C#.

**Comment by ShreyasZare** [comment]
Thanks for the clarification. UI changes have low priority since a lot of core features are pending and are being prioritized.

The rearrangement of menus that you are suggesting does not take into account security policies so some of them wont be feasible. 

The DNS Apps GUI is already a planned feature and will be added once some of the planned features are implemented. The UI for these apps will be added one by one for each app and pushed in updates.

The Block Page app must use only port 80 and 443. Which is why there is no option to configure port for the app. This is since those are the default ports so when a website is blocked, the block page is shown for it as expected.

**Comment by rednus** [comment]
Thanks for the explanation. 

Is it possible to have the Advanced Blocking app as the main Blocking app. That would make life much easier?

**Comment by ShreyasZare** [comment]
> Is it possible to have the Advanced Blocking app as the main Blocking app. That would make life much easier?

For some users it would seem unnecessarily complicated instead of having a simple blocking feature that works for all users. The Advanced Blocking app will have a GUI eventually once DNS Apps get GUI support and that will make it equally easy for someone who is seeking advanced blocking options.
