### ISSUE TITLE
in-addr.arp

### ISSUE THREAD

**Issue by ChristoffBo** [TechnitiumSoftware/DnsServer#943]
Hi Sir,

I see my Opnsense box is hitting my DNS servers with alot of 10.in-addr.arpa requests and the rcode is NxDomain.

What i understand and my DNS skill are very limited is that in-addr.arpa is  revers host name lookups?

I do have the Auto PTR app installed. do you perhaps know how i can solve this?

Kind regards

**Comment by ShreyasZare** [comment]
Thanks for asking. Yes, those are reverse lookup queries that query for PTR record type. The response RCODE of NXDOMAIN is correct since 10.0.0.0/8 is a private IP address range. Its not really an issue and you can just ignore it. If there are too many requests, you can use the Drop Requests app to drop those specific requests.

The Auto PTR app can be used in this case by creating a primary zone for `10.in-addr.arpa` and then adding an APP record for Auto PTR app. This setup will just allow the private IP address in the request to resolve to some domain name that you configure.

**Comment by ChristoffBo** [comment]
thank you much appreciated

**Comment by ChristoffBo** [comment]
thank you
