### ISSUE TITLE
[ Feature Request ] backup with selections in name

### ISSUE THREAD

**Issue by bcookatpcsd** [TechnitiumSoftware/DnsServer#951]
Looking for a more granular way or a way to make a group of backup choices, and possibly automate.. 

I would like a basic set of app, settings, and zone.. or at least when a backup is made, that somehow what is in the backup can be determined from the name.. 

servername_date_time_backup-auth-settings-log-zone-apps-stats.zip

(what do you think is included in that backup.. ) :) 

Possibly someone else can articulate a better suggestion if this is not clear. 

Thank you for listening and continuing to work on this project; it is greatly appreciated.

**Comment by ShreyasZare** [comment]
Thanks for the request. There are currently 11 option in backup, so if 10 are selected, the filename would become too long which may have issues in some cases since file path size is limited on some platforms like Windows to 260 chars. The other issue with long file name would be that on the GUI, the file name will only be partially displayed so it wont be practically useful unless you use command line to list files. A lot of users could find that annoying too.
