### ISSUE TITLE
Use hosts file or have override hostnames

### ISSUE THREAD

**Issue by v0l** [TechnitiumSoftware/DnsServer#96]
Hi,

I think it would be good to have a feature where you can specify manual dns entries which override all aother paths to resolve hostnames.

For example consider the following:

I own the domain example.com and its resolved by dns.example.com.

Then for testing purposes i want to add an A entry pointing to localhost for testing purposes, maybe i have the following zone configured.

```
NS  dns.example.com
A    test.example.com 127.0.0.1
```

In this case my test domain will not resolve because dns.example.com does not have this entry.

If it where possible to try to resolve on the local zone first then via NS that would be great, or add a separate section in settings for override hostnames, and maybe lastly read from hosts file.

**Comment by ShreyasZare** [comment]
Hi,

Thanks for the feedback. There is another way that you can use to achieve what you wish. 

First, remove your zone and use the DNS Client tab to import the zone directly from your production DNS Server. Use ANY type to query so that all records get imported into your local zone.

Once you have all records in local zone, go ahead and disable the A record you have. Now, add a new A record that points to loopback address 127.0.0.1.

This setup is now ready, you can chose to disable one record and enable another to switch between both. And if you disable the entire zone then the DNS server will respond with live records from your production DNS server.

Let me know if this helps.

**Comment by v0l** [comment]
Hi,

This is a great suggestion thanks for the reply!

Unfortunately this doesn't seem to return all the entries from the dns server, In my case I am querying an internal AD server for machine names / internal host names, and for this i am working on some internal project where i want to use HTTPS with some test/dev internal site.

**Comment by ShreyasZare** [comment]
It seems you are looking for something like a conditional forwarding + ability to add records. 

You can put a wildcard (*) NS entry to delegate all sub domains to your internal DNS server while you can manage the main domain records on your current DNS server.
