### ISSUE TITLE
Allowed Domains Still Show Up Under "Top Blocked Domains" Section on Dashboard

### ISSUE THREAD

**Issue by KevinFumbles** [TechnitiumSoftware/DnsServer#966]
I've noticed that when I allow a domain using the Top Blocked Domains section on the Dashboard, the domain continues to show up under that section even though the domain gets resolved normally. So functionally the DNS server is working correctly, but I believe the UI is displaying it wrong.

I understand from reading #45 that it will show up there due to historical queries, but what I've noticed is that allowed domains continue to show up there. Here's an example of a domain I've allowed and resolves correctly but still shows up:

![IMG_7118](https://github.com/user-attachments/assets/2bff9d92-a1f6-4222-8d8d-7f6c0fef1c20)
![Dashboard](https://github.com/user-attachments/assets/3640f421-891c-4ef4-8ee3-2fc523f77c38)

**Comment by ShreyasZare** [comment]
Thanks for the post. The domain is showing up due to historic data as you have mentioned too. It will go away from the last hour stats after an hour. Similarly, it would go away from last day stats in 24 hrs.

If you still think its an issue then do install the Query Logs (Sqlite) app and use the Logs > Query Logs section to filter for Response Type as Blocked/CacheBlocked and confirm if you are still getting any blocked response for the same time period on for the dashboard stats.

**Comment by KevinFumbles** [comment]
Ahh I see what’s happening, thanks for the suggestion to use the query for verification.

I am blocking AAAA records globally so even though the A records are querying successfully, the domain still shows up as blocked because of the AAAA queries. So even though it’s _slightly_ annoying having them show up under blocked, I think the current display is the most accurate. I can see a benefit in having an option to filter domains from the Top Domains lists, but that seems pretty niche and not a priority so I’ll go ahead and close this. Thanks again!
