### ISSUE TITLE
Feature Request: make "Zones Per Page" & "Records Per Page" number persistant

### ISSUE THREAD

**Issue by FlossFarrier** [TechnitiumSoftware/DnsServer#975]
Hey.

Just a little thing, but with a big advantage (I think...):

I wonder if it is possible to make the "Zones Per Page" & "Records Per Page" pull down menus persistant or put a default value into the settings page.

Now it only persists until the browser cache is cleared.

It would be an improvement especially when working with a lot of large zones not having to adjust the number all the time.

**Comment by ShreyasZare** [comment]
Thanks for the post. These minor settings are stored in the browser storage to keep them persistent. So clearing site data will clear these values. These are deliberately not stored at the DNS server level since these would then require additional API call and for most intended purposes, minor preferences stored in browser data works. 

If you have configured to clear cache on browser close then there is exception option available which you can configure to exclude the DNS admin panel URL.

**Comment by FlossFarrier** [comment]
Yeah I noticed that. Now I understand the reason. Thanks!

**Comment by FlossFarrier** [comment]
-closed-
