### ISSUE TITLE
Changing the default password for Technitium DNS on a headless server

### ISSUE THREAD

**Issue by Chewie9999** [TechnitiumSoftware/DnsServer#98]
Thank you for writing this program, it looks very useful.

I have installed it on a VM that does not have any windowing system.

I have installed elinks so that I can get to the GUI and then reset the admin password so I can connect remotely, but either it needs some graphical element that elinks 0.12pre6 can't cope with, or there is another problem.
In the section near the bottom of the page (in elinks), that has a username box (read only), and a "new password" and "confirm password" text box, when I enter a password and click "Save", nothing happens.

When I try and log in remotely using admin / admin, it says "invalid username or password", which I assume is a security measure.

How can I change the security to either allow a log in remotely with admin/admin, or  can I change the password via the command line?

I can see a username in the /etc/dns/config/dns.config file, but I have no idea how it is hashed, and my programming skills aren't good enough yet to figure it out myself 

Thank you!

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Due to the magic of modern JavaScript, the DNS Server's web console GUI works only with Chrome, Firefox and Edge. Any other web browser will fail to work with it. 

The GUI does auto login attempt when page loads using default "admin" password and will prompt for password change when the login succeeds. 

It seems that you probably were able to change the password but didn't get success message due to JavaScript issues in elinks which is why when you try to login with default password didn't work.

I would suggest that you use the password recovery method to reset the password to default and then use any of the three browsers listed above to change the password and do the configuration.

Do post here if it worked.

**Comment by Chewie9999** [comment]
Hi Shreyas,
Sorry for the delay, I have been away from the location where I was trying to run the software.
No, it definitely didn't change the password, and using the password recovery didn't help.
I had to wait until I got back to my server and then used an SSH tunnel to forward the port, and then I was presented with the proper change password screen, and changing the password worked.

**Comment by ShreyasZare** [comment]
Thanks for the details. Good to know that you were able to use Firefox with ssh tunnel and use the web console.

The DNS Server config file is in binary format and password is hashed and thus it wont be practical edit it manually. The server provides HTTP API which the web console javascript uses to do actions. You could see the calls in Firefox developer tools, copy those HTTP request and make same requests using curl over shell to get it done.

**Comment by Chewie9999** [comment]
Ok, thanks for for the comment!

**Comment by gsamoela** [comment]
I ran into same limitation.

I worked around with the following commands. I post them here as I spent quite some time before finding that simple way.

# Get token
TOKEN=$(curl -s "http://localhost:5380/api/user/login?user=admin&pass=admin&includeInfo=true" | jq -r '.token')

#Change admin password
curl "http://localhost:5380/api/user/changePassword?token=$TOKEN&pass=MYSECRETPASS"

Hope this helps.
