### ISSUE TITLE
Technitium DNS not listening DOT/DOH

### ISSUE THREAD

**Issue by shadow-security1** [TechnitiumSoftware/DnsServer#980]
Im currently running v12.2.1 on rocky linux 9.4, im currently unable to get technitium to listen on ports 443 and 853 for DOT/DOH. I put in the pfx file along with the password. Im able to login into the server using the web interface without any issues. I do see technitium listening on port 53, 538, 5380, 8443 but not port 443 or 853. Selinux is enabled but there are no errors being reported that would inidicate selinux would be prohibting technitium from listening on those protected ports. The certificate comes from lets encrypt and is valid using the automatic renewal. And the firewall ports are open as well.

**Comment by ShreyasZare** [comment]
Thanks for the post. Please check the DNS Logs from the admin panel to see if there are any errors logged. Post the error log here if you need help understanding it.

**Comment by shadow-security1** [comment]
All im seeing is an issue with sqlite nothing else that would be pointing to a certificate error 
[2024-07-23.log](https://github.com/user-attachments/files/16352886/2024-07-23.log)

**Comment by ShreyasZare** [comment]
Thanks for the logs. The sqlite issue in there is due to corrupt db file. You need to either delete the file or update the Query Logs (Sqlite) app's config to use a different db file path.

You need to restart the DNS server once and then check the logs for errors. The DNS server will bind to the local port only when it starts or when the settings are modified. So, restarting the DNS server will cause it to attempt to bind and write an error log when it fails. Do share the error log details here.

**Comment by shadow-security1** [comment]
I was able to resolve the issue after removing the sqlite db app and clearing the database. Thanks for your help.
