### ISSUE TITLE
Enable HTTP3 causes binding to all interfaces on web service port

### ISSUE THREAD

**Issue by ruifung** [TechnitiumSoftware/DnsServer#996]
When HTTP3 is enabled for the Web Service, the HTTP3 listener does not respect the "Web Service Local Addresses" settings and binds to [::]:53443

This causes issues with not being able to update the Web Service Local Addresses setting with new IPv6 addresses because it detects a port conflict with itself, due to listening on the UDP port for all interfaces, regardless of what is actually specified.

Version 12.2.1

**Comment by ShreyasZare** [comment]
Thanks for asking. This is due to how the `libmsquic` implements it where it will bind on `[::]` address even when specific IP address is provided. This is their hard requirement and they wont be changing it.

The port detection code is being updated in the next release so this issue you see when changing local address will get resolved.
